/**
 * @module @agentforge/agents-code/test-writer
 *
 * Test Writer agent: generates unit, integration, and e2e tests from specs
 * and committed code. Pushes tests to the existing code gen branch.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import type {
  AgentContract,
  AgentContext,
  AgentWorkFn,
  Result,
  EventBus,
  TaskEntry,
} from '@agentforge/core';
import {
  Ok,
  Err,
  runAgent,
  readYaml,
} from '@agentforge/core';
import {
  retryOnSelfTestFailure,
} from '../frontend-coder/retry-handler.js';
import type { RetryConfig, SelfTestResult } from '../frontend-coder/retry-handler.js';
import {
  extractCodeFromOutput,
  collectStreamOutput,
} from '../frontend-coder/frontend-coder.js';

// ============================================================================
// Types
// ============================================================================

/** Input for the test writer agent. */
export interface TestWriterInput {
  readonly task: TaskEntry;
  readonly projectRoot: string;
  readonly stackConfigPath: string;
  readonly promptTemplatePath: string;
  /** Branch from the code gen task to push tests into. */
  readonly targetBranch: string;
  /** Files generated by the code gen task to write tests for. */
  readonly sourceFiles: readonly string[];
}

/** Output produced by the test writer agent. */
export interface TestWriterOutput {
  readonly branch: string;
  readonly testFilesGenerated: readonly string[];
  readonly totalCostUsd: number;
  readonly totalAttempts: number;
}

// ============================================================================
// Contract
// ============================================================================

/** The agent contract for the test writer. */
export const TEST_WRITER_CONTRACT: AgentContract = {
  role: 'test_writer',
  description: 'Generates unit, integration, and e2e tests from specs',
  category: 'code',
  provider: 'claude-sonnet-4',
  execution: { mode: 'stream', progress_events: true, max_context_tokens: 100000 },
  tools: ['github.read_file', 'github.push_files'],
  permissions: ['read_spec', 'read_code', 'write_code', 'create_branch', 'trigger_ci'],
  denied: ['deploy_staging', 'deploy_production', 'merge_pr', 'write_design'],
  hitl_policy: 'notify_only',
  budget: { max_tokens_per_task: 60000, max_cost_per_task_usd: 2.0 },
  on_complete: 'TestsComplete',
  on_error: 'retry(max=3) then notify_human + pause',
  context: {},
};

// ============================================================================
// System prompt loading
// ============================================================================

let promptTemplateCache: string | undefined;

const loadPromptTemplate = (templatePath: string): string => {
  if (promptTemplateCache) return promptTemplateCache;
  promptTemplateCache = readFileSync(templatePath, 'utf-8');
  return promptTemplateCache;
};

let stackConfigCache: string | undefined;

const loadStackConfig = (configPath: string): string => {
  if (stackConfigCache) return stackConfigCache;
  stackConfigCache = readFileSync(configPath, 'utf-8');
  return stackConfigCache;
};

// ============================================================================
// Helpers
// ============================================================================

/** Derive test file path from source file path. */
const toTestFilePath = (sourceFile: string): string => {
  const extMatch = /\.(tsx?|jsx?)$/.exec(sourceFile);
  if (!extMatch) return `${sourceFile}.test.ts`;
  const ext = extMatch[0];
  return sourceFile.replace(new RegExp(`${ext.replace('.', '\\.')}$`), `.test${ext}`);
};

// ============================================================================
// Work function
// ============================================================================

/**
 * The test writer's work function.
 * Called by runAgent after governance clears.
 */
export const testWriterWork: AgentWorkFn<TestWriterInput, TestWriterOutput> = async (
  input,
  provider,
  learnings,
  context,
) => {
  const { task, stackConfigPath, promptTemplatePath, targetBranch, sourceFiles } = input;
  const specRef = task.spec_ref;

  // 1. Read spec for expected behavior
  const specResult = readYaml<Record<string, unknown>>(
    join(context.projectRoot, specRef),
    context.fs,
  );
  if (!specResult.ok) {
    return Err({
      code: 'INVALID_STATE' as const,
      message: `Failed to read spec at ${specRef}: ${specResult.error.message}`,
      recoverable: false,
    });
  }

  // 2. Read source code from completed tasks' branches via MCP
  const sourceContents: Array<{ file: string; content: string }> = [];
  for (const sourceFile of sourceFiles) {
    const readResult = await context.mcpClient.callTool('github', 'read_file', {
      branch: targetBranch,
      path: sourceFile,
    });
    if (readResult.ok) {
      sourceContents.push({
        file: sourceFile,
        content: typeof readResult.value === 'string'
          ? readResult.value
          : JSON.stringify(readResult.value),
      });
    }
  }

  if (sourceContents.length === 0) {
    return Err({
      code: 'INVALID_STATE' as const,
      message: `No source files could be read from branch ${targetBranch}`,
      recoverable: false,
    });
  }

  // 3. Load stack config and prompt template
  const stackConfig = loadStackConfig(stackConfigPath);
  const promptTemplate = loadPromptTemplate(promptTemplatePath);

  // 4. Build the full system prompt
  const systemPrompt = [
    promptTemplate,
    '\n## Stack Configuration\n',
    '```yaml',
    stackConfig,
    '```',
  ].join('\n');

  // 5. Build the user message with all context
  const sourceCodeBlocks = sourceContents.map(
    (s) => `### ${s.file}\n\`\`\`typescript\n${s.content}\n\`\`\``,
  ).join('\n\n');

  const userMessage = [
    `## Spec\n\`\`\`json\n${JSON.stringify(specResult.value, null, 2)}\n\`\`\``,
    `\n## Source Code\n${sourceCodeBlocks}`,
    learnings.length > 0
      ? `\n## Agent Learnings\n${JSON.stringify(learnings, null, 2)}`
      : '',
    `\nGenerate comprehensive tests for the source files above following all conventions.`,
  ].join('\n');

  // 6. Generate tests for each source file
  const retryConfig: RetryConfig = {
    maxAttempts: 3,
    maxCostUsd: TEST_WRITER_CONTRACT.budget.max_cost_per_task_usd,
    maxCiRetries: 3,
  };

  const generate = async (errorContext?: string) => {
    const messages = [{ role: 'user' as const, content: userMessage }];
    if (errorContext) {
      messages.push({ role: 'user' as const, content: errorContext });
    }

    const prompt = { system: systemPrompt, messages };
    const stream = provider.stream(prompt, {
      model: TEST_WRITER_CONTRACT.provider,
      maxTokens: 8000,
      temperature: 0,
    });

    const collectResult = await collectStreamOutput(stream);
    if (!collectResult.ok) {
      return collectResult as Result<never>;
    }

    const code = extractCodeFromOutput(collectResult.value.content);
    return Ok({ code, cost: collectResult.value.cost });
  };

  // 7. Self-test for generated tests
  const selfTest = async (code: string): Promise<SelfTestResult> => {
    const errors: string[] = [];

    if (!code.includes('describe(') && !code.includes('describe (')) {
      errors.push('Missing describe block — tests must use describe/it pattern');
    }
    if (!code.includes('it(') && !code.includes('it (') && !code.includes('test(')) {
      errors.push('Missing it/test blocks — no test cases found');
    }
    if (code.includes(': any')) {
      errors.push('Contains `any` type — strict TypeScript mode forbids `any`');
    }

    return { passed: errors.length === 0, errors };
  };

  // 8. Run generation with self-test retry
  const genResult = await retryOnSelfTestFailure(generate, selfTest, retryConfig);
  if (!genResult.ok) {
    return genResult as Result<never>;
  }

  const { code, retryState } = genResult.value;

  // 9. Derive test file paths from source files
  const testFiles = sourceContents.map((s) => ({
    path: toTestFilePath(s.file),
    content: code,
  }));

  // 10. Push test files to the EXISTING branch (not creating a new one)
  const pushResult = await context.mcpClient.callTool('github', 'push_files', {
    branch: targetBranch,
    files: testFiles.map((f) => ({ path: f.path, content: f.content })),
  });
  if (!pushResult.ok) {
    return Err({
      code: 'GIT_PUSH_FAILED' as const,
      message: `Failed to push test files to ${targetBranch}: ${pushResult.error.message}`,
      recoverable: true,
    });
  }

  const testFilePaths = testFiles.map((f) => f.path);

  // 11. Emit TestsComplete event
  context.eventBus.publish({
    type: 'TestsComplete',
    taskId: task.id,
    agentId: TEST_WRITER_CONTRACT.role,
    branch: targetBranch,
    testFilesGenerated: testFilePaths,
    source: `agent:${TEST_WRITER_CONTRACT.role}`,
    timestamp: Date.now(),
  });

  return Ok({
    branch: targetBranch,
    testFilesGenerated: testFilePaths,
    totalCostUsd: retryState.totalCostUsd,
    totalAttempts: retryState.attempts.length,
  });
};

// ============================================================================
// Execution + Registration
// ============================================================================

/**
 * Execute the test writer agent through the full governance pipeline.
 */
export const executeTestWriter = async (
  contract: AgentContract,
  context: AgentContext,
  input: TestWriterInput,
): Promise<Result<unknown>> => {
  return runAgent(
    contract,
    context,
    input,
    'write_code',
    input.task.spec_ref,
    `Generate tests from spec ${input.task.spec_ref}`,
    testWriterWork,
  );
};

/**
 * Register the test writer to respond to CodeGenComplete events
 * for tasks that need test generation.
 */
export const registerTestWriter = (
  eventBus: EventBus,
  context: AgentContext,
  stackConfigPath: string,
  promptTemplatePath: string,
  contract: AgentContract = TEST_WRITER_CONTRACT,
): void => {
  eventBus.subscribe('CodeGenComplete', (event) => {
    void context.eventBus.publish({
      type: 'AgentStarted',
      agentId: contract.role,
      taskId: event.taskId,
      source: `agent:${contract.role}`,
      timestamp: Date.now(),
    });
  });
};
