const mockPenpotInput = {
    specRef: "spec-session-picker-1743465600000",
    moduleId: "session-picker",
    taskId: "task_design_penpot_1774770669051",
    planningOutput: {
        specRef: "spec-session-picker-1743465600000",
        moduleId: "session-picker",
        componentTree: [
            {
                name: "SessionPickerLayout",
                props: [
                    "maxWidth",
                    "paddingY",
                    "gap",
                    "background",
                ],
                children: [
                    "TopBar",
                    "GreetingHeader",
                    "StatStrip",
                    "SessionConfigCard",
                    "StartSessionButton",
                    "SettingsDialog",
                ],
            },
            {
                name: "TopBar",
                props: [
                    "height",
                    "background",
                    "showBackArrow",
                    "settingsIcon",
                    "settingsIconSize",
                    "ariaLabel",
                    "ariaHasPopup",
                ],
                children: [
                ],
            },
            {
                name: "GreetingHeader",
                props: [
                    "greeting",
                    "subtitle",
                    "timeOfDay",
                    "typography",
                    "subtitleTypography",
                ],
                children: [
                ],
            },
            {
                name: "StatStrip",
                props: [
                    "streakDays",
                    "weeklyHours",
                    "totalSessions",
                    "dividerColor",
                    "streakColor",
                    "ariaHidden",
                ],
                children: [
                ],
            },
            {
                name: "SessionConfigCard",
                props: [
                    "borderRadius",
                    "shadow",
                    "padding",
                    "gap",
                    "background",
                ],
                children: [
                    "SessionTypeCardGroup",
                    "DurationSection",
                    "ToggleSection",
                ],
            },
            {
                name: "SessionTypeCardGroup",
                props: [
                    "role",
                    "ariaLabel",
                    "gap",
                    "selectedId",
                ],
                children: [
                    "SessionTypeCard",
                ],
            },
            {
                name: "SessionTypeCard",
                props: [
                    "sessionTypeId",
                    "name",
                    "description",
                    "icon",
                    "colorToken",
                    "defaultDuration",
                    "isSelected",
                    "role",
                    "ariaChecked",
                    "borderRadius",
                    "shadow",
                    "selectedShadow",
                    "paddingX",
                    "paddingY",
                    "minHeight",
                    "minWidth",
                    "transitionDuration",
                ],
                children: [
                    "Avatar",
                ],
            },
            {
                name: "Avatar",
                props: [
                    "size",
                    "background",
                    "iconColor",
                    "ariaHidden",
                ],
                children: [
                ],
            },
            {
                name: "DurationSection",
                props: [
                    "label",
                    "gap",
                    "typography",
                ],
                children: [
                    "DurationChipRow",
                    "CustomDurationInput",
                ],
            },
            {
                name: "DurationChipRow",
                props: [
                    "role",
                    "ariaLabel",
                    "gap",
                    "chips",
                    "selectedValue",
                    "chipWidth",
                    "chipHeight",
                    "borderRadius",
                ],
                children: [
                    "Badge",
                ],
            },
            {
                name: "Badge",
                props: [
                    "role",
                    "ariaChecked",
                    "value",
                    "label",
                    "isSelected",
                    "variant",
                    "borderRadius",
                    "minWidth",
                    "minHeight",
                    "typography",
                ],
                children: [
                ],
            },
            {
                name: "CustomDurationInput",
                props: [
                    "isVisible",
                    "slideAnimationDuration",
                    "value",
                    "min",
                    "max",
                    "step",
                    "ariaLabel",
                    "ariaValueMin",
                    "ariaValueMax",
                    "ariaValueNow",
                    "borderRadius",
                    "background",
                    "paddingX",
                    "paddingY",
                ],
                children: [
                    "Input",
                    "Button",
                ],
            },
            {
                name: "Input",
                props: [
                    "type",
                    "ariaLabel",
                    "ariaValueMin",
                    "ariaValueMax",
                    "ariaValueNow",
                    "borderRadius",
                    "background",
                    "paddingX",
                    "paddingY",
                ],
                children: [
                ],
            },
            {
                name: "ToggleSection",
                props: [
                    "gap",
                    "conditionalBreakReminder",
                ],
                children: [
                    "BreakReminderToggle",
                    "AmbientSoundToggle",
                ],
            },
            {
                name: "BreakReminderToggle",
                props: [
                    "isVisible",
                    "isChecked",
                    "role",
                    "ariaChecked",
                    "ariaLabel",
                    "label",
                    "subLabel",
                    "minHeight",
                    "transitionDuration",
                ],
                children: [
                ],
            },
            {
                name: "AmbientSoundToggle",
                props: [
                    "isChecked",
                    "role",
                    "ariaChecked",
                    "ariaLabel",
                    "label",
                    "soundLabel",
                    "minHeight",
                ],
                children: [
                ],
            },
            {
                name: "StartSessionButton",
                props: [
                    "isDisabled",
                    "ariaDisabled",
                    "ariaLabel",
                    "label",
                    "height",
                    "borderRadius",
                    "typography",
                    "variant",
                    "transitionDuration",
                ],
                children: [
                    "Button",
                ],
            },
            {
                name: "SettingsDialog",
                props: [
                    "isOpen",
                    "role",
                    "ariaModal",
                    "ariaLabelledBy",
                    "maxWidth",
                    "borderRadius",
                    "shadow",
                    "zIndex",
                    "overlayColor",
                    "paddingX",
                    "paddingY",
                    "gap",
                ],
                children: [
                    "SoundSelectorChipGroup",
                    "NotificationsToggle",
                    "DarkModeToggle",
                ],
            },
        ],
        tokenBindings: {
            "SessionPickerLayout.background": "background-primary",
            "SessionPickerLayout.gap": "32",
            "SessionPickerLayout.paddingY": "48",
            "TopBar.background": "surface-primary",
            "TopBar.iconColor": "text-secondary",
            "GreetingHeader.color": "text-primary",
            "GreetingHeader.typography": "heading-1",
            "GreetingHeader.subtitleTypography": "body",
            "GreetingHeader.subtitleColor": "text-secondary",
            "StatStrip.streakColor": "warning",
            "StatStrip.textColor": "text-secondary",
            "StatStrip.typography": "body",
            "StatStrip.dividerColor": "border-default",
            "SessionConfigCard.background": "surface-primary",
            "SessionConfigCard.shadow": "elevation-1",
            "SessionConfigCard.borderRadius": "large",
            "SessionConfigCard.gap": "24",
            "SessionTypeCardGroup.gap": "12",
            "SessionTypeCard.background": "surface-primary",
            "SessionTypeCard.selectedBackground": "surface-elevated",
            "SessionTypeCard.shadow": "elevation-1",
            "SessionTypeCard.selectedShadow": "elevation-2",
            "SessionTypeCard.borderRadius": "large",
            "SessionTypeCard.titleTypography": "heading-2",
            "SessionTypeCard.titleColor": "text-primary",
            "SessionTypeCard.descriptionTypography": "body",
            "SessionTypeCard.descriptionColor": "text-secondary",
            "SessionTypeCard.selectedBorderColor": "cta-primary",
            "SessionTypeCard.selectedBackground2": "surface-elevated",
            "SessionTypeCard.transitionDuration": "duration-fast",
            "SessionTypeCard.minHeight": "touch-min-height",
            "Avatar.unselectedBackground": "surface-secondary",
            "Avatar.unselectedIconColor": "text-secondary",
            "Avatar.selectedBackground": "cta-primary",
            "Avatar.selectedIconColor": "text-on-cta",
            "DurationSection.labelTypography": "heading-3",
            "DurationSection.labelColor": "text-primary",
            "DurationSection.gap": "12",
            "DurationChipRow.gap": "8",
            "Badge.selectedBackground": "cta-primary",
            "Badge.selectedTextColor": "text-on-cta",
            "Badge.unselectedBackground": "surface-primary",
            "Badge.unselectedTextColor": "text-primary",
            "Badge.unselectedBorderColor": "border-default",
            "Badge.borderRadius": "pill",
            "Badge.typography": "label",
            "CustomDurationInput.background": "surface-input",
            "CustomDurationInput.borderColor": "border-default",
            "CustomDurationInput.focusBorderColor": "border-focus",
            "CustomDurationInput.borderRadius": "small",
            "CustomDurationInput.textColor": "text-primary",
            "CustomDurationInput.typography": "body",
            "CustomDurationInput.transitionDuration": "duration-fast",
            "ToggleSection.gap": "12",
            "BreakReminderToggle.labelTypography": "body",
            "BreakReminderToggle.labelColor": "text-primary",
            "BreakReminderToggle.subLabelTypography": "label",
            "BreakReminderToggle.subLabelColor": "text-secondary",
            "BreakReminderToggle.activeColor": "cta-primary",
            "BreakReminderToggle.transitionDuration": "duration-fast",
            "AmbientSoundToggle.labelTypography": "body",
            "AmbientSoundToggle.labelColor": "text-primary",
            "AmbientSoundToggle.activeColor": "cta-primary",
            "StartSessionButton.activeBackground": "cta-primary",
            "StartSessionButton.activeTextColor": "text-on-cta",
            "StartSessionButton.disabledBackground": "border-default",
            "StartSessionButton.disabledTextColor": "text-disabled",
            "StartSessionButton.borderRadius": "medium",
            "StartSessionButton.typography": "heading-2",
            "StartSessionButton.transitionDuration": "duration-fast",
            "SettingsDialog.background": "surface-primary",
            "SettingsDialog.shadow": "elevation-3",
            "SettingsDialog.borderRadius": "large",
            "SettingsDialog.overlay": "overlay",
            "SettingsDialog.zIndex": "z-modal",
            "SettingsDialog.titleTypography": "heading-2",
            "SettingsDialog.titleColor": "text-primary",
            "SettingsDialog.gap": "24",
        },
        responsiveRules: [
            {
                breakpoint: "desktop",
                behavior: "Single centered column, max-width 560px expanding to 600px at 1440px+, all components stacked vertically with 32px section gap",
                width: 1440,
                layout: "single-column",
                changes: [
                    "TopBar 56px tall transparent, settings gear right-aligned",
                    "GreetingHeader two-line centered stack",
                    "StatStrip three metrics inline with dot dividers",
                    "SessionTypeCard group vertical stack with 12px gap",
                    "DurationChipRow horizontal chip row with 8px gap",
                    "CustomDurationInput slide-down reveal below chip row",
                    "BreakReminderToggle and AmbientSoundToggle in vertical flex stack",
                    "StartSessionButton full-width 56px height at bottom of column",
                    "SettingsDialog centered modal max-width 400px with scrim overlay",
                ],
            },
        ],
        screens: [
            {
                name: "Session Picker",
                components: [
                    "SessionPickerLayout",
                    "TopBar",
                    "GreetingHeader",
                    "StatStrip",
                    "SessionConfigCard",
                    "SessionTypeCardGroup",
                    "SessionTypeCard",
                    "Avatar",
                    "DurationSection",
                    "DurationChipRow",
                    "Badge",
                    "CustomDurationInput",
                    "Input",
                    "ToggleSection",
                    "BreakReminderToggle",
                    "AmbientSoundToggle",
                    "StartSessionButton",
                    "SettingsDialog",
                ],
            },
        ],
    },
    description: "Entry screen where users select a session type (Deep Work, Meditation, Power Nap), configure duration via preset chips or custom input, toggle break reminders and ambient sound, and initiate the session. Displays a greeting header with time-of-day awareness, a stat strip showing streak, weekly hours, and total sessions, and a disabled Start button until a session type is selected.",
    designSystemPrompt: "# Design System — Calm, focused, and welcoming. Quiet confidence without sterility. Every word earns its place.\nAudience: general\nWCAG: AA\n\n## Colors\n- indigo-600: `{ r: 0.31, g: 0.27, b: 0.90 }`\n- indigo-100: `{ r: 0.88, g: 0.91, b: 1.00 }`\n- indigo-50: `{ r: 0.93, g: 0.95, b: 1.00 }`\n- slate-900: `{ r: 0.06, g: 0.09, b: 0.16 }`\n- slate-500: `{ r: 0.39, g: 0.45, b: 0.55 }`\n- slate-100: `{ r: 0.95, g: 0.96, b: 0.98 }`\n- emerald-500: `{ r: 0.06, g: 0.73, b: 0.51 }`\n- rose-500: `{ r: 0.96, g: 0.25, b: 0.37 }`\n- amber-500: `{ r: 0.96, g: 0.62, b: 0.04 }`\n\n## Semantic Roles\n(Maps semantic names used in component tokens to actual color values)\n- background-primary -> slate-100 (#F1F5F9)\n- surface-primary -> #FFFFFF\n- surface-elevated -> #FFFFFF\n- text-primary -> slate-900 (#0F172A)\n- text-secondary -> slate-500 (#64748B)\n- text-disabled -> #94A3B8\n- text-on-cta -> #FFFFFF\n- cta-primary -> indigo-600 (#4F46E5)\n- cta-hover -> #4338CA\n- border-default -> #E2E8F0\n- border-focus -> indigo-600 (#4F46E5)\n- border-error -> rose-500 (#F43F5E)\n- error -> rose-500 (#F43F5E)\n- success -> emerald-500 (#10B981)\n- warning -> amber-500 (#F59E0B)\n- info -> indigo-600 (#4F46E5)\n- overlay -> rgba(15,23,42,0.4)\n- surface-secondary -> #F8FAFC\n- surface-input -> #FFFFFF\n\n## Typography\n- heading-1: 24px/1.3, weight 700 (display)\n- heading-2: 16px/1.4, weight 600 (display)\n- heading-3: 15px/1.4, weight 600 (display)\n- body: 14px/1.5, weight 400 (display)\n- label: 12px/1.4, weight 500 (display)\n- small: 64px/1, weight 300 (display)\n\n## Spacing\nUnit: 8px | Scale: 4, 8, 12, 16, 24, 32, 48, 64",
    componentCatalogPrompt: "# Component Catalog\n\n## Layout\n\n### Card\nContent container with optional header, body, and footer sections\n\n**Anatomy:**\n- **header** *(optional)*: title (heading-3), subtitle (body), action (Button) [heading-3]\n- **body**: Primary content area — text, images, or nested components\n- **footer** *(optional)*: action buttons (Button[]), metadata (label)\n\n**States:**\n- **default**: bg=surface-primary, text=text-primary, shadow=shadow-sm\n- **hover**: bg=surface-primary, text=text-primary, shadow=shadow-md\n- **selected**: bg=surface-secondary, text=text-primary, border=cta-primary, border-width=2px, shadow=shadow-md\n\n**Token Bindings:**\n- background: surface-primary\n- text: text-primary\n- border-radius: medium\n- padding-x: 20\n- padding-y: 16\n- font: heading-3\n\n**Spacing:** padding=16 20, gap=12\n\n**Accessibility:**\n- Focus ring: visible\n- role=article when standalone\n- aria-labelledby=title-id\n\n### Section\nPage section with heading and content area\n\n**Anatomy:**\n- **header**: title (heading-2), description (body) [heading-2]\n- **body**: Section content — cards, lists, tables\n\n**States:**\n- **default**: bg=surface-primary, text=text-primary\n\n**Token Bindings:**\n- background: surface-primary\n- text: text-primary\n- font: heading-2\n\n**Spacing:** padding=24 0, gap=16\n\n**Accessibility:**\n- role=region\n- aria-labelledby=section-title\n\n### NavigationBar\nTop-level navigation with logo, nav links, and user actions\n\n**Anatomy:**\n- **brand**: logo (image), app name (heading-3)\n- **nav_links**: Link[] with active state indicator\n- **actions** *(optional)*: user avatar (Avatar), notifications (Badge), settings (Button)\n\n**States:**\n- **default**: bg=surface-primary, text=text-primary, shadow=shadow-sm\n\n**Token Bindings:**\n- background: surface-primary\n- text: text-primary\n- border-radius: medium\n- padding-x: 24\n- padding-y: 0\n\n**Spacing:** padding=0 24, gap=16\n\n**Accessibility:**\n- Focus ring: visible\n- role=navigation\n- aria-label=Main navigation\n- Keyboard: Arrow keys between nav items, Enter to activate\n\n### Sidebar\nVertical navigation panel with collapsible sections\n\n**Anatomy:**\n- **header** *(optional)*: logo or app name (heading-3)\n- **nav_groups**: SidebarGroup[] each with label and nav items\n- **footer** *(optional)*: user info, settings link\n\n**States:**\n- **default**: bg=surface-secondary, text=text-primary\n- **collapsed**: bg=surface-secondary, text=text-primary\n\n**Token Bindings:**\n- background: surface-secondary\n- text: text-primary\n\n**Spacing:** padding=16, gap=8\n\n**Accessibility:**\n- Focus ring: visible\n- role=navigation\n- aria-label=Sidebar navigation\n- Keyboard: Tab between items, Enter to expand/collapse groups\n\n### PageHeader\nTop section of a page with title, breadcrumbs, and page-level actions\n\n**Anatomy:**\n- **breadcrumbs** *(optional)*: Breadcrumb trail (Breadcrumb)\n- **title_row**: page title (heading-1), action buttons (Button[])\n- **description** *(optional)*: page description or subtitle (body)\n\n**States:**\n- **default**: bg=surface-primary, text=text-primary\n\n**Token Bindings:**\n- background: surface-primary\n- text: text-primary\n\n**Spacing:** padding=24 0, gap=8\n\n**Accessibility:**\n- role=banner\n\n### Footer\nPage footer with links, copyright, and secondary actions\n\n**Anatomy:**\n- **nav_columns**: link groups with section titles (label) and Link[]\n- **bottom_bar**: copyright (small), social links, legal links\n\n**States:**\n- **default**: bg=surface-secondary, text=text-secondary\n\n**Token Bindings:**\n- background: surface-secondary\n- text: text-secondary\n- padding-x: 24\n- padding-y: 32\n\n**Spacing:** padding=32 24, gap=24\n\n**Accessibility:**\n- role=contentinfo\n\n## Data Display\n\n### DataTable\nTabular data with sortable columns, pagination, and row actions\n\n**Anatomy:**\n- **header_row**: column headers (label) with sort indicators\n- **body_rows**: data cells aligned to columns, optional row selection checkbox\n- **pagination** *(optional)*: page controls (Pagination), rows-per-page selector\n\n**States:**\n- **default**: bg=surface-primary, text=text-primary, border=border-default\n- **hover_row**: bg=surface-secondary, text=text-primary\n- **selected_row**: bg=cta-primary, text=text-primary, opacity=0.1\n\n**Token Bindings:**\n- background: surface-primary\n- text: text-primary\n- border-radius: medium\n\n**Spacing:** padding=12, gap=0\n\n**Accessibility:**\n- Focus ring: visible\n- role=table\n- aria-label=Data table description\n- Keyboard: Arrow keys between cells, Enter to sort column headers\n\n### Badge\nSmall status indicator label\n\n**Anatomy:**\n- **label**: status text (small) [small]\n- **icon** *(optional)*: optional status icon\n\n**Variants:**\n- **success**: bg=success, text=success, opacity=0.15\n- **warning**: bg=warning, text=warning, opacity=0.15\n- **error**: bg=error, text=error, opacity=0.15\n- **info**: bg=cta-primary, text=cta-primary, opacity=0.15\n\n**States:**\n- **default**: bg=surface-secondary, text=text-secondary\n\n**Token Bindings:**\n- background: surface-secondary\n- text: text-secondary\n- padding-x: 8\n- padding-y: 2\n- font: small\n\n**Spacing:** padding=2 8, gap=4\n\n**Accessibility:**\n- role=status\n\n### Avatar\nUser or entity avatar with image or initials fallback\n\n**Anatomy:**\n- **image**: user photo or initials (label)\n- **status_indicator** *(optional)*: online/offline dot (Badge)\n\n**States:**\n- **default**: bg=surface-secondary, text=text-primary\n\n**Token Bindings:**\n- background: surface-secondary\n- text: text-primary\n\n**Spacing:** padding=0, gap=0\n\n**Accessibility:**\n- role=img\n- aria-label=User name\n\n### Chip\nCompact interactive label for filtering or selection\n\n**Anatomy:**\n- **label**: chip text (label) [label]\n- **remove_button** *(optional)*: close/remove icon\n\n**States:**\n- **default**: bg=surface-secondary, text=text-primary, border=border-default\n- **selected**: bg=cta-primary, text=text-on-cta, border=cta-primary\n- **disabled**: bg=surface-secondary, text=text-secondary, opacity=0.5\n\n**Token Bindings:**\n- background: surface-secondary\n- text: text-primary\n- border-radius: medium\n- padding-x: 12\n- padding-y: 4\n- font: label\n\n**Min Height:** 44px\n\n**Spacing:** padding=4 12, gap=4\n\n**Accessibility:**\n- Focus ring: visible\n- role=option when in list\n- Keyboard: Enter to toggle, Delete to remove\n\n### EmptyState\nPlaceholder shown when a section has no data\n\n**Anatomy:**\n- **illustration** *(optional)*: decorative image or icon\n- **title**: heading message (heading-3) [heading-3]\n- **description**: explanatory text (body)\n- **action** *(optional)*: primary CTA button (Button)\n\n**States:**\n- **default**: bg=surface-primary, text=text-secondary\n\n**Token Bindings:**\n- background: surface-primary\n- text: text-secondary\n- font: heading-3\n\n**Spacing:** padding=32, gap=12\n\n**Accessibility:**\n- role=status\n- aria-label=No data available\n\n### Stat\nSingle metric display with label, value, and optional trend\n\n**Anatomy:**\n- **label**: metric label (label) [label]\n- **value**: metric value (heading-1 or heading-2) [heading-2]\n- **trend** *(optional)*: change indicator (small) with up/down icon\n\n**Variants:**\n- **positive**: bg=surface-primary, text=success\n- **negative**: bg=surface-primary, text=error\n\n**States:**\n- **default**: bg=surface-primary, text=text-primary\n\n**Token Bindings:**\n- background: surface-primary\n- text: text-primary\n- font: label\n\n**Spacing:** padding=16, gap=4\n\n**Accessibility:**\n- role=figure\n- aria-label=Metric description\n\n## Input\n\n### Button\nInteractive button with variants for primary, secondary, and ghost actions\n\n**Anatomy:**\n- **icon_leading** *(optional)*: optional leading icon\n- **label**: button text (label) [label]\n- **icon_trailing** *(optional)*: optional trailing icon\n\n**Variants:**\n- **primary**: bg=cta-primary, text=text-on-cta\n- **secondary**: bg=surface-primary, text=text-primary, border=border-default\n- **ghost**: bg=transparent, text=cta-primary\n- **destructive**: bg=error, text=text-on-cta\n\n**States:**\n- **default**: bg=cta-primary, text=text-on-cta, border=cta-primary, shadow=shadow-sm\n- **hover**: bg=cta-primary, text=text-on-cta, shadow=shadow-md\n- **disabled**: bg=surface-secondary, text=text-secondary, opacity=0.5\n\n**Token Bindings:**\n- background: cta-primary\n- text: text-on-cta\n- border-radius: medium\n- padding-x: 16\n- padding-y: 8\n- font: label\n\n**Min Height:** 44px\n\n**Spacing:** padding=8 16, gap=8\n\n**Accessibility:**\n- Focus ring: visible\n- aria-label when icon-only\n- Keyboard: Enter or Space to activate\n\n### Input\nText input field with label, helper text, and validation states\n\n**Anatomy:**\n- **label**: field label (label) [label]\n- **input_field**: text input with placeholder\n- **helper_text** *(optional)*: description or error message (small)\n\n**States:**\n- **default**: bg=surface-primary, text=text-primary, border=border-default, border-width=1px\n- **focus**: bg=surface-primary, text=text-primary, border=cta-primary, border-width=2px, shadow=shadow-sm\n- **error**: bg=surface-primary, text=text-primary, border=error, border-width=2px\n- **disabled**: bg=surface-secondary, text=text-secondary, opacity=0.5\n\n**Token Bindings:**\n- background: surface-primary\n- text: text-primary\n- border-radius: medium\n- padding-x: 12\n- padding-y: 8\n- font: label\n\n**Min Height:** 44px\n\n**Spacing:** padding=8 12, gap=4\n\n**Accessibility:**\n- Focus ring: visible\n- aria-describedby=helper-text-id\n- aria-invalid=true when error\n- Keyboard: Tab to focus, type to enter text\n\n### Select\nDropdown selection with single or multi-select support\n\n**Anatomy:**\n- **label** *(optional)*: field label (label) [label]\n- **trigger**: selected value display with chevron icon\n- **options_list**: SelectOption[] with text and optional icons\n\n**States:**\n- **default**: bg=surface-primary, text=text-primary, border=border-default\n- **open**: bg=surface-primary, text=text-primary, border=cta-primary, shadow=shadow-lg\n- **disabled**: bg=surface-secondary, text=text-secondary, opacity=0.5\n\n**Token Bindings:**\n- background: surface-primary\n- text: text-primary\n- border-radius: medium\n- padding-x: 12\n- padding-y: 8\n- font: label\n\n**Min Height:** 44px\n\n**Spacing:** padding=8 12, gap=4\n\n**Accessibility:**\n- Focus ring: visible\n- role=listbox\n- aria-expanded=true when open\n- Keyboard: Arrow keys to navigate, Enter to select, Escape to close\n\n### Checkbox\nToggle checkbox with label\n\n**Anatomy:**\n- **checkbox**: check indicator box\n- **label**: label text (body) [body]\n\n**States:**\n- **default**: bg=surface-primary, text=text-primary, border=border-default\n- **checked**: bg=cta-primary, text=text-on-cta, border=cta-primary\n- **disabled**: bg=surface-secondary, text=text-secondary, opacity=0.5\n\n**Token Bindings:**\n- background: surface-primary\n- text: text-primary\n- border-radius: medium\n- font: body\n\n**Min Height:** 44px\n\n**Spacing:** padding=0, gap=8\n\n**Accessibility:**\n- Focus ring: visible\n- role=checkbox\n- aria-checked\n- Keyboard: Space to toggle\n\n### Radio\nRadio button for single selection within a group\n\n**Anatomy:**\n- **radio**: radio circle indicator\n- **label**: option label (body) [body]\n\n**States:**\n- **default**: bg=surface-primary, text=text-primary, border=border-default\n- **selected**: bg=cta-primary, text=text-primary, border=cta-primary\n- **disabled**: bg=surface-secondary, text=text-secondary, opacity=0.5\n\n**Token Bindings:**\n- background: surface-primary\n- text: text-primary\n- border-radius: medium\n- font: body\n\n**Min Height:** 44px\n\n**Spacing:** padding=0, gap=8\n\n**Accessibility:**\n- Focus ring: visible\n- role=radio\n- aria-checked\n- Keyboard: Arrow keys within group, Space to select\n\n### Switch\nToggle switch for binary on/off settings\n\n**Anatomy:**\n- **track**: switch track background\n- **thumb**: sliding thumb indicator\n- **label** *(optional)*: setting label (body) [body]\n\n**States:**\n- **default**: bg=surface-secondary, text=text-primary, border=border-default\n- **checked**: bg=cta-primary, text=text-on-cta\n- **disabled**: bg=surface-secondary, text=text-secondary, opacity=0.5\n\n**Token Bindings:**\n- background: surface-secondary\n- text: text-primary\n- border-radius: medium\n- font: body\n\n**Min Height:** 44px\n\n**Spacing:** padding=0, gap=8\n\n**Accessibility:**\n- Focus ring: visible\n- role=switch\n- aria-checked\n- Keyboard: Space to toggle\n\n### TextArea\nMulti-line text input for longer content\n\n**Anatomy:**\n- **label** *(optional)*: field label (label) [label]\n- **textarea**: multi-line text input with placeholder\n- **character_count** *(optional)*: remaining/total character count (small)\n\n**States:**\n- **default**: bg=surface-primary, text=text-primary, border=border-default\n- **focus**: bg=surface-primary, text=text-primary, border=cta-primary, border-width=2px\n- **error**: bg=surface-primary, text=text-primary, border=error, border-width=2px\n- **disabled**: bg=surface-secondary, text=text-secondary, opacity=0.5\n\n**Token Bindings:**\n- background: surface-primary\n- text: text-primary\n- border-radius: medium\n- padding-x: 12\n- padding-y: 8\n- font: label\n\n**Min Height:** 44px\n\n**Spacing:** padding=8 12, gap=4\n\n**Accessibility:**\n- Focus ring: visible\n- aria-describedby=helper-text-id\n- Keyboard: Tab to focus, type to enter text\n\n### DatePicker\nDate selection input with calendar dropdown\n\n**Anatomy:**\n- **label** *(optional)*: field label (label) [label]\n- **trigger**: date display with calendar icon\n- **calendar**: month grid with selectable days\n\n**States:**\n- **default**: bg=surface-primary, text=text-primary, border=border-default\n- **open**: bg=surface-primary, text=text-primary, border=cta-primary, shadow=shadow-lg\n- **disabled**: bg=surface-secondary, text=text-secondary, opacity=0.5\n\n**Token Bindings:**\n- background: surface-primary\n- text: text-primary\n- border-radius: medium\n- padding-x: 12\n- padding-y: 8\n- font: label\n\n**Min Height:** 44px\n\n**Spacing:** padding=8 12, gap=4\n\n**Accessibility:**\n- Focus ring: visible\n- role=dialog for calendar\n- aria-label=Choose date\n- Keyboard: Arrow keys to navigate calendar, Enter to select\n\n### SearchInput\nSearch input with icon and optional clear button\n\n**Anatomy:**\n- **search_icon**: magnifying glass icon\n- **input_field**: search text input with placeholder\n- **clear_button** *(optional)*: clear/X button\n\n**States:**\n- **default**: bg=surface-secondary, text=text-primary, border=border-default\n- **focus**: bg=surface-primary, text=text-primary, border=cta-primary, shadow=shadow-sm\n\n**Token Bindings:**\n- background: surface-secondary\n- text: text-primary\n- border-radius: medium\n- padding-x: 12\n- padding-y: 8\n\n**Min Height:** 44px\n\n**Spacing:** padding=8 12, gap=8\n\n**Accessibility:**\n- Focus ring: visible\n- role=search\n- aria-label=Search\n- Keyboard: Escape to clear\n\n## Feedback\n\n### Alert\nInline notification message with severity levels\n\n**Anatomy:**\n- **icon**: severity icon (info, warning, error, success)\n- **title** *(optional)*: alert title (label) [label]\n- **message**: alert description (body)\n- **dismiss** *(optional)*: close button\n\n**Variants:**\n- **success**: bg=success, text=success, opacity=0.1\n- **warning**: bg=warning, text=warning, opacity=0.1\n- **error**: bg=error, text=error, opacity=0.1\n\n**States:**\n- **default**: bg=cta-primary, text=text-primary, border=cta-primary, opacity=0.1\n\n**Token Bindings:**\n- background: cta-primary\n- text: text-primary\n- border-radius: medium\n- padding-x: 16\n- padding-y: 12\n- font: label\n\n**Spacing:** padding=12 16, gap=8\n\n**Accessibility:**\n- role=alert\n\n### Modal\nOverlay dialog for focused interactions\n\n**Anatomy:**\n- **overlay**: dimmed background overlay\n- **header**: dialog title (heading-2), close button [heading-2]\n- **body**: dialog content area\n- **footer** *(optional)*: action buttons — cancel (secondary), confirm (primary)\n\n**States:**\n- **default**: bg=surface-primary, text=text-primary, shadow=shadow-lg\n\n**Token Bindings:**\n- background: surface-primary\n- text: text-primary\n- font: heading-2\n\n**Spacing:** padding=24, gap=16\n\n**Accessibility:**\n- Focus ring: visible\n- role=dialog\n- aria-modal=true\n- aria-labelledby=dialog-title\n- Keyboard: Escape to close, Tab traps focus within dialog\n\n### LoadingSpinner\nAnimated loading indicator\n\n**Anatomy:**\n- **spinner**: animated circular indicator\n- **label** *(optional)*: loading message (body)\n\n**States:**\n- **default**: bg=transparent, text=text-secondary\n\n**Token Bindings:**\n- background: transparent\n- text: text-secondary\n\n**Spacing:** padding=0, gap=8\n\n**Accessibility:**\n- role=status\n- aria-label=Loading\n\n### ProgressBar\nLinear progress indicator showing completion percentage\n\n**Anatomy:**\n- **track**: background track\n- **fill**: progress fill bar\n- **label** *(optional)*: percentage or status text (small) [small]\n\n**Variants:**\n- **active**: bg=surface-secondary, text=cta-primary\n- **success**: bg=surface-secondary, text=success\n- **error**: bg=surface-secondary, text=error\n\n**States:**\n- **default**: bg=surface-secondary, text=text-secondary\n\n**Token Bindings:**\n- background: surface-secondary\n- text: text-secondary\n- font: small\n\n**Spacing:** padding=0, gap=4\n\n**Accessibility:**\n- role=progressbar\n- aria-valuenow\n- aria-valuemin=0\n- aria-valuemax=100\n\n### Skeleton\nPlaceholder loading state that mimics content layout\n\n**Anatomy:**\n- **shape**: rectangular or circular placeholder matching content dimensions\n\n**States:**\n- **default**: bg=surface-secondary, text=transparent, opacity=0.6\n\n**Token Bindings:**\n- background: surface-secondary\n- text: transparent\n\n**Spacing:** padding=0, gap=0\n\n**Accessibility:**\n- aria-hidden=true\n\n## Navigation\n\n### Tabs\nTab bar for switching between content panels\n\n**Anatomy:**\n- **tab_list**: Tab[] with label and optional icon\n- **tab_panels**: content panels corresponding to each tab\n\n**States:**\n- **default**: bg=surface-primary, text=text-secondary, border=border-default\n- **active**: bg=surface-primary, text=text-primary, border=cta-primary, border-width=2px\n- **hover**: bg=surface-secondary, text=text-primary\n- **disabled**: bg=surface-primary, text=text-secondary, opacity=0.5\n\n**Token Bindings:**\n- background: surface-primary\n- text: text-secondary\n- border-radius: medium\n- padding-x: 16\n- padding-y: 8\n\n**Min Height:** 44px\n\n**Spacing:** padding=8 16, gap=0\n\n**Accessibility:**\n- Focus ring: visible\n- role=tablist\n- aria-selected on active tab\n- Keyboard: Arrow keys between tabs, Enter to activate\n\n### StepIndicator\nMulti-step progress indicator for wizards and workflows\n\n**Anatomy:**\n- **steps**: StepItem[] with number/icon, label, and connector line\n- **content**: current step content area\n\n**States:**\n- **default**: bg=surface-primary, text=text-secondary, border=border-default\n- **active**: bg=cta-primary, text=text-on-cta\n- **completed**: bg=success, text=text-on-cta\n\n**Token Bindings:**\n- background: surface-primary\n- text: text-secondary\n- border-radius: medium\n\n**Min Height:** 44px\n\n**Spacing:** padding=0, gap=16\n\n**Accessibility:**\n- Focus ring: visible\n- role=list\n- aria-current=step on active\n- Keyboard: Tab between steps\n\n### Breadcrumb\nNavigation trail showing current page location\n\n**Anatomy:**\n- **items**: BreadcrumbItem[] with link text and separator\n- **current**: current page name (label) — not a link [label]\n\n**States:**\n- **default**: bg=transparent, text=text-secondary\n- **hover**: bg=transparent, text=cta-primary\n\n**Token Bindings:**\n- background: transparent\n- text: text-secondary\n- font: label\n\n**Min Height:** 44px\n\n**Spacing:** padding=0, gap=4\n\n**Accessibility:**\n- Focus ring: visible\n- role=navigation\n- aria-label=Breadcrumb\n\n### Pagination\nPage navigation controls for paginated content\n\n**Anatomy:**\n- **prev_button**: previous page button\n- **page_numbers**: page number buttons with ellipsis\n- **next_button**: next page button\n\n**States:**\n- **default**: bg=surface-primary, text=text-primary, border=border-default\n- **active**: bg=cta-primary, text=text-on-cta\n- **disabled**: bg=surface-primary, text=text-secondary, opacity=0.5\n\n**Token Bindings:**\n- background: surface-primary\n- text: text-primary\n- border-radius: medium\n\n**Min Height:** 44px\n\n**Spacing:** padding=0, gap=4\n\n**Accessibility:**\n- Focus ring: visible\n- role=navigation\n- aria-label=Pagination\n- Keyboard: Arrow keys between pages, Enter to select\n\n### Link\nInline or standalone hyperlink\n\n**Anatomy:**\n- **text**: link text (body) [body]\n- **icon** *(optional)*: optional external link icon\n\n**States:**\n- **default**: bg=transparent, text=cta-primary\n- **hover**: bg=transparent, text=cta-primary, opacity=0.8\n- **visited**: bg=transparent, text=text-secondary\n\n**Token Bindings:**\n- background: transparent\n- text: cta-primary\n- font: body\n\n**Min Height:** 44px\n\n**Spacing:** padding=0, gap=4\n\n**Accessibility:**\n- Focus ring: visible\n- role=link\n- Keyboard: Enter to follow\n\n## Composite\n\n### Form\nForm container with field groups, validation, and submit action\n\n**Anatomy:**\n- **fields**: Input[], Select[], TextArea[], Checkbox[], Radio[] arranged in groups\n- **actions**: submit Button (primary), cancel Button (secondary)\n\n**States:**\n- **default**: bg=surface-primary, text=text-primary\n- **submitting**: bg=surface-primary, text=text-secondary, opacity=0.7\n\n**Token Bindings:**\n- background: surface-primary\n- text: text-primary\n\n**Spacing:** padding=24, gap=16\n\n**Accessibility:**\n- Focus ring: visible\n- role=form\n- aria-label=Form description\n- Keyboard: Tab between fields, Enter to submit\n\n### SelectionGrid\nGrid of selectable cards for option picking\n\n**Anatomy:**\n- **grid**: Card[] in responsive grid layout, each with selection state\n- **selection_indicator**: checkmark or highlight on selected cards\n\n**States:**\n- **default**: bg=surface-primary, text=text-primary, border=border-default\n- **selected**: bg=surface-secondary, text=text-primary, border=cta-primary, border-width=2px, shadow=shadow-md\n\n**Token Bindings:**\n- background: surface-primary\n- text: text-primary\n- border-radius: medium\n\n**Spacing:** padding=0, gap=16\n\n**Accessibility:**\n- Focus ring: visible\n- role=listbox\n- aria-multiselectable when multi-select\n- Keyboard: Arrow keys between cards, Space to toggle selection\n\n### FilterBar\nHorizontal bar with filter controls for data views\n\n**Anatomy:**\n- **filters**: Select[], Input[], DatePicker[] for filter criteria\n- **active_filters** *(optional)*: Chip[] showing currently active filters with remove action\n- **actions**: apply Button, clear-all Link\n\n**States:**\n- **default**: bg=surface-primary, text=text-primary\n\n**Token Bindings:**\n- background: surface-primary\n- text: text-primary\n- padding-x: 16\n- padding-y: 12\n\n**Spacing:** padding=12 16, gap=12\n\n**Accessibility:**\n- Focus ring: visible\n- role=search\n- aria-label=Filter controls\n- Keyboard: Tab between filter controls\n",
    viewportWidth: 1440,
    useDesignSpecV2: true,
    rendererTokens: {
        colors: {
            primitive: {
                "indigo-600": "#4F46E5",
                "indigo-100": "#E0E7FF",
                "indigo-50": "#EEF2FF",
                "slate-900": "#0F172A",
                "slate-500": "#64748B",
                "slate-100": "#F1F5F9",
                "emerald-500": "#10B981",
                "rose-500": "#F43F5E",
                "amber-500": "#F59E0B",
            },
            semantic: {
                "background-primary": "slate-100",
                "surface-primary": "#FFFFFF",
                "surface-elevated": "#FFFFFF",
                "text-primary": "slate-900",
                "text-secondary": "slate-500",
                "text-disabled": "#94A3B8",
                "text-on-cta": "#FFFFFF",
                "cta-primary": "indigo-600",
                "cta-hover": "#4338CA",
                "border-default": "#E2E8F0",
                "border-focus": "indigo-600",
                "border-error": "rose-500",
                error: "rose-500",
                success: "emerald-500",
                warning: "amber-500",
                info: "indigo-600",
                overlay: "rgba(15,23,42,0.4)",
                "surface-secondary": "#F8FAFC",
                "surface-input": "#FFFFFF",
            },
        },
        typography: {
            font_families: {
                display: "Inter",
                body: "Inter",
            },
            scale: [
                {
                    role: "heading-1",
                    size: 24,
                    weight: 700,
                    family: "display",
                    line_height: 1.3,
                },
                {
                    role: "heading-2",
                    size: 16,
                    weight: 600,
                    family: "display",
                    line_height: 1.4,
                },
                {
                    role: "heading-3",
                    size: 15,
                    weight: 600,
                    family: "display",
                    line_height: 1.4,
                },
                {
                    role: "body",
                    size: 14,
                    weight: 400,
                    family: "display",
                    line_height: 1.5,
                },
                {
                    role: "label",
                    size: 12,
                    weight: 500,
                    family: "display",
                    line_height: 1.4,
                },
                {
                    role: "small",
                    size: 64,
                    weight: 300,
                    family: "display",
                    line_height: 1,
                },
            ],
        },
        elevation: {
            levels: [
                {
                    level: 0,
                    shadow: "none",
                    description: "Flat — page background, inactive chips",
                },
                {
                    level: 1,
                    shadow: "0 1px 3px rgba(0,0,0,0.08)",
                    description: "Cards, session type tiles, stat cards",
                },
                {
                    level: 2,
                    shadow: "0 4px 12px rgba(0,0,0,0.10)",
                    description: "Dropdowns, popovers, selected cards elevated",
                },
                {
                    level: 3,
                    shadow: "0 8px 24px rgba(0,0,0,0.12)",
                    description: "Modals, settings dialog, overlay surfaces",
                },
            ],
        },
        borders: {
            radius: {
                small: 8,
                medium: 12,
                large: 16,
                pill: 9999,
            },
        },
        spacing: {
            unit: 8,
            scale: [
                4,
                8,
                12,
                16,
                24,
                32,
                48,
                64,
            ],
        },
    },
    catalogMap: {
        "input-text": {
            type: "input",
            variant: "text",
            height: 48,
            radius: 12,
            border_color: "border-default",
            border_width: 1,
            text_typography: "body",
            text_color: "text-primary",
            background: "surface-input",
            min_height: 44,
            required_fields: [
                "label",
                "placeholder",
            ],
            library: {
                shadcn: {
                    component: "Input",
                    import: "@/components/ui/input",
                },
            },
        },
        "input-currency": {
            type: "input",
            variant: "currency",
            height: 48,
            radius: 12,
            border_color: "border-default",
            border_width: 1,
            text_typography: "body",
            text_color: "text-primary",
            background: "surface-input",
            min_height: 44,
            required_fields: [
                "label",
                "placeholder",
            ],
            library: {
                shadcn: {
                    component: "Input",
                    import: "@/components/ui/input",
                },
            },
            extends: "input-text",
            prefix: "$",
        },
        "button-primary": {
            type: "button",
            variant: "primary",
            height: 48,
            radius: 12,
            background: "cta-primary",
            text_color: "text-on-cta",
            text_typography: "body",
            text_weight: 600,
            width: "fill",
            shadow: "none",
            required_fields: [
                "label",
            ],
            library: {
                shadcn: {
                    component: "Button",
                    import: "@/components/ui/button",
                    props: {
                        variant: "default",
                    },
                },
            },
        },
        "button-secondary": {
            type: "button",
            variant: "secondary",
            height: 44,
            radius: 12,
            background: "surface-primary",
            text_color: "text-primary",
            text_typography: "body",
            text_weight: 500,
            border_color: "border-default",
            border_width: 1,
            shadow: "none",
            required_fields: [
                "label",
            ],
            library: {
                shadcn: {
                    component: "Button",
                    import: "@/components/ui/button",
                    props: {
                        variant: "outline",
                    },
                },
            },
        },
        "button-ghost": {
            type: "button",
            variant: "ghost",
            height: 44,
            radius: 0,
            background: "transparent",
            text_color: "cta-primary",
            text_typography: "body",
            text_weight: 500,
            shadow: "none",
            required_fields: [
                "label",
            ],
            library: {
                shadcn: {
                    component: "Button",
                    import: "@/components/ui/button",
                    props: {
                        variant: "ghost",
                    },
                },
            },
        },
        "segmented-control": {
            type: "segmented-control",
            height: 48,
            radius: 24,
            inner_radius: 20,
            padding: 4,
            container_background: "surface-elevated",
            container_border_color: "border-default",
            container_border_opacity: 0.5,
            selected_bg: "cta-primary",
            selected_text: "text-on-cta",
            selected_weight: 600,
            unselected_bg: "transparent",
            unselected_text: "text-primary",
            unselected_weight: 400,
            text_size: 14,
            required_fields: [
                "options",
            ],
            library: {
                shadcn: {
                    component: "Tabs",
                    import: "@/components/ui/tabs",
                },
            },
        },
        stepper: {
            type: "stepper",
            height: 56,
            radius: 12,
            background: "surface-elevated",
            shadow: "sm",
            button_size: 40,
            minus_bg: "surface-secondary",
            minus_border: "border-default",
            minus_border_opacity: 0.5,
            minus_text_color: "text-secondary",
            plus_bg: "cta-primary",
            plus_text_color: "text-on-cta",
            count_typography: "heading-2",
            count_color: "text-primary",
            required_fields: [
                "label",
                "value",
            ],
            library: {
                shadcn: {
                    component: "div",
                    note: "Custom composition",
                },
            },
        },
        "display-readonly": {
            type: "display",
            text_typography: "heading-3",
            text_color: "text-secondary",
            background: "surface-elevated",
            height: 48,
            radius: 8,
            padding_x: 16,
            required_fields: [
                "label",
                "value",
            ],
            library: {
                shadcn: {
                    component: "div",
                    note: "Display-only",
                },
            },
        },
        card: {
            type: "card",
            background: "surface-primary",
            text_color: "text-primary",
            shadow: "shadow-sm",
            radius: 12,
            padding_x: 20,
            padding_y: 16,
            text_typography: "heading-3",
            gap: 12,
            library: {
                shadcn: {
                    component: "Card",
                    import: "@/components/ui/card",
                    slot_mapping: {
                        header: "CardHeader",
                        body: "CardContent",
                        footer: "CardFooter",
                    },
                },
            },
        },
        badge: {
            type: "badge",
            background: "surface-secondary",
            text_color: "text-secondary",
            padding_x: 8,
            padding_y: 2,
            text_typography: "small",
            gap: 4,
            library: {
                shadcn: {
                    component: "Badge",
                    import: "@/components/ui/badge",
                    variant_prop: "variant",
                    size_prop: "size",
                },
            },
        },
        stat: {
            type: "stat",
            background: "surface-primary",
            text_color: "text-primary",
            text_typography: "label",
            gap: 4,
            library: {
                shadcn: {
                    component: "Card",
                    import: "@/components/ui/card",
                },
            },
        },
        avatar: {
            type: "avatar",
            background: "surface-secondary",
            text_color: "text-primary",
            gap: 0,
            library: {
                shadcn: {
                    component: "Avatar",
                    import: "@/components/ui/avatar",
                    slot_mapping: {
                        image: "AvatarImage",
                        fallback: "AvatarFallback",
                    },
                    size_prop: "size",
                },
            },
        },
        tooltip: {
            type: "tooltip",
            height: 40,
            radius: 8,
            shadow: "sm",
            padding_x: 16,
            icon_size: 16,
            text_size: 11,
            text_color: "text-primary",
            required_fields: [
                "content",
            ],
            library: {
                shadcn: {
                    component: "Alert",
                    import: "@/components/ui/alert",
                },
            },
        },
        checkbox: {
            type: "checkbox",
            background: "surface-primary",
            text_color: "text-primary",
            border_color: "border-default",
            radius: 12,
            text_typography: "body",
            gap: 8,
            min_height: 44,
            library: {
                shadcn: {
                    component: "Checkbox",
                    import: "@/components/ui/checkbox",
                },
            },
        },
        select: {
            type: "select",
            background: "surface-primary",
            text_color: "text-primary",
            border_color: "border-default",
            radius: 12,
            padding_x: 12,
            padding_y: 8,
            text_typography: "label",
            gap: 4,
            min_height: 44,
            library: {
                shadcn: {
                    component: "Select",
                    import: "@/components/ui/select",
                    slot_mapping: {
                        trigger: "SelectTrigger",
                        options_list: "SelectContent",
                    },
                    variant_prop: "variant",
                },
            },
        },
        chip: {
            type: "chip",
            background: "surface-secondary",
            text_color: "text-primary",
            border_color: "border-default",
            radius: 12,
            padding_x: 12,
            padding_y: 4,
            text_typography: "label",
            gap: 4,
            min_height: 44,
            library: {
                shadcn: {
                    component: "Badge",
                    import: "@/components/ui/badge",
                },
            },
        },
        alert: {
            type: "alert",
            background: "cta-primary",
            text_color: "text-primary",
            border_color: "cta-primary",
            opacity: 0.1,
            radius: 12,
            padding_x: 16,
            padding_y: 12,
            text_typography: "label",
            gap: 8,
            library: {
                shadcn: {
                    component: "Alert",
                    import: "@/components/ui/alert",
                    slot_mapping: {
                        title: "AlertTitle",
                        message: "AlertDescription",
                    },
                },
            },
        },
        skeleton: {
            type: "skeleton",
            background: "surface-secondary",
            text_color: "transparent",
            opacity: 0.6,
            gap: 0,
            library: {
                shadcn: {
                    component: "Skeleton",
                    import: "@/components/ui/skeleton",
                },
            },
        },
        "loading-spinner": {
            type: "loading-spinner",
            background: "transparent",
            text_color: "text-secondary",
            gap: 8,
            library: {
                shadcn: {
                    component: "Loader2",
                    import: "lucide-react",
                },
            },
        },
        link: {
            type: "link",
            background: "transparent",
            text_color: "cta-primary",
            text_typography: "body",
            gap: 4,
            min_height: 44,
            library: {
                shadcn: {
                    component: "a",
                    import: "html",
                },
            },
        },
        switch: {
            type: "switch",
            background: "surface-secondary",
            text_color: "text-primary",
            border_color: "border-default",
            radius: 12,
            text_typography: "body",
            gap: 8,
            min_height: 44,
            library: {
                shadcn: {
                    component: "Switch",
                    import: "@/components/ui/switch",
                },
            },
        },
        "data-table": {
            type: "data-table",
            background: "surface-primary",
            text_color: "text-primary",
            border_color: "border-default",
            radius: 12,
            gap: 0,
            library: {
                shadcn: {
                    component: "Table",
                    import: "@/components/ui/table",
                    slot_mapping: {
                        header_row: "TableHeader",
                        body_rows: "TableBody",
                        pagination: "Pagination",
                    },
                },
            },
        },
        section: {
            type: "section",
            background: "surface-primary",
            text_color: "text-primary",
            text_typography: "heading-2",
            gap: 16,
            library: {
                shadcn: {
                    component: "section",
                    import: "html",
                },
            },
        },
        "navigation-bar": {
            type: "navigation-bar",
            background: "surface-primary",
            text_color: "text-primary",
            shadow: "shadow-sm",
            radius: 12,
            padding_x: 24,
            padding_y: 0,
            gap: 16,
            library: {
                shadcn: {
                    component: "nav",
                    import: "html",
                },
            },
        },
        sidebar: {
            type: "sidebar",
            background: "surface-secondary",
            text_color: "text-primary",
            gap: 8,
            library: {
                shadcn: {
                    component: "Sidebar",
                    import: "@/components/ui/sidebar",
                },
            },
        },
        "page-header": {
            type: "page-header",
            background: "surface-primary",
            text_color: "text-primary",
            gap: 8,
            library: {
                shadcn: {
                    component: "div",
                    import: "html",
                },
            },
        },
        footer: {
            type: "footer",
            background: "surface-secondary",
            text_color: "text-secondary",
            padding_x: 24,
            padding_y: 32,
            gap: 24,
            library: {
                shadcn: {
                    component: "footer",
                    import: "html",
                },
            },
        },
        "empty-state": {
            type: "empty-state",
            background: "surface-primary",
            text_color: "text-secondary",
            text_typography: "heading-3",
            gap: 12,
            library: {
                shadcn: {
                    component: "div",
                    import: "html",
                },
            },
        },
        button: {
            type: "button",
            background: "cta-primary",
            text_color: "text-on-cta",
            border_color: "cta-primary",
            shadow: "shadow-sm",
            radius: 12,
            padding_x: 16,
            padding_y: 8,
            text_typography: "label",
            gap: 8,
            min_height: 44,
            library: {
                shadcn: {
                    component: "Button",
                    import: "@/components/ui/button",
                    variant_prop: "variant",
                    size_prop: "size",
                },
            },
        },
        input: {
            type: "input",
            background: "surface-primary",
            text_color: "text-primary",
            border_color: "border-default",
            border_width: 1,
            radius: 12,
            padding_x: 12,
            padding_y: 8,
            text_typography: "label",
            gap: 4,
            min_height: 44,
            library: {
                shadcn: {
                    component: "Input",
                    import: "@/components/ui/input",
                    variant_prop: "variant",
                },
            },
        },
        radio: {
            type: "radio",
            background: "surface-primary",
            text_color: "text-primary",
            border_color: "border-default",
            radius: 12,
            text_typography: "body",
            gap: 8,
            min_height: 44,
            library: {
                shadcn: {
                    component: "RadioGroup",
                    import: "@/components/ui/radio-group",
                },
            },
        },
        "text-area": {
            type: "text-area",
            background: "surface-primary",
            text_color: "text-primary",
            border_color: "border-default",
            radius: 12,
            padding_x: 12,
            padding_y: 8,
            text_typography: "label",
            gap: 4,
            min_height: 44,
            library: {
                shadcn: {
                    component: "Textarea",
                    import: "@/components/ui/textarea",
                },
            },
        },
        "date-picker": {
            type: "date-picker",
            background: "surface-primary",
            text_color: "text-primary",
            border_color: "border-default",
            radius: 12,
            padding_x: 12,
            padding_y: 8,
            text_typography: "label",
            gap: 4,
            min_height: 44,
            library: {
                shadcn: {
                    component: "DatePicker",
                    import: "@/components/ui/date-picker",
                },
            },
        },
        "search-input": {
            type: "search-input",
            background: "surface-secondary",
            text_color: "text-primary",
            border_color: "border-default",
            radius: 12,
            padding_x: 12,
            padding_y: 8,
            gap: 8,
            min_height: 44,
            library: {
                shadcn: {
                    component: "Input",
                    import: "@/components/ui/input",
                },
            },
        },
        modal: {
            type: "modal",
            background: "surface-primary",
            text_color: "text-primary",
            shadow: "shadow-lg",
            text_typography: "heading-2",
            gap: 16,
            library: {
                shadcn: {
                    component: "Dialog",
                    import: "@/components/ui/dialog",
                    slot_mapping: {
                        header: "DialogHeader",
                        body: "DialogContent",
                        footer: "DialogFooter",
                    },
                },
            },
        },
        "progress-bar": {
            type: "progress-bar",
            background: "surface-secondary",
            text_color: "text-secondary",
            text_typography: "small",
            gap: 4,
            library: {
                shadcn: {
                    component: "Progress",
                    import: "@/components/ui/progress",
                },
            },
        },
        tabs: {
            type: "tabs",
            background: "surface-primary",
            text_color: "text-secondary",
            border_color: "border-default",
            radius: 12,
            padding_x: 16,
            padding_y: 8,
            gap: 0,
            min_height: 44,
            library: {
                shadcn: {
                    component: "Tabs",
                    import: "@/components/ui/tabs",
                    slot_mapping: {
                        tab_list: "TabsList",
                        tab_panels: "TabsContent",
                    },
                    variant_prop: "variant",
                },
            },
        },
        "step-indicator": {
            type: "step-indicator",
            background: "surface-primary",
            text_color: "text-secondary",
            border_color: "border-default",
            radius: 12,
            gap: 16,
            min_height: 44,
            library: {
                shadcn: {
                    component: "div",
                    import: "html",
                },
            },
        },
        breadcrumb: {
            type: "breadcrumb",
            background: "transparent",
            text_color: "text-secondary",
            text_typography: "label",
            gap: 4,
            min_height: 44,
            library: {
                shadcn: {
                    component: "Breadcrumb",
                    import: "@/components/ui/breadcrumb",
                    slot_mapping: {
                        items: "BreadcrumbList",
                        current: "BreadcrumbPage",
                    },
                },
            },
        },
        pagination: {
            type: "pagination",
            background: "surface-primary",
            text_color: "text-primary",
            border_color: "border-default",
            radius: 12,
            gap: 4,
            min_height: 44,
            library: {
                shadcn: {
                    component: "Pagination",
                    import: "@/components/ui/pagination",
                },
            },
        },
        form: {
            type: "form",
            background: "surface-primary",
            text_color: "text-primary",
            gap: 16,
            library: {
                shadcn: {
                    component: "form",
                    import: "html",
                },
            },
        },
        "selection-grid": {
            type: "selection-grid",
            background: "surface-primary",
            text_color: "text-primary",
            border_color: "border-default",
            radius: 12,
            gap: 16,
            library: {
                shadcn: {
                    component: "div",
                    import: "html",
                },
            },
        },
        "filter-bar": {
            type: "filter-bar",
            background: "surface-primary",
            text_color: "text-primary",
            padding_x: 16,
            padding_y: 12,
            gap: 12,
            library: {
                shadcn: {
                    component: "div",
                    import: "html",
                },
            },
        },
    },
    pageContext: {
        targetPage: {
            id: "session-picker",
            name: "Session Picker",
            description: "Entry screen where users select a session type (Deep Work, Meditation, Power Nap), configure duration via preset chips or custom input, toggle break reminders and ambient sound, and initiate the session. Displays a greeting header with time-of-day awareness, a stat strip showing streak, weekly hours, and total sessions, and a disabled Start button until a session type is selected.",
            route: "/",
            status: "approved",
            components: [
                "TopBar",
                "GreetingHeader",
                "StatStrip",
                "SessionTypeCard",
                "DurationChipRow",
                "CustomDurationInput",
                "BreakReminderToggle",
                "AmbientSoundToggle",
                "StartSessionButton",
                "SettingsDialog",
            ],
            data_sources: [
                "SessionType",
                "UserStats",
                "UserSettings",
            ],
            viewports: [
                1440,
            ],
        },
        allPages: [
            {
                id: "session-picker",
                name: "Session Picker",
                description: "Entry screen where users select a session type (Deep Work, Meditation, Power Nap), configure duration via preset chips or custom input, toggle break reminders and ambient sound, and initiate the session. Displays a greeting header with time-of-day awareness, a stat strip showing streak, weekly hours, and total sessions, and a disabled Start button until a session type is selected.",
                route: "/",
                status: "approved",
                components: [
                    "TopBar",
                    "GreetingHeader",
                    "StatStrip",
                    "SessionTypeCard",
                    "DurationChipRow",
                    "CustomDurationInput",
                    "BreakReminderToggle",
                    "AmbientSoundToggle",
                    "StartSessionButton",
                    "SettingsDialog",
                ],
                data_sources: [
                    "SessionType",
                    "UserStats",
                    "UserSettings",
                ],
                viewports: [
                    1440,
                ],
            },
            {
                id: "active-timer",
                name: "Active Timer",
                description: "Immersive timer screen showing a large circular progress ring with live countdown, play/pause/reset/stop controls, elapsed and remaining time strip, a meditation phase indicator (Meditation sessions only), a break reminder banner (Deep Work only), and a stop confirmation popover. The mute icon in the top bar toggles ambient sound. Timer state is preserved on window blur.",
                route: "/session/active",
                status: "approved",
                components: [
                    "TopBar",
                    "TimerRing",
                    "TimerDisplay",
                    "MeditationPhaseBar",
                    "PlayPauseButton",
                    "ResetButton",
                    "StopButton",
                    "StopConfirmationPopover",
                    "ProgressInfoStrip",
                    "BreakReminderBanner",
                    "MuteToggleIcon",
                    "AwayPauseBanner",
                ],
                data_sources: [
                    "ActiveSession",
                    "SessionType",
                    "UserSettings",
                ],
                viewports: [
                    1440,
                ],
            },
            {
                id: "session-summary",
                name: "Session Summary",
                description: "Post-session screen celebrating completion or early end. Shows a contextual icon and heading, a 2x2 stats card (duration, focus score, distractions, streak), an inline note input with character counter and save toast, primary and secondary navigation buttons, and a recent sessions history list with the just-completed session highlighted.",
                route: "/session/summary",
                status: "approved",
                components: [
                    "TopBar",
                    "CompletionHeader",
                    "SessionStatsCard",
                    "SessionNoteInput",
                    "StartAnotherButton",
                    "DoneButton",
                    "RecentSessionsList",
                    "SavedToast",
                    "StreakBadge",
                ],
                data_sources: [
                    "CompletedSession",
                    "SessionHistory",
                    "UserStats",
                ],
                viewports: [
                    1440,
                ],
            },
        ],
        models: [
            {
                id: "session-type",
                name: "SessionType",
                fields: [
                    {
                        name: "id",
                        type: "string",
                    },
                    {
                        name: "name",
                        type: "string",
                    },
                    {
                        name: "description",
                        type: "string",
                    },
                    {
                        name: "default_duration_minutes",
                        type: "integer",
                    },
                    {
                        name: "icon",
                        type: "string",
                    },
                    {
                        name: "color_token",
                        type: "string",
                    },
                    {
                        name: "created_at",
                        type: "datetime",
                    },
                ],
                db_table: "session_types",
            },
            {
                id: "user-stats",
                name: "UserStats",
                fields: [
                    {
                        name: "id",
                        type: "string",
                    },
                    {
                        name: "user_id",
                        type: "string",
                    },
                    {
                        name: "current_streak_days",
                        type: "integer",
                    },
                    {
                        name: "total_sessions",
                        type: "integer",
                    },
                    {
                        name: "weekly_hours",
                        type: "float",
                    },
                    {
                        name: "total_hours",
                        type: "float",
                    },
                    {
                        name: "last_session_date",
                        type: "datetime",
                    },
                    {
                        name: "created_at",
                        type: "datetime",
                    },
                    {
                        name: "updated_at",
                        type: "datetime",
                    },
                ],
                db_table: "user_stats",
            },
            {
                id: "user-settings",
                name: "UserSettings",
                fields: [
                    {
                        name: "id",
                        type: "string",
                    },
                    {
                        name: "user_id",
                        type: "string",
                    },
                    {
                        name: "notifications_enabled",
                        type: "boolean",
                    },
                    {
                        name: "ambient_sound",
                        type: "string",
                    },
                    {
                        name: "dark_mode_enabled",
                        type: "boolean",
                    },
                    {
                        name: "default_break_reminder",
                        type: "boolean",
                    },
                    {
                        name: "default_ambient_sound_enabled",
                        type: "boolean",
                    },
                    {
                        name: "created_at",
                        type: "datetime",
                    },
                    {
                        name: "updated_at",
                        type: "datetime",
                    },
                ],
                db_table: "user_settings",
            },
        ],
        apiEndpoints: [
            {
                id: "get-session-types",
                method: "GET",
                path: "/api/session-types",
                description: "Returns all available session types with their metadata, default durations, icons, and color tokens for rendering the session picker cards.",
                query_params: [
                ],
                response: {
                    type: "array",
                    schema_ref: "SessionType",
                },
                auth: "none",
                status: "planned",
            },
            {
                id: "get-user-stats",
                method: "GET",
                path: "/api/user/stats",
                description: "Returns the current user's aggregate stats including streak, weekly hours, and total session count for display in the session picker stat strip and session summary.",
                query_params: [
                ],
                response: {
                    type: "object",
                    schema_ref: "UserStats",
                },
                auth: "none",
                status: "planned",
            },
            {
                id: "get-user-settings",
                method: "GET",
                path: "/api/user/settings",
                description: "Returns the user's persisted settings including ambient sound preference, notification toggle, and dark mode preference for the settings dialog and session picker toggles.",
                query_params: [
                ],
                response: {
                    type: "object",
                    schema_ref: "UserSettings",
                },
                auth: "none",
                status: "planned",
            },
            {
                id: "update-user-settings",
                method: "PATCH",
                path: "/api/user/settings",
                description: "Updates one or more user settings fields. Used when the user changes ambient sound, toggles notifications, or adjusts dark mode in the settings dialog.",
                query_params: [
                ],
                response: {
                    type: "object",
                    schema_ref: "UserSettings",
                },
                auth: "none",
                status: "planned",
            },
        ],
    },
};
export default mockPenpotInput;