const mockPlanningOutput = {
    ok: true,
    value: {
        specRef: "spec-session-picker-1743465600000",
        moduleId: "session-picker",
        componentTree: [
            {
                name: "SessionPickerLayout",
                props: [
                    "maxWidth",
                    "paddingY",
                    "gap",
                    "background",
                ],
                children: [
                    "TopBar",
                    "GreetingHeader",
                    "StatStrip",
                    "SessionConfigCard",
                    "StartSessionButton",
                    "SettingsDialog",
                ],
            },
            {
                name: "TopBar",
                props: [
                    "height",
                    "background",
                    "showBackArrow",
                    "settingsIcon",
                    "settingsIconSize",
                    "ariaLabel",
                    "ariaHasPopup",
                ],
                children: [
                ],
            },
            {
                name: "GreetingHeader",
                props: [
                    "greeting",
                    "subtitle",
                    "timeOfDay",
                    "typography",
                    "subtitleTypography",
                ],
                children: [
                ],
            },
            {
                name: "StatStrip",
                props: [
                    "streakDays",
                    "weeklyHours",
                    "totalSessions",
                    "dividerColor",
                    "streakColor",
                    "ariaHidden",
                ],
                children: [
                ],
            },
            {
                name: "SessionConfigCard",
                props: [
                    "borderRadius",
                    "shadow",
                    "padding",
                    "gap",
                    "background",
                ],
                children: [
                    "SessionTypeCardGroup",
                    "DurationSection",
                    "ToggleSection",
                ],
            },
            {
                name: "SessionTypeCardGroup",
                props: [
                    "role",
                    "ariaLabel",
                    "gap",
                    "selectedId",
                ],
                children: [
                    "SessionTypeCard",
                ],
            },
            {
                name: "SessionTypeCard",
                props: [
                    "sessionTypeId",
                    "name",
                    "description",
                    "icon",
                    "colorToken",
                    "defaultDuration",
                    "isSelected",
                    "role",
                    "ariaChecked",
                    "borderRadius",
                    "shadow",
                    "selectedShadow",
                    "paddingX",
                    "paddingY",
                    "minHeight",
                    "minWidth",
                    "transitionDuration",
                ],
                children: [
                    "Avatar",
                ],
            },
            {
                name: "Avatar",
                props: [
                    "size",
                    "background",
                    "iconColor",
                    "ariaHidden",
                ],
                children: [
                ],
            },
            {
                name: "DurationSection",
                props: [
                    "label",
                    "gap",
                    "typography",
                ],
                children: [
                    "DurationChipRow",
                    "CustomDurationInput",
                ],
            },
            {
                name: "DurationChipRow",
                props: [
                    "role",
                    "ariaLabel",
                    "gap",
                    "chips",
                    "selectedValue",
                    "chipWidth",
                    "chipHeight",
                    "borderRadius",
                ],
                children: [
                    "Badge",
                ],
            },
            {
                name: "Badge",
                props: [
                    "role",
                    "ariaChecked",
                    "value",
                    "label",
                    "isSelected",
                    "variant",
                    "borderRadius",
                    "minWidth",
                    "minHeight",
                    "typography",
                ],
                children: [
                ],
            },
            {
                name: "CustomDurationInput",
                props: [
                    "isVisible",
                    "slideAnimationDuration",
                    "value",
                    "min",
                    "max",
                    "step",
                    "ariaLabel",
                    "ariaValueMin",
                    "ariaValueMax",
                    "ariaValueNow",
                    "borderRadius",
                    "background",
                    "paddingX",
                    "paddingY",
                ],
                children: [
                    "Input",
                    "Button",
                ],
            },
            {
                name: "Input",
                props: [
                    "type",
                    "ariaLabel",
                    "ariaValueMin",
                    "ariaValueMax",
                    "ariaValueNow",
                    "borderRadius",
                    "background",
                    "paddingX",
                    "paddingY",
                ],
                children: [
                ],
            },
            {
                name: "ToggleSection",
                props: [
                    "gap",
                    "conditionalBreakReminder",
                ],
                children: [
                    "BreakReminderToggle",
                    "AmbientSoundToggle",
                ],
            },
            {
                name: "BreakReminderToggle",
                props: [
                    "isVisible",
                    "isChecked",
                    "role",
                    "ariaChecked",
                    "ariaLabel",
                    "label",
                    "subLabel",
                    "minHeight",
                    "transitionDuration",
                ],
                children: [
                ],
            },
            {
                name: "AmbientSoundToggle",
                props: [
                    "isChecked",
                    "role",
                    "ariaChecked",
                    "ariaLabel",
                    "label",
                    "soundLabel",
                    "minHeight",
                ],
                children: [
                ],
            },
            {
                name: "StartSessionButton",
                props: [
                    "isDisabled",
                    "ariaDisabled",
                    "ariaLabel",
                    "label",
                    "height",
                    "borderRadius",
                    "typography",
                    "variant",
                    "transitionDuration",
                ],
                children: [
                    "Button",
                ],
            },
            {
                name: "SettingsDialog",
                props: [
                    "isOpen",
                    "role",
                    "ariaModal",
                    "ariaLabelledBy",
                    "maxWidth",
                    "borderRadius",
                    "shadow",
                    "zIndex",
                    "overlayColor",
                    "paddingX",
                    "paddingY",
                    "gap",
                ],
                children: [
                    "SoundSelectorChipGroup",
                    "NotificationsToggle",
                    "DarkModeToggle",
                ],
            },
        ],
        tokenBindings: {
            "SessionPickerLayout.background": "background-primary",
            "SessionPickerLayout.gap": "32",
            "SessionPickerLayout.paddingY": "48",
            "TopBar.background": "surface-primary",
            "TopBar.iconColor": "text-secondary",
            "GreetingHeader.color": "text-primary",
            "GreetingHeader.typography": "heading-1",
            "GreetingHeader.subtitleTypography": "body",
            "GreetingHeader.subtitleColor": "text-secondary",
            "StatStrip.streakColor": "warning",
            "StatStrip.textColor": "text-secondary",
            "StatStrip.typography": "body",
            "StatStrip.dividerColor": "border-default",
            "SessionConfigCard.background": "surface-primary",
            "SessionConfigCard.shadow": "elevation-1",
            "SessionConfigCard.borderRadius": "large",
            "SessionConfigCard.gap": "24",
            "SessionTypeCardGroup.gap": "12",
            "SessionTypeCard.background": "surface-primary",
            "SessionTypeCard.selectedBackground": "surface-elevated",
            "SessionTypeCard.shadow": "elevation-1",
            "SessionTypeCard.selectedShadow": "elevation-2",
            "SessionTypeCard.borderRadius": "large",
            "SessionTypeCard.titleTypography": "heading-2",
            "SessionTypeCard.titleColor": "text-primary",
            "SessionTypeCard.descriptionTypography": "body",
            "SessionTypeCard.descriptionColor": "text-secondary",
            "SessionTypeCard.selectedBorderColor": "cta-primary",
            "SessionTypeCard.selectedBackground2": "surface-elevated",
            "SessionTypeCard.transitionDuration": "duration-fast",
            "SessionTypeCard.minHeight": "touch-min-height",
            "Avatar.unselectedBackground": "surface-secondary",
            "Avatar.unselectedIconColor": "text-secondary",
            "Avatar.selectedBackground": "cta-primary",
            "Avatar.selectedIconColor": "text-on-cta",
            "DurationSection.labelTypography": "heading-3",
            "DurationSection.labelColor": "text-primary",
            "DurationSection.gap": "12",
            "DurationChipRow.gap": "8",
            "Badge.selectedBackground": "cta-primary",
            "Badge.selectedTextColor": "text-on-cta",
            "Badge.unselectedBackground": "surface-primary",
            "Badge.unselectedTextColor": "text-primary",
            "Badge.unselectedBorderColor": "border-default",
            "Badge.borderRadius": "pill",
            "Badge.typography": "label",
            "CustomDurationInput.background": "surface-input",
            "CustomDurationInput.borderColor": "border-default",
            "CustomDurationInput.focusBorderColor": "border-focus",
            "CustomDurationInput.borderRadius": "small",
            "CustomDurationInput.textColor": "text-primary",
            "CustomDurationInput.typography": "body",
            "CustomDurationInput.transitionDuration": "duration-fast",
            "ToggleSection.gap": "12",
            "BreakReminderToggle.labelTypography": "body",
            "BreakReminderToggle.labelColor": "text-primary",
            "BreakReminderToggle.subLabelTypography": "label",
            "BreakReminderToggle.subLabelColor": "text-secondary",
            "BreakReminderToggle.activeColor": "cta-primary",
            "BreakReminderToggle.transitionDuration": "duration-fast",
            "AmbientSoundToggle.labelTypography": "body",
            "AmbientSoundToggle.labelColor": "text-primary",
            "AmbientSoundToggle.activeColor": "cta-primary",
            "StartSessionButton.activeBackground": "cta-primary",
            "StartSessionButton.activeTextColor": "text-on-cta",
            "StartSessionButton.disabledBackground": "border-default",
            "StartSessionButton.disabledTextColor": "text-disabled",
            "StartSessionButton.borderRadius": "medium",
            "StartSessionButton.typography": "heading-2",
            "StartSessionButton.transitionDuration": "duration-fast",
            "SettingsDialog.background": "surface-primary",
            "SettingsDialog.shadow": "elevation-3",
            "SettingsDialog.borderRadius": "large",
            "SettingsDialog.overlay": "overlay",
            "SettingsDialog.zIndex": "z-modal",
            "SettingsDialog.titleTypography": "heading-2",
            "SettingsDialog.titleColor": "text-primary",
            "SettingsDialog.gap": "24",
        },
        responsiveRules: [
            {
                breakpoint: "desktop",
                behavior: "Single centered column, max-width 560px expanding to 600px at 1440px+, all components stacked vertically with 32px section gap",
                width: 1440,
                layout: "single-column",
                changes: [
                    "TopBar 56px tall transparent, settings gear right-aligned",
                    "GreetingHeader two-line centered stack",
                    "StatStrip three metrics inline with dot dividers",
                    "SessionTypeCard group vertical stack with 12px gap",
                    "DurationChipRow horizontal chip row with 8px gap",
                    "CustomDurationInput slide-down reveal below chip row",
                    "BreakReminderToggle and AmbientSoundToggle in vertical flex stack",
                    "StartSessionButton full-width 56px height at bottom of column",
                    "SettingsDialog centered modal max-width 400px with scrim overlay",
                ],
            },
        ],
        screens: [
            {
                name: "Session Picker",
                components: [
                    "SessionPickerLayout",
                    "TopBar",
                    "GreetingHeader",
                    "StatStrip",
                    "SessionConfigCard",
                    "SessionTypeCardGroup",
                    "SessionTypeCard",
                    "Avatar",
                    "DurationSection",
                    "DurationChipRow",
                    "Badge",
                    "CustomDurationInput",
                    "Input",
                    "ToggleSection",
                    "BreakReminderToggle",
                    "AmbientSoundToggle",
                    "StartSessionButton",
                    "SettingsDialog",
                ],
            },
        ],
    },
};
export default mockPlanningOutput;