/**
 * @module @agentforge/cli/commands/design-generate
 *
 * The `agentforge design:generate` command.
 * Uses LLM to generate a complete app spec (pages, models, API) from
 * the project description and design tokens, then presents an HTML preview
 * for the user to review and approve before writing spec files.
 */

import * as readline from 'node:readline';
import * as os from 'node:os';
import * as path from 'node:path';
import * as fs from 'node:fs';
import type { DesignTokensSpec, BrandSpec } from '@agentforge/core';
import { loadDesignTokens, loadBrandSpec, loadPRD } from '@agentforge/core';
import { createClaudeProvider } from '@agentforge/providers';
import type { LLMProvider } from '@agentforge/providers';
import { infoMsg, warnMsg, errorMsg, successMsg } from '../formatter.js';
import type { FileSystem } from '../fs-utils.js';
import { readYaml, writeYaml, realFs, loadDotEnv } from '../fs-utils.js';
import { openInBrowser, generateDesignOptions } from './generate-design-options.js';
import type { GenerateDesignOptionsConfig } from './generate-design-options.js';
import { saveDesignTokens, saveBrandSpec } from '@agentforge/core';
import { generateTailwindConfig, generateGlobalCss } from './init.js';

// ============================================================================
// Types
// ============================================================================

/** A page definition generated by the LLM. */
export interface GeneratedPage {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly route: string;
  readonly components: readonly string[];
  readonly data_sources: readonly string[];
}

/** A model definition generated by the LLM. */
export interface GeneratedModel {
  readonly id: string;
  readonly name: string;
  readonly fields: readonly {
    readonly name: string;
    readonly type: string;
    readonly nullable?: boolean;
  }[];
  readonly db_table: string;
}

/** An API endpoint generated by the LLM. */
export interface GeneratedEndpoint {
  readonly id: string;
  readonly method: string;
  readonly path: string;
  readonly description: string;
  readonly query_params: readonly { readonly name: string; readonly type: string }[];
  readonly response: { readonly type: string; readonly schema_ref: string };
  readonly auth: string;
}

/** Complete app spec generated by the LLM. */
export interface GeneratedAppSpec {
  readonly pages: readonly GeneratedPage[];
  readonly models: readonly GeneratedModel[];
  readonly endpoints: readonly GeneratedEndpoint[];
}

/** Result of the design:generate flow. */
export interface DesignGenerateResult {
  readonly spec: GeneratedAppSpec;
  readonly source: 'llm' | 'fallback';
}

/** Options for customizing behavior (e.g. in tests). */
export interface DesignGenerateConfig {
  readonly openBrowser?: (url: string) => Promise<boolean>;
  readonly designOptionsConfig?: GenerateDesignOptionsConfig;
}

// ============================================================================
// LLM Prompt
// ============================================================================

/** Build the system prompt for app spec generation. */
function buildSystemPrompt(): string {
  return `You are a product architect and UX expert. Given an app description and its design system, generate a complete app specification with pages, data models, and API endpoints.

Respond with ONLY valid JSON (no markdown, no code fences) matching this exact schema:

{
  "pages": [
    {
      "id": "kebab-case-id",
      "name": "Human Readable Name",
      "description": "What this page does and its key interactions",
      "route": "/url-path",
      "components": ["ComponentName1", "ComponentName2"],
      "data_sources": ["ModelName1", "ModelName2"]
    }
  ],
  "models": [
    {
      "id": "kebab-case-id",
      "name": "PascalCaseName",
      "fields": [
        { "name": "id", "type": "string" },
        { "name": "title", "type": "string" },
        { "name": "created_at", "type": "datetime" }
      ],
      "db_table": "table_name"
    }
  ],
  "endpoints": [
    {
      "id": "kebab-case-id",
      "method": "GET",
      "path": "/api/resource",
      "description": "What this endpoint does",
      "query_params": [{ "name": "param", "type": "string" }],
      "response": { "type": "array", "schema_ref": "ModelName" },
      "auth": "none"
    }
  ]
}

Rules:
- Generate 3-6 pages that form a complete, coherent app
- Each page should have a clear purpose and list its key components
- Models should cover all data the pages need
- API endpoints should support all page data requirements
- Use RESTful conventions for endpoints
- Every model needs at minimum: id, created_at fields
- Pages should include: a landing/home page, main content pages, and detail views
- Think about the user journey — how do they flow between pages?
- Component names should be descriptive (e.g., "BookCard", "SearchBar", "NavigationHeader")
- Keep it practical — this is a real app that will be built`;
}

/** Build the user prompt with full app context. */
function buildUserPrompt(context: {
  readonly appName: string;
  readonly description: string;
  readonly tokens: DesignTokensSpec;
  readonly brand: BrandSpec;
  readonly prdContent?: string;
}): string {
  const colorNames = Object.keys(context.tokens.colors.primitive).join(', ');
  const fonts = `${context.tokens.typography.font_families.display} (headings) + ${context.tokens.typography.font_families.body} (body)`;

  const appContext = context.prdContent
    ? `App: ${context.appName}\n\nPRD:\n${context.prdContent}`
    : `App: ${context.appName}\nDescription: ${context.description || 'A web application'}`;

  return `Generate a complete app specification for:

${appContext}

Design system context:
- Brand tone: ${context.brand.identity.tone}
- Target audience: ${context.brand.identity.audience}
- Color palette: ${colorNames}
- Typography: ${fonts}
- WCAG level: ${context.brand.accessibility.wcag_level}

Generate all pages, data models, and API endpoints needed for this app.`;
}

// ============================================================================
// LLM Response Parsing
// ============================================================================

/** Parse and validate LLM response into GeneratedAppSpec. */
export function parseAppSpecResponse(raw: string): GeneratedAppSpec | null {
  try {
    const cleaned = raw.replace(/^```(?:json)?\s*/m, '').replace(/\s*```\s*$/m, '').trim();
    const parsed = JSON.parse(cleaned) as GeneratedAppSpec;

    if (!Array.isArray(parsed.pages) || parsed.pages.length === 0) return null;
    if (!Array.isArray(parsed.models) || parsed.models.length === 0) return null;
    if (!Array.isArray(parsed.endpoints) || parsed.endpoints.length === 0) return null;

    // Validate each page has required fields
    const validPages = parsed.pages.filter(
      (p) => p.id && p.name && p.description && p.route && Array.isArray(p.components),
    );
    if (validPages.length === 0) return null;

    // Validate each model has required fields
    const validModels = parsed.models.filter(
      (m) => m.id && m.name && Array.isArray(m.fields) && m.fields.length > 0 && m.db_table,
    );
    if (validModels.length === 0) return null;

    // Validate each endpoint has required fields
    const validEndpoints = parsed.endpoints.filter(
      (e) => e.id && e.method && e.path && e.response,
    );
    if (validEndpoints.length === 0) return null;

    return {
      pages: validPages,
      models: validModels,
      endpoints: validEndpoints,
    };
  } catch {
    return null;
  }
}

// ============================================================================
// HTML Preview Generation
// ============================================================================

/** Generate an HTML preview showing the complete app spec. */
export function generateAppSpecPreviewHtml(
  appName: string,
  spec: GeneratedAppSpec,
  tokens: DesignTokensSpec,
  brand: BrandSpec,
): string {
  const displayFont = tokens.typography.font_families.display;
  const bodyFont = tokens.typography.font_families.body;
  const fontImport = [displayFont, bodyFont]
    .filter((f, i, a) => a.indexOf(f) === i)
    .map((f) => f.replace(/\s+/g, '+'))
    .join('&family=');

  const bgHex = resolveColor(tokens.colors.semantic['background-primary'], tokens.colors.primitive);
  const textHex = resolveColor(tokens.colors.semantic['text-primary'], tokens.colors.primitive);
  const ctaHex = resolveColor(tokens.colors.semantic['cta-primary'], tokens.colors.primitive);
  const primitiveVals = Object.values(tokens.colors.primitive);
  const surfaceHex = primitiveVals[4] ?? primitiveVals[3] ?? '#f5f5f5';

  const pageCards = spec.pages.map((page, i) => `
        <div class="page-card" style="animation-delay: ${i * 0.1}s">
          <div class="page-header">
            <span class="page-number">${i + 1}</span>
            <div>
              <h3 class="page-name">${page.name}</h3>
              <code class="page-route">${page.route}</code>
            </div>
          </div>
          <p class="page-desc">${page.description}</p>
          <div class="page-section">
            <div class="section-label">Components</div>
            <div class="chip-list">
              ${page.components.map((c) => `<span class="chip component-chip">${c}</span>`).join('')}
            </div>
          </div>
          <div class="page-section">
            <div class="section-label">Data Sources</div>
            <div class="chip-list">
              ${page.data_sources.map((d) => `<span class="chip data-chip">${d}</span>`).join('')}
            </div>
          </div>
        </div>`).join('\n');

  const modelCards = spec.models.map((model) => `
        <div class="model-card">
          <h4 class="model-name">${model.name}</h4>
          <code class="model-table">${model.db_table}</code>
          <table class="field-table">
            <thead><tr><th>Field</th><th>Type</th></tr></thead>
            <tbody>
              ${model.fields.map((f) => `<tr><td>${f.name}</td><td><code>${f.type}</code>${f.nullable ? ' <span class="nullable">nullable</span>' : ''}</td></tr>`).join('')}
            </tbody>
          </table>
        </div>`).join('\n');

  const endpointRows = spec.endpoints.map((ep) => {
    const methodClass = ep.method.toLowerCase();
    return `
            <tr>
              <td><span class="method-badge ${methodClass}">${ep.method}</span></td>
              <td><code>${ep.path}</code></td>
              <td>${ep.description}</td>
              <td><code>${ep.response.schema_ref}</code></td>
            </tr>`;
  }).join('\n');

  // Build a flow diagram showing page connections
  const flowNodes = spec.pages.map((page, i) => {
    const x = 40 + (i % 3) * 280;
    const y = 40 + Math.floor(i / 3) * 120;
    return `<div class="flow-node" style="left:${x}px;top:${y}px">
              <div class="flow-node-name">${page.name}</div>
              <div class="flow-node-route">${page.route}</div>
            </div>`;
  }).join('\n');

  const flowHeight = (Math.ceil(spec.pages.length / 3)) * 120 + 80;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>App Spec Preview — ${appName}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=${fontImport}&display=swap" rel="stylesheet">
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: '${bodyFont}', -apple-system, sans-serif; background: #f4f5f7; color: #333; }

    .header {
      background: ${textHex};
      color: ${bgHex};
      padding: 48px 24px 40px;
      text-align: center;
    }
    .header h1 { font-family: '${displayFont}', sans-serif; font-size: 32px; font-weight: 700; margin-bottom: 8px; }
    .header p { font-size: 16px; opacity: 0.8; }
    .header .brand-badge {
      display: inline-block;
      margin-top: 12px;
      padding: 4px 16px;
      background: ${ctaHex};
      color: ${isLight(ctaHex) ? '#111' : '#fff'};
      border-radius: 9999px;
      font-size: 12px;
      font-weight: 500;
    }

    .tabs {
      display: flex;
      gap: 0;
      justify-content: center;
      background: #fff;
      border-bottom: 1px solid #e0e0e0;
      position: sticky;
      top: 0;
      z-index: 10;
    }
    .tab {
      padding: 14px 32px;
      border: none;
      background: transparent;
      font-size: 14px;
      font-weight: 500;
      color: #888;
      cursor: pointer;
      border-bottom: 2px solid transparent;
      transition: all .2s;
      font-family: '${bodyFont}', sans-serif;
    }
    .tab.active { color: ${ctaHex}; border-bottom-color: ${ctaHex}; }
    .tab:hover:not(.active) { color: #555; }

    .container { max-width: 1100px; margin: 0 auto; padding: 32px 24px; }
    .panel { display: none; }
    .panel.active { display: block; }

    /* Pages */
    .pages-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(340px, 1fr)); gap: 20px; }
    .page-card {
      background: #fff;
      border-radius: 12px;
      padding: 24px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.08);
      animation: fadeIn 0.3s ease-out both;
    }
    @keyframes fadeIn { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: none; } }
    .page-header { display: flex; gap: 12px; align-items: flex-start; margin-bottom: 12px; }
    .page-number {
      width: 32px; height: 32px; border-radius: 8px;
      background: ${ctaHex}; color: ${isLight(ctaHex) ? '#111' : '#fff'};
      display: flex; align-items: center; justify-content: center;
      font-weight: 700; font-size: 14px; flex-shrink: 0;
    }
    .page-name { font-family: '${displayFont}', sans-serif; font-size: 18px; font-weight: 600; color: ${textHex}; }
    .page-route { font-size: 12px; color: #888; background: #f5f5f5; padding: 2px 8px; border-radius: 4px; }
    .page-desc { font-size: 13px; color: #666; line-height: 1.5; margin-bottom: 16px; }
    .page-section { margin-top: 12px; }
    .section-label { font-size: 11px; font-weight: 600; text-transform: uppercase; color: #999; letter-spacing: 0.5px; margin-bottom: 6px; }
    .chip-list { display: flex; flex-wrap: wrap; gap: 6px; }
    .chip { padding: 4px 10px; border-radius: 6px; font-size: 11px; font-weight: 500; }
    .component-chip { background: #e0f2fe; color: #0369a1; }
    .data-chip { background: #fce7f3; color: #9d174d; }

    /* Models */
    .models-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 20px; }
    .model-card { background: #fff; border-radius: 12px; padding: 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
    .model-name { font-family: '${displayFont}', sans-serif; font-size: 18px; font-weight: 600; color: ${textHex}; margin-bottom: 4px; }
    .model-table { font-size: 12px; color: #888; background: #f5f5f5; padding: 2px 8px; border-radius: 4px; display: inline-block; margin-bottom: 16px; }
    .field-table { width: 100%; border-collapse: collapse; font-size: 13px; }
    .field-table th { text-align: left; padding: 8px 0; border-bottom: 1px solid #e0e0e0; color: #999; font-weight: 500; font-size: 11px; text-transform: uppercase; }
    .field-table td { padding: 6px 0; border-bottom: 1px solid #f5f5f5; }
    .field-table code { background: #f5f5f5; padding: 1px 6px; border-radius: 3px; font-size: 12px; }
    .nullable { font-size: 10px; color: #999; font-style: italic; }

    /* API */
    .api-table { width: 100%; border-collapse: collapse; background: #fff; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
    .api-table th { text-align: left; padding: 12px 16px; background: #fafafa; font-size: 11px; text-transform: uppercase; color: #999; font-weight: 600; border-bottom: 1px solid #e0e0e0; }
    .api-table td { padding: 12px 16px; border-bottom: 1px solid #f5f5f5; font-size: 13px; }
    .api-table code { background: #f5f5f5; padding: 1px 6px; border-radius: 3px; font-size: 12px; }
    .method-badge { padding: 3px 8px; border-radius: 4px; font-size: 11px; font-weight: 700; font-family: monospace; }
    .method-badge.get { background: #dcfce7; color: #166534; }
    .method-badge.post { background: #dbeafe; color: #1e40af; }
    .method-badge.put { background: #fef9c3; color: #854d0e; }
    .method-badge.patch { background: #fef9c3; color: #854d0e; }
    .method-badge.delete { background: #fecaca; color: #991b1b; }

    /* Flow */
    .flow-container { position: relative; background: #fff; border-radius: 12px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); min-height: ${flowHeight}px; }
    .flow-node {
      position: absolute;
      background: ${surfaceHex};
      border: 2px solid ${ctaHex};
      border-radius: 10px;
      padding: 12px 16px;
      min-width: 200px;
      text-align: center;
    }
    .flow-node-name { font-family: '${displayFont}', sans-serif; font-size: 14px; font-weight: 600; color: ${textHex}; }
    .flow-node-route { font-size: 11px; color: #888; margin-top: 2px; }

    /* Summary */
    .summary-strip {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 16px;
      margin-bottom: 32px;
    }
    .summary-card {
      background: #fff;
      border-radius: 12px;
      padding: 20px;
      text-align: center;
      box-shadow: 0 1px 3px rgba(0,0,0,0.08);
    }
    .summary-number { font-family: '${displayFont}', sans-serif; font-size: 32px; font-weight: 700; color: ${ctaHex}; }
    .summary-label { font-size: 12px; color: #888; margin-top: 4px; }

    .footer { text-align: center; padding: 40px 24px; color: #888; font-size: 14px; }
    .footer strong { color: #333; }
    .footer kbd { background: #e0e0e0; padding: 2px 8px; border-radius: 4px; font-family: monospace; font-size: 13px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${appName}</h1>
    <p>Generated App Specification</p>
    <span class="brand-badge">${brand.identity.tone} · ${brand.identity.audience}</span>
  </div>

  <div class="tabs">
    <button class="tab active" onclick="switchTab('overview')" data-tab="overview">Overview</button>
    <button class="tab" onclick="switchTab('pages')" data-tab="pages">Pages (${spec.pages.length})</button>
    <button class="tab" onclick="switchTab('models')" data-tab="models">Models (${spec.models.length})</button>
    <button class="tab" onclick="switchTab('api')" data-tab="api">API (${spec.endpoints.length})</button>
    <button class="tab" onclick="switchTab('flow')" data-tab="flow">User Flow</button>
  </div>

  <div class="container">
    <!-- Overview -->
    <div class="panel active" id="panel-overview">
      <div class="summary-strip">
        <div class="summary-card">
          <div class="summary-number">${spec.pages.length}</div>
          <div class="summary-label">Pages</div>
        </div>
        <div class="summary-card">
          <div class="summary-number">${spec.models.length}</div>
          <div class="summary-label">Data Models</div>
        </div>
        <div class="summary-card">
          <div class="summary-number">${spec.endpoints.length}</div>
          <div class="summary-label">API Endpoints</div>
        </div>
        <div class="summary-card">
          <div class="summary-number">${new Set(spec.pages.flatMap((p) => p.components)).size}</div>
          <div class="summary-label">Components</div>
        </div>
      </div>
      <div class="pages-grid">
        ${pageCards}
      </div>
    </div>

    <!-- Pages -->
    <div class="panel" id="panel-pages">
      <div class="pages-grid">
        ${pageCards}
      </div>
    </div>

    <!-- Models -->
    <div class="panel" id="panel-models">
      <div class="models-grid">
        ${modelCards}
      </div>
    </div>

    <!-- API -->
    <div class="panel" id="panel-api">
      <table class="api-table">
        <thead>
          <tr>
            <th>Method</th>
            <th>Path</th>
            <th>Description</th>
            <th>Response</th>
          </tr>
        </thead>
        <tbody>
          ${endpointRows}
        </tbody>
      </table>
    </div>

    <!-- Flow -->
    <div class="panel" id="panel-flow">
      <div class="flow-container">
        ${flowNodes}
      </div>
    </div>
  </div>

  <div class="footer">
    Return to your terminal — type <kbd>y</kbd> to approve, <kbd>r</kbd> to regenerate, or <kbd>n</kbd> to cancel.
  </div>

  <script>
    function switchTab(name) {
      document.querySelectorAll('.tab').forEach(t => t.classList.toggle('active', t.dataset.tab === name));
      document.querySelectorAll('.panel').forEach(p => p.classList.toggle('active', p.id === 'panel-' + name));
    }
  </script>
</body>
</html>`;
}

/** Check if a hex color is light. */
function isLight(hex: string): boolean {
  const c = hex.replace('#', '');
  const r = parseInt(c.substring(0, 2), 16);
  const g = parseInt(c.substring(2, 4), 16);
  const b = parseInt(c.substring(4, 6), 16);
  return (r * 299 + g * 587 + b * 114) / 1000 > 128;
}

/** Resolve a semantic color to its hex value. */
function resolveColor(semantic: string, primitive: Readonly<Record<string, string>>): string {
  if (semantic.startsWith('#')) return semantic;
  return primitive[semantic] ?? '#888888';
}

// ============================================================================
// CLI Summary (fallback when browser can't open)
// ============================================================================

/** Print a CLI summary when browser can't open. */
function printCliSummary(
  spec: GeneratedAppSpec,
  output: NodeJS.WritableStream,
): void {
  output.write(infoMsg('\n=== Generated App Spec ===\n'));

  output.write(infoMsg('\nPages:\n'));
  for (const page of spec.pages) {
    output.write(infoMsg(`  ${page.name} (${page.route})\n`));
    output.write(infoMsg(`    ${page.description}\n`));
    output.write(infoMsg(`    Components: ${page.components.join(', ')}\n`));
  }

  output.write(infoMsg('\nModels:\n'));
  for (const model of spec.models) {
    output.write(infoMsg(`  ${model.name} (${model.db_table})\n`));
    output.write(infoMsg(`    Fields: ${model.fields.map((f) => `${f.name}:${f.type}`).join(', ')}\n`));
  }

  output.write(infoMsg('\nAPI Endpoints:\n'));
  for (const ep of spec.endpoints) {
    output.write(infoMsg(`  ${ep.method} ${ep.path} — ${ep.description}\n`));
  }
}

// ============================================================================
// Prompt Helper
// ============================================================================

/** Prompt for a single line using a short-lived readline. */
function promptOnce(
  input: NodeJS.ReadableStream,
  output: NodeJS.WritableStream,
  question: string,
): Promise<string> {
  const rl = readline.createInterface({ input, output, terminal: false });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim().toLowerCase());
    });
  });
}

// ============================================================================
// LLM Generation
// ============================================================================

/** Attempt LLM generation of the app spec. */
async function tryLLMGeneration(
  apiKey: string,
  context: {
    readonly appName: string;
    readonly description: string;
    readonly tokens: DesignTokensSpec;
    readonly brand: BrandSpec;
    readonly prdContent?: string;
  },
  output: NodeJS.WritableStream,
): Promise<GeneratedAppSpec | null> {
  let provider: LLMProvider;
  try {
    provider = createClaudeProvider('claude-sonnet-4', { apiKey });
  } catch {
    output.write(warnMsg('Failed to create LLM provider.\n'));
    return null;
  }

  const systemPrompt = buildSystemPrompt();
  const userPrompt = buildUserPrompt(context);

  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const result = await provider.complete(
        {
          system: systemPrompt,
          messages: [
            { role: 'user', content: userPrompt },
            ...(attempt > 0
              ? [{ role: 'user' as const, content: 'Your previous response was not valid JSON. Please respond with ONLY the JSON object, no markdown.' }]
              : []),
          ],
        },
        { model: 'claude-sonnet-4', maxTokens: 8192, temperature: 0.7 },
      );

      if (!result.ok) {
        output.write(warnMsg(`LLM request failed: ${JSON.stringify(result.error)}\n`));
        return null;
      }

      const spec = parseAppSpecResponse(result.value.content);
      if (!spec) {
        if (attempt === 0) continue;
        output.write(warnMsg('LLM returned invalid spec structure.\n'));
        return null;
      }

      return spec;
    } catch (e) {
      if (attempt === 0) continue;
      output.write(warnMsg(`LLM generation error: ${e instanceof Error ? e.message : String(e)}\n`));
      return null;
    }
  }

  return null;
}

// ============================================================================
// Spec File Writing
// ============================================================================

/** Write the generated spec to YAML files. */
function writeSpecFiles(
  rootDir: string,
  spec: GeneratedAppSpec,
  fileSystem: FileSystem,
): void {
  const specDir = path.join(rootDir, 'agentforge', 'spec');
  fileSystem.mkdir(specDir);

  // Write pages.yaml
  const pagesData = {
    version: '1.0',
    pages: spec.pages.map((p) => ({
      id: p.id,
      name: p.name,
      description: p.description,
      route: p.route,
      status: 'approved',
      components: [...p.components],
      data_sources: [...p.data_sources],
    })),
  };
  writeYaml(path.join(specDir, 'pages.yaml'), pagesData, fileSystem);

  // Write models.yaml
  const modelsData = {
    version: '1.0',
    models: spec.models.map((m) => ({
      id: m.id,
      name: m.name,
      fields: m.fields.map((f) => ({ ...f })),
      db_table: m.db_table,
    })),
  };
  writeYaml(path.join(specDir, 'models.yaml'), modelsData, fileSystem);

  // Write api.yaml
  const apiData = {
    version: '1.0',
    base_url: '/api',
    endpoints: spec.endpoints.map((e) => ({
      id: e.id,
      method: e.method,
      path: e.path,
      description: e.description,
      query_params: e.query_params.map((q) => ({ ...q })),
      response: { ...e.response },
      auth: e.auth,
      status: 'planned',
    })),
  };
  writeYaml(path.join(specDir, 'api.yaml'), apiData, fileSystem);
}

// ============================================================================
// Main Command
// ============================================================================

/**
 * Generate a complete app spec from project context using LLM.
 *
 * Two-phase flow:
 * - Phase 1: If design-tokens.yaml is missing, generates design system
 *   (requires docs/prd.md).
 * - Phase 2: Generates app spec (pages, models, API) using PRD + design context.
 *
 * Opens HTML previews for the user to review before writing files.
 */
export async function designGenerateCommand(
  rootDir: string,
  fileSystem: FileSystem = realFs,
  input: NodeJS.ReadableStream = process.stdin,
  output: NodeJS.WritableStream = process.stdout,
  config?: DesignGenerateConfig,
): Promise<DesignGenerateResult | null> {
  // Load .env file so ANTHROPIC_API_KEY is available
  loadDotEnv(rootDir);

  // Read project context via proper YAML parsing
  let appName = '';
  let description = '';
  const manifestPath = path.join(rootDir, 'agentforge.yaml');
  const manifestResult = readYaml<{ project?: { name?: string; description?: string } }>(manifestPath, fileSystem);
  if (manifestResult.ok) {
    appName = manifestResult.value.project?.name ?? '';
    description = manifestResult.value.project?.description ?? '';
  }

  if (!appName) {
    output.write(errorMsg('Could not read project name from agentforge.yaml. Run `agentforge init` first.\n'));
    return null;
  }

  // Load PRD if available
  const prdResult = loadPRD(rootDir, fileSystem);
  const prdContent = prdResult.ok ? prdResult.value : undefined;

  // Phase 1: Design System — generate if missing, or offer to regenerate if existing
  let tokensResult = loadDesignTokens(rootDir, fileSystem);
  let brandResult = loadBrandSpec(rootDir, fileSystem);
  const designSystemExists = tokensResult.ok && brandResult.ok;

  let regenerateDesign = !designSystemExists;
  if (designSystemExists) {
    const answer = await promptOnce(input, output, '\nDesign system already exists. Regenerate it? (y/n): ');
    regenerateDesign = answer === 'y' || answer === 'yes';
  }

  if (regenerateDesign) {
    if (!prdContent) {
      output.write(errorMsg('PRD not found at docs/prd.md. Run `agentforge describe` first to create a PRD.\n'));
      return null;
    }

    output.write(infoMsg(designSystemExists
      ? '\nRegenerating design options...\n'
      : '\nDesign system not found. Generating design options...\n'));

    const designResult = await generateDesignOptions(
      {
        appName,
        description: description || prdContent.substring(0, 500),
        targetAudience: '',
        prdContent,
      },
      input,
      output,
      config?.designOptionsConfig,
    );

    // Save design system files
    saveDesignTokens(rootDir, designResult.tokens, fileSystem);
    saveBrandSpec(rootDir, designResult.brand, fileSystem);

    // Generate and write tailwind.config.ts
    const tailwindContent = generateTailwindConfig(designResult.tokens);
    fileSystem.writeFile(path.join(rootDir, 'tailwind.config.ts'), tailwindContent);

    // Generate and write global.css
    const stylesDir = path.join(rootDir, 'src', 'styles');
    fileSystem.mkdir(stylesDir);
    const cssContent = generateGlobalCss(designResult.tokens);
    fileSystem.writeFile(path.join(stylesDir, 'global.css'), cssContent);

    output.write(successMsg('\n✓ Design system created:\n'));
    output.write(successMsg('  agentforge/spec/design-tokens.yaml\n'));
    output.write(successMsg('  agentforge/spec/brand.yaml\n'));
    output.write(successMsg('  tailwind.config.ts\n'));
    output.write(successMsg('  src/styles/global.css\n'));

    // Reload tokens and brand
    tokensResult = loadDesignTokens(rootDir, fileSystem);
    brandResult = loadBrandSpec(rootDir, fileSystem);
  }

  if (!tokensResult.ok || !brandResult.ok) {
    output.write(errorMsg('Failed to load design system.\n'));
    return null;
  }

  const tokens = tokensResult.value;
  const brand = brandResult.value;

  // Phase 2: App Spec Generation
  const apiKey = process.env['ANTHROPIC_API_KEY'];
  if (!apiKey) {
    output.write(errorMsg('ANTHROPIC_API_KEY is required for spec generation. Set it in your environment.\n'));
    return null;
  }

  output.write(infoMsg('\nGenerating app specification with AI...\n'));

  let spec = await tryLLMGeneration(
    apiKey,
    { appName, description, tokens, brand, prdContent },
    output,
  );
  if (!spec) {
    output.write(errorMsg('Failed to generate app spec. Please try again.\n'));
    return null;
  }

  // Preview loop — show HTML, get user approval
  const browserFn = config?.openBrowser ?? openInBrowser;
  let approved = false;

  while (!approved) {
    const html = generateAppSpecPreviewHtml(appName, spec, tokens, brand);
    const tmpFile = path.join(os.tmpdir(), `agentforge-spec-preview-${Date.now()}.html`);
    fs.writeFileSync(tmpFile, html, 'utf-8');

    const browserOpened = await browserFn(`file://${tmpFile}`);
    if (browserOpened) {
      output.write(infoMsg('\nApp spec preview opened in your browser.\n'));
    } else {
      output.write(warnMsg('\nCould not open browser. Here is the spec:\n'));
      printCliSummary(spec, output);
    }

    const answer = await promptOnce(input, output, '\nApprove this spec? (y)es / (r)egenerate / (n)o: ');

    // Clean up temp file
    try { fs.unlinkSync(tmpFile); } catch { /* ignore */ }

    if (answer === 'y' || answer === 'yes') {
      approved = true;
    } else if (answer === 'r' || answer === 'regenerate') {
      output.write(infoMsg('Regenerating...\n'));
      const newSpec = await tryLLMGeneration(
        apiKey,
        { appName, description, tokens, brand, prdContent },
        output,
      );
      if (newSpec) {
        spec = newSpec;
      } else {
        output.write(warnMsg('Regeneration failed. Keeping current spec.\n'));
      }
    } else {
      output.write(infoMsg('Cancelled.\n'));
      return null;
    }
  }

  // Write spec files
  writeSpecFiles(rootDir, spec, fileSystem);
  output.write(successMsg(`\nApp spec written:\n`));
  output.write(successMsg(`  agentforge/spec/pages.yaml    (${spec.pages.length} pages)\n`));
  output.write(successMsg(`  agentforge/spec/models.yaml   (${spec.models.length} models)\n`));
  output.write(successMsg(`  agentforge/spec/api.yaml      (${spec.endpoints.length} endpoints)\n`));

  // Next steps
  output.write('\n');
  output.write(successMsg('Next steps:\n'));
  output.write(infoMsg('  1. Design screens in Figma:\n'));
  for (const page of spec.pages.slice(0, 3)) {
    output.write(infoMsg(`         agentforge design:figma "${page.name.toLowerCase()}"\n`));
  }
  if (spec.pages.length > 3) {
    output.write(infoMsg(`         ... and ${spec.pages.length - 3} more pages\n`));
  }
  output.write(infoMsg('     Or design screens in Penpot:\n'));
  for (const page of spec.pages.slice(0, 3)) {
    output.write(infoMsg(`         agentforge design:penpot "${page.name.toLowerCase()}"\n`));
  }
  if (spec.pages.length > 3) {
    output.write(infoMsg(`         ... and ${spec.pages.length - 3} more pages\n`));
  }
  output.write(infoMsg('  2. Re-run to update:         agentforge design:generate\n'));
  output.write(infoMsg('  3. Start full design phase:   agentforge start design\n'));
  output.write('\n');

  return { spec, source: 'llm' };
}
