/**
 * @module @agentforge/cli/commands/generate-design-options
 *
 * LLM-generated design system options with rich HTML preview.
 * Falls back to hardcoded archetypes when no API key or on failure.
 */

import * as os from 'node:os';
import * as path from 'node:path';
import * as fs from 'node:fs';
import type { DesignTokensSpec, BrandSpec, PromptTrace, FileSystem, OpacitySpec, MotionSpec, StateTokensSpec, TypographyScaleEntry, SpacingSpec, BorderSpec, TouchTargetSpec, LayoutSpec, ZIndexSpec, BorderWidthSpec, TextExtrasSpec } from '@agentforge/core';
import { DEFAULT_LAYOUT_TOKENS, DEFAULT_OPACITY, DEFAULT_MOTION, DEFAULT_STATE, DEFAULT_ELEVATION, DEFAULT_TYPOGRAPHY_SCALE } from '../design/design-tokens-defaults.js';
import type { PreviewData } from '../design/design-tokens-defaults.js';
import { validateDesignTokens, validateBrandSpec, recordPromptTrace, loadPRD, debugLog, logDefaults } from '@agentforge/core';
import { createClaudeProvider, resolveClaudeAuth, authResultToProviderConfig } from '@agentforge/providers';
import type { LLMProvider, ProviderConfig } from '@agentforge/providers';
import { resolveCLIModel } from '../utils/resolve-cli-model.js';
import { infoMsg, warnMsg, successMsg } from '../formatter.js';
import { promptOnce } from '../utils/prompt-once.js';
import { openInBrowser } from '../utils/open-in-browser.js';
import { generatePreviewHtml } from '../design/preview-html.js';
import { buildDesignTokensSpec } from '../design/archetypes.js';
import type { DesignArchetype } from '../design/archetypes.js';

// Re-export defaults — canonical location is ../design/design-tokens-defaults.js
export { DEFAULT_LAYOUT_TOKENS, SHARED_LAYOUT, DEFAULT_OPACITY, DEFAULT_MOTION, DEFAULT_STATE, DEFAULT_ELEVATION, DEFAULT_TYPOGRAPHY_SCALE, DEFAULT_PREVIEW } from '../design/design-tokens-defaults.js';
export type { PreviewData } from '../design/design-tokens-defaults.js';

/** A single design option generated by the LLM. */
export interface DesignOption {
  readonly label: string;
  readonly vibe: string;
  readonly colors: {
    readonly primitive: Record<string, string>;
    readonly semantic: Record<string, string> & {
      readonly 'background-primary': string;
      readonly 'text-primary': string;
      readonly 'cta-primary': string;
      readonly error: string;
    };
  };
  readonly fonts: {
    readonly display: string;
    readonly body: string;
  };
  readonly brand: {
    readonly tone: string;
    readonly illustrationDirection: string;
    readonly illustrationDescription: string;
    readonly motionFeel: string;
  };
  readonly elevation?: {
    readonly levels: readonly {
      readonly level: number;
      readonly shadow: string;
      readonly description: string;
    }[];
  };
  readonly typography_scale?: readonly TypographyScaleEntry[];
  readonly spacing?: SpacingSpec;
  readonly borders?: BorderSpec;
  readonly touch_targets?: TouchTargetSpec;
  readonly layout?: LayoutSpec;
  readonly z_index?: ZIndexSpec;
  readonly opacity?: OpacitySpec;
  readonly motion?: MotionSpec;
  readonly state?: StateTokensSpec;
  readonly border_styles?: BorderWidthSpec;
  readonly text_extras?: TextExtrasSpec;
  readonly preview?: PreviewData;
}

/** Result returned from generateDesignOptions. */
export interface GenerateDesignResult {
  readonly tokens: DesignTokensSpec;
  readonly brand: BrandSpec;
  readonly source: 'llm' | 'fallback' | 'catalog';
}

/**
 * JSON Schema for structured output — the original 6-property schema that
 * fits within Anthropic's grammar compiler limits.
 *
 * Extra design tokens (typography_scale, borders, motion, preview) are
 * requested via a single "extras" JSON string field to avoid schema complexity.
 */
const DESIGN_OPTIONS_SCHEMA: Record<string, unknown> = {
  type: 'object',
  properties: {
    options: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          label: { type: 'string' },
          vibe: { type: 'string' },
          colors: {
            type: 'object',
            properties: {
              primitive: {
                type: 'array',
                description: '5-8 named colors, each with a kebab-case name and hex value',
                items: {
                  type: 'object',
                  properties: {
                    name: { type: 'string', description: 'kebab-case color name, e.g. "deep-teal"' },
                    hex: { type: 'string', description: 'hex color value, e.g. "#0F6E56"' },
                  },
                  required: ['name', 'hex'],
                  additionalProperties: false,
                },
              },
              semantic: {
                type: 'object',
                properties: {
                  'background-primary': { type: 'string' },
                  'surface-primary': { type: 'string' },
                  'surface-elevated': { type: 'string' },
                  'text-primary': { type: 'string' },
                  'text-secondary': { type: 'string' },
                  'text-disabled': { type: 'string' },
                  'text-on-cta': { type: 'string' },
                  'cta-primary': { type: 'string' },
                  'cta-hover': { type: 'string' },
                  'border-default': { type: 'string' },
                  'border-focus': { type: 'string' },
                  'border-error': { type: 'string' },
                  error: { type: 'string' },
                  success: { type: 'string' },
                  warning: { type: 'string' },
                  info: { type: 'string' },
                  overlay: { type: 'string' },
                  'surface-secondary': { type: 'string' },
                  'surface-input': { type: 'string' },
                },
                required: [
                  'background-primary', 'surface-primary', 'surface-elevated',
                  'surface-secondary', 'surface-input',
                  'text-primary', 'text-secondary', 'text-disabled', 'text-on-cta',
                  'cta-primary', 'cta-hover', 'border-default', 'border-focus',
                  'border-error', 'error', 'success', 'warning', 'info', 'overlay',
                ],
                additionalProperties: false,
              },
            },
            required: ['primitive', 'semantic'],
            additionalProperties: false,
          },
          fonts: {
            type: 'object',
            properties: {
              display: { type: 'string' },
              body: { type: 'string' },
            },
            required: ['display', 'body'],
            additionalProperties: false,
          },
          brand: {
            type: 'object',
            properties: {
              tone: { type: 'string' },
              illustrationDirection: { type: 'string' },
              illustrationDescription: { type: 'string' },
              motionFeel: { type: 'string', enum: ['snappy', 'smooth', 'bouncy', 'subtle'] },
            },
            required: ['tone', 'illustrationDirection', 'illustrationDescription', 'motionFeel'],
            additionalProperties: false,
          },
          elevation: {
            type: 'object',
            properties: {
              levels: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: {
                    level: { type: 'number' },
                    shadow: { type: 'string' },
                    description: { type: 'string' },
                  },
                  required: ['level', 'shadow', 'description'],
                  additionalProperties: false,
                },
              },
            },
            required: ['levels'],
            additionalProperties: false,
          },
          extras: {
            type: 'string',
            description: 'JSON string containing optional extra tokens. Include a JSON object with any of: "typography_scale" (array of {role,size,weight,family,line_height}), "borders" ({radius:{small,medium,large,pill}}), "motion" ({durations:{fast,normal,slow},easings:{default,emphasized}}), "border_styles" ({widths:{thin,medium,thick}, styles:{default,dashed}}), "text_extras" ({transforms:{uppercase,lowercase,capitalize}, letter_spacing:{tight,normal,wide}}), "preview" ({metrics:[{label,value,trend}],table_rows:[{name,status,amount,date}],nav_items:[string]}). Example: {"borders":{"radius":{"small":4,"medium":8,"large":16,"pill":9999}},"border_styles":{"widths":{"thin":1,"medium":2,"thick":4},"styles":{"default":"solid","dashed":"dashed"}},"text_extras":{"transforms":{"uppercase":"uppercase","lowercase":"lowercase","capitalize":"capitalize"},"letter_spacing":{"tight":"-0.02em","normal":"0","wide":"0.05em"}},"preview":{"metrics":[{"label":"Revenue","value":"$12k","trend":"+5%"}],"table_rows":[{"name":"Alice","status":"Active","amount":"$100","date":"2024-01"}],"nav_items":["Dashboard","Settings"]}}',
          },
        },
        required: ['label', 'vibe', 'colors', 'fonts', 'brand'],
        additionalProperties: false,
      },
    },
  },
  required: ['options'],
  additionalProperties: false,
};

/**
 * Convert structured output to DesignOption format.
 * Handles the core schema fields + parses the "extras" JSON string for
 * optional tokens (typography_scale, borders, motion, preview).
 */
function normalizeStructuredOptions(
  raw: { options: Array<Record<string, unknown>> },
): DesignOption[] {
  return raw.options.map((opt) => {
    const colors = opt.colors as { primitive: Array<{ name: string; hex: string }> | Record<string, string>; semantic: Record<string, string> };
    // Convert primitive array → Record if the structured schema was used
    const primitive: Record<string, string> = Array.isArray(colors.primitive)
      ? Object.fromEntries(colors.primitive.map((c) => [c.name, c.hex]))
      : colors.primitive;

    const result: Record<string, unknown> = {
      ...opt,
      colors: { primitive, semantic: colors.semantic },
    };

    // Parse extras JSON string for optional tokens
    const extrasRaw = opt.extras as string | undefined;
    if (extrasRaw && typeof extrasRaw === 'string') {
      try {
        const extras = JSON.parse(extrasRaw) as Record<string, unknown>;

        // Typography scale: coerce size/weight/line_height from "24px" → 24
        if (extras.typography_scale && Array.isArray(extras.typography_scale)) {
          result.typography_scale = (extras.typography_scale as Record<string, unknown>[]).map((entry) => ({
            ...entry,
            size: parseFloat(String(entry.size)) || 14,
            weight: parseFloat(String(entry.weight)) || 400,
            line_height: parseFloat(String(entry.line_height)) || 1.5,
          }));
        }

        if (extras.borders) result.borders = extras.borders;

        // Motion: coerce durations from "150ms" → 150
        if (extras.motion) {
          const motion = extras.motion as Record<string, unknown>;
          const durations = motion.durations as Record<string, unknown> | undefined;
          if (durations) {
            motion.durations = {
              fast: parseFloat(String(durations.fast)) || 100,
              normal: parseFloat(String(durations.normal)) || 200,
              slow: parseFloat(String(durations.slow)) || 400,
            };
          }
          result.motion = motion;
        }

        if (extras.border_styles) result.border_styles = extras.border_styles;
        if (extras.text_extras) result.text_extras = extras.text_extras;

        if (extras.preview) result.preview = extras.preview;
      } catch {
        // Malformed extras — skip, non-critical
      }
    }
    delete result.extras;

    return result as unknown as DesignOption;
  });
}

/** Build the system prompt for the LLM. */
function buildSystemPrompt(output: NodeJS.WritableStream): string {
  const systemPrompt = `You are a design system expert. Generate 3 distinct design direction options for a web application.

Each option should feel meaningfully different — vary the mood, color temperature, and typography personality.

Rules:
- 5-8 primitive colors per option, using kebab-case names (e.g. "deep-teal", "warm-cream")
- Semantic color values should reference primitive color names (except overlay which is an rgba value)
- Use real Google Fonts that pair well
- Ensure sufficient contrast between background-primary and text-primary (WCAG AA)
- surface-secondary should be a subtle variant of surface-primary (e.g. slightly darker or lighter) for nested content areas
- surface-input should be the background for input fields (often same as background-primary or slightly different)
- Elevation shadows should feel cohesive with the design direction (4 levels: flat, cards, dropdowns, modals)

The "extras" field is a JSON string for optional design tokens. Include a JSON object with any of these keys:
- "typography_scale": array of {role, size, weight, family, line_height} — include if design needs non-standard sizing. 6 roles: heading-1, heading-2, heading-3, body, label, small. "family" must be "display" or "body" (abstract keys, not actual font names).
- "borders": {radius: {small, medium, large, pill}} — include for specific corner treatment (small=0 for brutalist, large=24 for soft/playful).
- "motion": {durations: {fast, normal, slow}, easings: {default, emphasized}} — include if brand personality suggests specific animation character.
- "preview": {metrics: [{label, value, trend}], table_rows: [{name, status, amount, date}], nav_items: [string]} — SHOULD include 3 metrics, 4 table_rows, 4 nav_items matching the app domain.`
  debugLog('buildSystemPrompt: Building system prompt');
  return systemPrompt;
}

/** Build the user prompt with app context. */
function buildUserPrompt(context: {
  appName: string;
  description: string;
  targetAudience: string;
  prdContent?: string;
}, output: NodeJS.WritableStream): string {
  debugLog(context.prdContent ? 'buildUserPrompt: prdContent included in the prompt' : 'buildUserPrompt: prdContent not included in the prompt');
  const appContext = context.prdContent
    ? `- App name: ${context.appName}\n\nPRD:\n${context.prdContent}`
    : `- App name: ${context.appName}\n- Description: ${context.description || 'A web application'}\n- Target audience: ${context.targetAudience || 'general'}`;

  return `Generate 3 design system options for:\n${appContext}`;
}

/** Parse and validate LLM response into DesignOption array. */
export function parseLLMResponse(raw: string): DesignOption[] {
  // Strip markdown code fences if present
  const cleaned = raw.replace(/^```(?:json)?\s*/m, '').replace(/\s*```\s*$/m, '').trim();
  const parsed = JSON.parse(cleaned) as Record<string, unknown>;

  // Accept the canonical key "options" or common LLM variants
  const candidates = parsed.options
    ?? parsed.designSystems
    ?? parsed.themes
    ?? parsed.designOptions
    ?? parsed.design_systems
    ?? parsed.design_options;

  // If the top-level value is itself an array, use it directly
  const optionsArray = Array.isArray(candidates)
    ? candidates
    : Array.isArray(parsed) ? parsed as unknown as DesignOption[] : undefined;

  if (!Array.isArray(optionsArray)) {
    throw new Error('Response missing "options" array — got keys: ' + Object.keys(parsed).join(', '));
  }

  return (optionsArray as DesignOption[]).filter((opt) => {
    if (!opt.label || !opt.vibe) return false;
    if (!opt.colors?.primitive || !opt.colors?.semantic) return false;
    const primCount = Object.keys(opt.colors.primitive).length;
    if (primCount < 5) return false;
    if (primCount > 8) warnMsg(`Option "${opt.label}" has ${primCount} primitive colors (expected 5-8).\n`);
    if (!opt.colors.semantic['background-primary'] || !opt.colors.semantic['text-primary']) return false;
    if (!opt.colors.semantic['cta-primary'] || !opt.colors.semantic.error) return false;
    if (!opt.fonts?.display || !opt.fonts?.body) return false;
    if (!opt.brand?.tone) return false;
    return true;
  });
}

// Order matters: entries are resolved top-to-bottom.
// text-secondary must be filled before border-default (which derives from it).
const SEMANTIC_COLOR_DEFAULTS: Record<string, (opt: DesignOption) => string> = {
  'surface-primary': (opt) => opt.colors.semantic['background-primary'],
  'surface-elevated': (opt) => opt.colors.semantic['background-primary'],
  'surface-secondary': (opt) => opt.colors.semantic['surface-primary'],
  'surface-input': (opt) => opt.colors.semantic['background-primary'],
  'text-secondary': (opt) => opt.colors.semantic['text-primary'],
  'text-disabled': (opt) => opt.colors.semantic['text-primary'],
  'text-on-cta': (opt) => opt.colors.semantic['background-primary'],
  'cta-hover': (opt) => opt.colors.semantic['cta-primary'],
  'border-default': (opt) => opt.colors.semantic['text-secondary'] ?? opt.colors.semantic['text-primary'],
  'border-focus': (opt) => opt.colors.semantic['cta-primary'],
  'border-error': (opt) => opt.colors.semantic['error'],
  // Emergency fallbacks only — these hex values are not archetype-aware.
  // The expanded prompt makes all 17 keys required, so these should
  // rarely fire. They exist as a safety net for truly broken LLM output.
  success: () => '#16A34A',
  warning: () => '#CA8A04',
  info: (opt) => opt.colors.semantic['cta-primary'],
  overlay: () => 'rgba(0,0,0,0.5)',
};

/**
 * Backfill missing semantic colors on parsed LLM options.
 * Uses heuristic derivations so downstream consumers always have all 17 keys.
 */
export function backfillSemanticColors(options: DesignOption[], output: NodeJS.WritableStream): DesignOption[] {
  return options.map((opt) => {
    const filled = { ...opt.colors.semantic };
    let missingKeys = false;
    let missingKeysList: string[] = [];
    for (const [key, derive] of Object.entries(SEMANTIC_COLOR_DEFAULTS)) {
      if (!filled[key]) {
        missingKeys = true;
        missingKeysList.push(key);
        filled[key] = derive({ ...opt, colors: { ...opt.colors, semantic: filled } } as DesignOption);
      }
    }
    if (missingKeys) {
      debugLog('backfillSemanticColors: Missing keys: ' + missingKeysList.join(', '));
    }
    return {
      ...opt,
      colors: { ...opt.colors, semantic: filled as DesignOption['colors']['semantic'] },
    };
  });
}

/**
 * Backfill missing elevation on parsed LLM options.
 * Injects DEFAULT_ELEVATION when the LLM omits it.
 */
export function backfillElevation(options: DesignOption[], output: NodeJS.WritableStream): DesignOption[] {
  return options.map((opt) => {
    if (opt.elevation && opt.elevation.levels.length) {
      // add level 0 if it does not exist: { level: 0, shadow: 'none', description: 'Flat, no elevation' }
      if (!opt.elevation.levels.find((level) => level.level === 0)) {
        const withLevel0 = [{ level: 0, shadow: 'none', description: 'Flat, no elevation' }, ...opt.elevation.levels];
        opt = { ...opt, elevation: { ...opt.elevation, levels: withLevel0 } };
      }
    }
    if (opt.elevation && opt.elevation.levels.length >= 4) return opt;
    debugLog('backfillElevation: LLM omitted elevation — backfilling with defaults');
    return { ...opt, elevation: DEFAULT_ELEVATION };
  });
}

/** Convert a DesignOption to DesignTokensSpec. */
export function optionToTokens(option: DesignOption, output: NodeJS.WritableStream): DesignTokensSpec {
  debugLog('optionToTokens: Converting DesignOption to DesignTokensSpec');
  debugLog('optionToTokens: Merging option overrides with default tokens');
  return {
    version: '1.0',
    created_by: 'agentforge-init-llm',
    colors: {
      primitive: option.colors.primitive,
      semantic: option.colors.semantic,
    },
    typography: {
      font_families: { display: option.fonts.display, body: option.fonts.body },
      scale: (option.typography_scale ?? [...DEFAULT_TYPOGRAPHY_SCALE]).map((entry) => {
        // Normalize actual font names to abstract keys ("display"/"body")
        if (entry.family === 'display' || entry.family === 'body') return entry;
        const family = entry.family === option.fonts.display ? 'display'
          : entry.family === option.fonts.body ? 'body'
            : 'body'; // default to body for unknown fonts
        return { ...entry, family };
      }),
    },
    spacing: option.spacing ?? DEFAULT_LAYOUT_TOKENS.spacing,
    borders: option.borders ?? DEFAULT_LAYOUT_TOKENS.borders,
    touch_targets: option.touch_targets ?? DEFAULT_LAYOUT_TOKENS.touch_targets,
    elevation: option.elevation ?? DEFAULT_ELEVATION,
    layout: option.layout ?? DEFAULT_LAYOUT_TOKENS.layout,
    z_index: option.z_index ?? DEFAULT_LAYOUT_TOKENS.z_index,
    opacity: option.opacity ?? DEFAULT_OPACITY,
    motion: option.motion ?? DEFAULT_MOTION,
    state: option.state ?? DEFAULT_STATE,
    ...(option.border_styles && { border_styles: option.border_styles }),
    ...(option.text_extras && { text_extras: option.text_extras }),
  } satisfies DesignTokensSpec;
}

/** Convert a DesignOption to BrandSpec. */
export function optionToBrand(option: DesignOption, audience: string, output: NodeJS.WritableStream): BrandSpec {
  debugLog('optionToBrand: Converting DesignOption to BrandSpec');
  debugLog('optionToBrand: Hardcoding accessibility=AA, page_transitions=fade, duration_base_ms=200, easing=ease-out');
  logDefaults('optionToBrand', {
    illustrationDirection: [option.brand.illustrationDirection, 'minimal'],
    illustrationDescription: [option.brand.illustrationDescription, 'Clean illustrations with accent color highlights'],
    motionFeel: [option.brand.motionFeel, 'snappy'],
    audience: [audience, 'general'],
  });
  return {
    version: '1.0',
    created_by: 'agentforge-init-llm',
    identity: {
      tone: option.brand.tone,
      audience: audience || 'general',
    },
    illustration_style: {
      direction: option.brand.illustrationDirection || 'minimal',
      description: option.brand.illustrationDescription || 'Clean illustrations with accent color highlights',
    },
    motion_principles: {
      page_transitions: 'fade',
      interaction_feel: option.brand.motionFeel || 'snappy',
      easing: 'ease-out',
      duration_base_ms: 200,
    },
    accessibility: {
      wcag_level: 'AA',
    },
  };
}

/** Build the 3 fallback options from existing archetypes. */
export function buildFallbackOptions(): DesignOption[] {
  const archetypes: { key: DesignArchetype; label: string; vibe: string }[] = [
    { key: 'warm', label: 'Warm & Inviting', vibe: 'Cream, teal, rounded, friendly — approachable and playful' },
    { key: 'professional', label: 'Clean & Professional', vibe: 'White, slate, blue accent — structured and trustworthy' },
    { key: 'bold', label: 'Bold & Modern', vibe: 'Dark, violet, lime — geometric and cutting-edge' },
  ];

  return archetypes.map(({ key, label, vibe }) => {
    const tokens = buildDesignTokensSpec(key);
    const semantic = tokens.colors.semantic as unknown as DesignOption['colors']['semantic'];
    return {
      label,
      vibe,
      colors: { primitive: tokens.colors.primitive as Record<string, string>, semantic },
      fonts: tokens.typography.font_families as { display: string; body: string },
      brand: {
        tone: key === 'warm' ? 'playful-warm' : key === 'professional' ? 'professional-clean' : 'bold-modern',
        illustrationDirection: 'minimal',
        illustrationDescription: 'Clean illustrations with accent color highlights',
        motionFeel: 'snappy',
      },
      elevation: tokens.elevation,
    };
  });
}



// Re-export — canonical location is ../design/preview-html.js
export { generatePreviewHtml } from '../design/preview-html.js';



// Re-export for backward compatibility — canonical location is ../utils/open-in-browser.js
export { openInBrowser } from '../utils/open-in-browser.js';

/** Print a CLI summary table when browser can't open. */
function printCliSummary(
  options: DesignOption[],
  output: NodeJS.WritableStream,
): void {
  options.forEach((opt, i) => {
    const colors = Object.values(opt.colors.primitive).join(', ');
    output.write(infoMsg(`\n  Option ${i + 1}: ${opt.label}\n`));
    output.write(infoMsg(`    ${opt.vibe}\n`));
    output.write(infoMsg(`    Colors: ${colors}\n`));
    output.write(infoMsg(`    Fonts: ${opt.fonts.display} + ${opt.fonts.body}\n`));
    output.write(infoMsg(`    Tone: ${opt.brand.tone}\n`));
  });
}

// Re-export for backward compatibility — canonical location is ../utils/prompt-once.js
export { promptOnce } from '../utils/prompt-once.js';

/** Options for customizing generateDesignOptions behavior (e.g. in tests). */
export interface GenerateDesignOptionsConfig {
  /** Override browser opener. Return true if browser opened. */
  readonly openBrowser?: (url: string) => Promise<boolean>;
  /** When true, skip LLM calls and use built-in archetypes directly. */
  readonly mock?: boolean;
  /** Optional project root used to load docs/prd.md when context.prdContent is not set. */
  readonly rootDir?: string;
  /** Optional filesystem to use with rootDir for PRD loading. */
  readonly fileSystem?: FileSystem;
}

type DesignOptionsContext = {
  appName: string;
  description: string;
  targetAudience: string;
  prdContent?: string;
};

/**
 * Apply caller `prdContent` if present; otherwise read `docs/prd.md` from disk when
 * `rootDir` + `fileSystem` are configured. Does not prompt — see
 * `resolveEffectiveDesignOptionsContext()` for the full PRD resolution flow.
 */
export function resolveDesignOptionsContext(
  context: DesignOptionsContext,
  config?: GenerateDesignOptionsConfig,
): DesignOptionsContext {
  if (context.prdContent) {
    return context;
  }
  if (!config?.rootDir || !config.fileSystem) {
    return context;
  }

  const prdResult = loadPRD(config.rootDir, config.fileSystem);
  if (!prdResult.ok) {
    return context;
  }

  return { ...context, prdContent: prdResult.value };
}

/**
 * Full PRD resolution for design options (logical order, not redundant):
 * 1. If the caller already passed `prdContent`, use it.
 * 2. Else try `docs/prd.md` on disk immediately — if it exists, load it and skip prompting.
 *    (This is why a first call to `resolveDesignOptionsContext` here does *not* “miss” the PRD:
 *    it is the step that picks up an existing file.)
 * 3. If still missing and we have a project root, ensure `docs/` exists, optionally ask the user
 *    to add the file, then load again.
 */
async function resolveEffectiveDesignOptionsContext(
  context: DesignOptionsContext,
  config: GenerateDesignOptionsConfig | undefined,
  inp: NodeJS.ReadableStream,
  out: NodeJS.WritableStream,
): Promise<DesignOptionsContext> {
  // Single automatic read: if docs/prd.md exists, we load it here and skip all prompting.
  let effectiveContext = resolveDesignOptionsContext(context, config);
  if (effectiveContext.prdContent) {
    return effectiveContext;
  }

  // PRD is still missing after the automatic disk read. We only offer the interactive pause when
  // we can read paths on disk (--mock skips this; omitting rootDir/fileSystem means no project
  // context). If we return here, we are not "missing PRD again" — we simply cannot show the prompt.
  const rootDir = config?.rootDir;
  const fileSystem = config?.fileSystem;
  const canOfferInteractivePrdPause =
    !config?.mock && rootDir !== undefined && rootDir !== '' && fileSystem !== undefined;
  if (!canOfferInteractivePrdPause) {
    return effectiveContext;
  }

  // loadPRD already ran inside resolveDesignOptionsContext; we only reach here when the file
  // was missing or unreadable. The prompts below are an optional second chance: user adds the
  // file on disk locally (not an "upload"), then we call loadPRD again.
  const docsDir = path.join(rootDir, 'docs');
  fileSystem.mkdir(docsDir);
  const projectFolderName = path.basename(path.resolve(rootDir));
  const prdRelPath = path.join(projectFolderName, 'docs', 'prd.md');

  const pauseToAddPrd = await promptOnce(
    inp,
    out,
    `Do you have a PRD for "${effectiveContext.appName}"? (y/n): `,
  );
  if (pauseToAddPrd.toLowerCase() === 'y' || pauseToAddPrd.toLowerCase() === 'yes') {
    await promptOnce(
      inp,
      out,
      `Add your markdown PRD at ${prdRelPath}, then press Enter: `,
    );
    effectiveContext = resolveDesignOptionsContext(context, config);
    if (effectiveContext.prdContent) {
      out.write(successMsg(`✓ Loaded PRD from ${prdRelPath}\n`));
    } else {
      out.write(
        warnMsg(`${prdRelPath} still not readable. Continuing with name and description only.\n`),
      );
    }
  } else {
    out.write(infoMsg('Continuing with app name and description only (no PRD file).\n'));
  }

  return effectiveContext;
}

/**
 * Generate 3 design system options (LLM or fallback), show preview, let user pick.
 */
export async function generateDesignOptions(
  context: DesignOptionsContext,
  input?: NodeJS.ReadableStream,
  output?: NodeJS.WritableStream,
  config?: GenerateDesignOptionsConfig,
  promptTraces?: PromptTrace[],
): Promise<GenerateDesignResult> {
  const out = output ?? process.stdout;
  const inp = input ?? process.stdin;

  let options: DesignOption[];
  let source: 'llm' | 'fallback' = 'fallback';
  const effectiveContext = await resolveEffectiveDesignOptionsContext(context, config, inp, out);

  // Try LLM generation (unless --mock is set)
  const authResult = resolveClaudeAuth();
  const llmProviderConfig = authResult ? authResultToProviderConfig(authResult) : null;
  if (config?.mock) {
    out.write(infoMsg('\n--mock: skipping LLM, using built-in archetypes\n'));
    options = buildFallbackOptions();
  } else if (llmProviderConfig) {
    out.write(infoMsg('\nCalling Claude Sonnet to generate design themes...\n'));
    const llmOptions = await tryLLMGeneration(llmProviderConfig, effectiveContext, out, promptTraces);
    if (llmOptions) {
      options = llmOptions;
      source = 'llm';
      out.write(successMsg(`✓ ${options.length} design themes generated via LLM\n`));
    } else {
      out.write(warnMsg('LLM generation failed, falling back to built-in archetypes\n'));
      options = buildFallbackOptions();
    }
  } else {
    out.write(warnMsg('No Claude auth configured, using built-in archetypes\n'));
    options = buildFallbackOptions();
  }

  // Generate HTML preview and open in browser
  const html = generatePreviewHtml(effectiveContext.appName, options);
  const tmpFile = path.join(os.tmpdir(), `agentforge-design-preview-${Date.now()}.html`);
  fs.writeFileSync(tmpFile, html, 'utf-8');

  const browserFn = config?.openBrowser ?? openInBrowser;
  const browserOpened = await browserFn(`file://${tmpFile}`);
  if (browserOpened) {
    out.write(infoMsg('\nDesign preview opened in your browser.\n'));
  } else {
    out.write(warnMsg('\nCould not open browser. Here are the options:\n'));
    printCliSummary(options, out);
  }

  // Prompt user to choose — read directly from stream to avoid readline buffering
  // issues that consume data intended for subsequent readline consumers
  let choice: number | undefined;

  while (choice === undefined) {
    const answer = await promptOnce(inp, out, '\nChoose 1, 2, or 3 (or \'r\' to regenerate): ');

    if (answer === 'r' && llmProviderConfig && !config?.mock) {
      out.write(infoMsg('Regenerating via LLM...\n'));
      const llmOptions = await tryLLMGeneration(llmProviderConfig, effectiveContext, out, promptTraces);
      if (llmOptions) {
        options = llmOptions;
        source = 'llm';
        const newHtml = generatePreviewHtml(effectiveContext.appName, options);
        fs.writeFileSync(tmpFile, newHtml, 'utf-8');
        const opened = await browserFn(`file://${tmpFile}`);
        if (!opened) {
          printCliSummary(options, out);
        } else {
          out.write(infoMsg('Preview refreshed in browser.\n'));
        }
      } else {
        out.write(warnMsg('Regeneration failed. Keeping current options.\n'));
      }
      continue;
    }

    const num = parseInt(answer, 10);
    if (num >= 1 && num <= options.length) {
      choice = num;
    } else {
      out.write(warnMsg('Please enter 1, 2, or 3.\n'));
    }
  }

  // Clean up temp file
  try {
    fs.unlinkSync(tmpFile);
  } catch {
    // ignore cleanup errors
  }

  const selected = options[choice - 1];
  const tokens = optionToTokens(selected, out);
  const brand = optionToBrand(selected, effectiveContext.targetAudience, out);

  return { tokens, brand, source };
}

/** Attempt LLM generation, return null on failure. */
async function tryLLMGeneration(
  providerConfig: ProviderConfig,
  context: { appName: string; description: string; targetAudience: string; prdContent?: string },
  output: NodeJS.WritableStream,
  promptTraces?: PromptTrace[],
): Promise<DesignOption[] | null> {
  let provider: LLMProvider;
  try {
    provider = createClaudeProvider(resolveCLIModel(), providerConfig);
  } catch (err) {
    output.write(warnMsg(`Failed to create LLM provider: ${err instanceof Error ? err.message : String(err)}\n`));
    return null;
  }

  const systemPrompt = buildSystemPrompt(output);
  const userPrompt = buildUserPrompt(context, output);

  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const messages: { role: 'user'; content: string }[] = [
        { role: 'user', content: userPrompt },
      ];
      const prompt = { system: systemPrompt, messages };
      const opts = {
        model: resolveCLIModel(),
        maxTokens: 8192,
        temperature: 0.8,
        responseSchema: { schema: DESIGN_OPTIONS_SCHEMA },
      };

      recordPromptTrace(
        { promptTraces },
        'design-system-generation',
        prompt,
        opts,
      );

      const result = await provider.complete(prompt, opts);
      if (!result.ok) {
        output.write(warnMsg(`LLM request failed: ${JSON.stringify(result.error)}\n`));
        return null;
      }

      // With structured output the response is guaranteed valid JSON matching the schema.
      // Use the pre-parsed structured field when available, fall back to parsing content.
      const parsed = (result.value.structured ?? JSON.parse(result.value.content)) as { options: Array<Record<string, unknown>> };
      const rawOptions = normalizeStructuredOptions(parsed);

      const withSemantics = backfillSemanticColors(rawOptions, output);
      const options = backfillElevation(withSemantics, output);
      if (options.length < 2) {
        output.write(warnMsg(`LLM returned ${options.length} valid option(s), need at least 2 ${attempt === 0 ? '— retrying...' : ', using defaults.'}\n`));
        if (attempt === 0) continue;
        return null;
      }

      // Validate each option by converting to tokens/brand
      const validOptions = options.filter((opt) => {
        const tokens = optionToTokens(opt, output);
        const brand = optionToBrand(opt, context.targetAudience, output);
        const tokensValid = validateDesignTokens(tokens);
        const brandValid = validateBrandSpec(brand);
        if (!tokensValid.ok) output.write(warnMsg(`  Option "${opt.label}": token validation failed — ${JSON.stringify(tokensValid.error)}\n`));
        if (!brandValid.ok) output.write(warnMsg(`  Option "${opt.label}": brand validation failed — ${JSON.stringify(brandValid.error)}\n`));
        return tokensValid.ok && brandValid.ok;
      });

      if (validOptions.length < 2) {
        output.write(warnMsg(`Only ${validOptions.length}/${options.length} options passed validation${attempt === 0 ? ' — retrying...' : ', using defaults.'}\n`));
        if (attempt === 0) continue;
        return null;
      }

      return validOptions.slice(0, 3);
    } catch (err) {
      output.write(warnMsg(`LLM error (attempt ${attempt + 1}/2): ${err instanceof Error ? err.message : String(err)}\n`));
      if (attempt === 0) continue;
      return null;
    }
  }

  return null;
}
