/**
 * @module @agentforge/cli/commands/generate-design-options
 *
 * LLM-generated design system options with rich HTML preview.
 * Falls back to hardcoded archetypes when no API key or on failure.
 */

import * as readline from 'node:readline';
import * as os from 'node:os';
import * as path from 'node:path';
import * as fs from 'node:fs';
import { exec } from 'node:child_process';
import type { DesignTokensSpec, BrandSpec } from '@agentforge/core';
import { validateDesignTokens, validateBrandSpec } from '@agentforge/core';
import { createClaudeProvider } from '@agentforge/providers';
import type { LLMProvider } from '@agentforge/providers';
import { infoMsg, warnMsg } from '../formatter.js';
import { buildDesignTokensSpec } from './init.js';
import type { DesignArchetype } from './init.js';

/** Shared layout tokens — enforced in code, never LLM-generated. */
export const SHARED_LAYOUT = {
  spacing: { unit: 8, scale: [4, 8, 12, 16, 24, 32, 48, 64] as readonly number[] },
  borders: { radius: { small: 8, medium: 12, large: 16, pill: 9999 } },
  touch_targets: { minimum_height: 44, minimum_width: 44 },
} as const;

/** Fixed typography scale — sizes/weights are consistent across options. */
const FIXED_TYPOGRAPHY_SCALE = [
  { role: 'heading-1', size: 32, weight: 700, family: 'display' },
  { role: 'heading-2', size: 24, weight: 700, family: 'display' },
  { role: 'heading-3', size: 18, weight: 600, family: 'display' },
  { role: 'body', size: 14, weight: 400, family: 'body' },
  { role: 'label', size: 12, weight: 500, family: 'body' },
  { role: 'small', size: 11, weight: 400, family: 'body' },
] as const;

/** A single design option generated by the LLM. */
export interface DesignOption {
  readonly label: string;
  readonly vibe: string;
  readonly colors: {
    readonly primitive: Record<string, string>;
    readonly semantic: {
      readonly 'background-primary': string;
      readonly 'text-primary': string;
      readonly 'cta-primary': string;
      readonly error: string;
    };
  };
  readonly fonts: {
    readonly display: string;
    readonly body: string;
  };
  readonly brand: {
    readonly tone: string;
    readonly illustrationDirection: string;
    readonly illustrationDescription: string;
    readonly motionFeel: string;
  };
  readonly components?: Record<string, Record<string, Record<string, string | number>>>;
}

/** Result returned from generateDesignOptions. */
export interface GenerateDesignResult {
  readonly tokens: DesignTokensSpec;
  readonly brand: BrandSpec;
  readonly source: 'llm' | 'fallback' | 'catalog';
}

/** Build the system prompt for the LLM. */
function buildSystemPrompt(): string {
  return `You are a design system expert. Generate 3 distinct design direction options for a web application.

Each option should feel meaningfully different — vary the mood, color temperature, and typography personality.

Respond with ONLY valid JSON (no markdown, no code fences) matching this exact schema:

{
  "options": [
    {
      "label": "Theme Name",
      "vibe": "One-line description of the visual feel",
      "colors": {
        "primitive": {
          "color-name-1": "#hex1",
          "color-name-2": "#hex2",
          "color-name-3": "#hex3",
          "color-name-4": "#hex4",
          "color-name-5": "#hex5"
        },
        "semantic": {
          "background-primary": "color-name-X",
          "text-primary": "color-name-Y",
          "cta-primary": "color-name-Z",
          "error": "#hex-for-error"
        }
      },
      "fonts": {
        "display": "Google Font Family Name",
        "body": "Google Font Family Name"
      },
      "brand": {
        "tone": "tone-descriptor",
        "illustrationDirection": "style-keyword",
        "illustrationDescription": "Brief description of illustration approach",
        "motionFeel": "snappy|smooth|bouncy|subtle"
      },
      "components": {
        "button": {
          "primary": { "bg": "semantic-or-primitive-name", "text": "semantic-or-primitive-name", "radius": "border-radius-key", "padding_x": 24, "padding_y": 12, "min_height": 44 },
          "secondary": { "bg": "transparent", "text": "semantic-or-primitive-name", "border_color": "primitive-name", "border_width": 1, "radius": "border-radius-key" },
          "ghost": { "bg": "transparent", "text": "semantic-or-primitive-name", "radius": "border-radius-key" }
        },
        "card": {
          "default": { "bg": "semantic-or-primitive-name", "border_color": "primitive-name", "border_width": 1, "border_style": "solid", "radius": "border-radius-key", "padding": 24 },
          "highlighted": { "bg": "primitive-name", "border_color": "semantic-or-primitive-name", "border_width": 2, "border_style": "solid", "radius": "border-radius-key", "padding": 24 }
        },
        "input": {
          "default": { "bg": "semantic-or-primitive-name", "text": "semantic-or-primitive-name", "border_color": "primitive-name", "radius": "border-radius-key", "padding_x": 16, "padding_y": 12, "min_height": 44 },
          "focus": { "border_color": "semantic-or-primitive-name", "border_width": 2 },
          "error": { "border_color": "error", "border_width": 2 }
        },
        "tab_bar": {
          "active": { "bg": "semantic-or-primitive-name", "text": "semantic-or-primitive-name", "radius": "pill" },
          "inactive": { "bg": "transparent", "text": "semantic-or-primitive-name" }
        },
        "badge": {
          "success": { "bg": "primitive-name", "text": "semantic-or-primitive-name", "radius": "pill" },
          "warning": { "bg": "primitive-name", "text": "semantic-or-primitive-name", "radius": "pill" },
          "error": { "bg": "error", "text": "semantic-or-primitive-name", "radius": "pill" },
          "info": { "bg": "semantic-or-primitive-name", "text": "semantic-or-primitive-name", "radius": "pill" }
        },
        "avatar": {
          "default": { "size": 40, "border_radius": "pill", "border_color": "primitive-name", "border_width": 2 }
        },
        "progress_bar": {
          "track": { "bg": "primitive-name", "radius": "pill", "height": 8 },
          "fill": { "bg": "semantic-or-primitive-name", "radius": "pill" }
        }
      }
    }
  ]
}

Rules:
- Exactly 5 primitive colors per option, using kebab-case names
- Semantic values reference primitive color names (except error which can be a direct hex)
- Use real Google Fonts that pair well
- Ensure sufficient contrast between background-primary and text-primary (WCAG AA)
- Each option should have a distinct personality
- The components section must define token bindings for: button (primary, secondary, ghost), card (default, highlighted), input (default, focus, error), tab_bar (active, inactive), badge (success, warning, error, info), avatar, progress_bar. All color values must reference your primitive or semantic token names — never raw hex.`;
}

/** Build the user prompt with app context. */
function buildUserPrompt(context: {
  appName: string;
  description: string;
  targetAudience: string;
  prdContent?: string;
}): string {
  const appContext = context.prdContent
    ? `- App name: ${context.appName}\n\nPRD:\n${context.prdContent}`
    : `- App name: ${context.appName}\n- Description: ${context.description || 'A web application'}\n- Target audience: ${context.targetAudience || 'general'}`;

  return `Generate 3 design system options for:\n${appContext}`;
}

/** Parse and validate LLM response into DesignOption array. */
export function parseLLMResponse(raw: string): DesignOption[] {
  // Strip markdown code fences if present
  const cleaned = raw.replace(/^```(?:json)?\s*/m, '').replace(/\s*```\s*$/m, '').trim();
  const parsed = JSON.parse(cleaned) as { options: DesignOption[] };

  if (!Array.isArray(parsed.options)) {
    throw new Error('Response missing "options" array');
  }

  return parsed.options.filter((opt) => {
    if (!opt.label || !opt.vibe) return false;
    if (!opt.colors?.primitive || !opt.colors?.semantic) return false;
    if (Object.keys(opt.colors.primitive).length < 5) return false;
    if (!opt.colors.semantic['background-primary'] || !opt.colors.semantic['text-primary']) return false;
    if (!opt.colors.semantic['cta-primary'] || !opt.colors.semantic.error) return false;
    if (!opt.fonts?.display || !opt.fonts?.body) return false;
    if (!opt.brand?.tone) return false;
    return true;
  });
}

/** Convert a DesignOption to DesignTokensSpec. */
export function optionToTokens(option: DesignOption): DesignTokensSpec {
  return {
    version: '1.0',
    created_by: 'agentforge-init-llm',
    colors: {
      primitive: option.colors.primitive,
      semantic: option.colors.semantic,
    },
    typography: {
      font_families: { display: option.fonts.display, body: option.fonts.body },
      scale: [...FIXED_TYPOGRAPHY_SCALE],
    },
    spacing: SHARED_LAYOUT.spacing,
    borders: SHARED_LAYOUT.borders,
    touch_targets: SHARED_LAYOUT.touch_targets,
    ...(option.components ? { components: option.components } : {}),
  };
}

/** Convert a DesignOption to BrandSpec. */
export function optionToBrand(option: DesignOption, audience: string): BrandSpec {
  return {
    version: '1.0',
    created_by: 'agentforge-init-llm',
    identity: {
      tone: option.brand.tone,
      audience: audience || 'general',
    },
    illustration_style: {
      direction: option.brand.illustrationDirection || 'minimal',
      description: option.brand.illustrationDescription || 'Clean illustrations with accent color highlights',
    },
    motion_principles: {
      page_transitions: 'fade',
      interaction_feel: option.brand.motionFeel || 'snappy',
      easing: 'ease-out',
      duration_base_ms: 200,
    },
    accessibility: {
      wcag_level: 'AA',
    },
  };
}

/** Build the 3 fallback options from existing archetypes. */
function buildFallbackOptions(): DesignOption[] {
  const archetypes: { key: DesignArchetype; label: string; vibe: string }[] = [
    { key: 'warm', label: 'Warm & Inviting', vibe: 'Cream, teal, rounded, friendly — approachable and playful' },
    { key: 'professional', label: 'Clean & Professional', vibe: 'White, slate, blue accent — structured and trustworthy' },
    { key: 'bold', label: 'Bold & Modern', vibe: 'Dark, violet, lime — geometric and cutting-edge' },
  ];

  return archetypes.map(({ key, label, vibe }) => {
    const tokens = buildDesignTokensSpec(key);
    const semantic = tokens.colors.semantic as unknown as DesignOption['colors']['semantic'];
    return {
      label,
      vibe,
      colors: { primitive: tokens.colors.primitive as Record<string, string>, semantic },
      fonts: tokens.typography.font_families as { display: string; body: string },
      brand: {
        tone: key === 'warm' ? 'playful-warm' : key === 'professional' ? 'professional-clean' : 'bold-modern',
        illustrationDirection: 'minimal',
        illustrationDescription: 'Clean illustrations with accent color highlights',
        motionFeel: 'snappy',
      },
    };
  });
}

/** Resolve a semantic color to its hex value. */
function resolveColor(semantic: string, primitive: Record<string, string>): string {
  // If semantic value starts with #, it's already a hex
  if (semantic.startsWith('#')) return semantic;
  return primitive[semantic] ?? '#888888';
}

/** Generate the self-contained HTML preview for 3 options. */
export function generatePreviewHtml(
  appName: string,
  options: DesignOption[],
): string {
  const fontFamilies = options
    .flatMap((o) => [o.fonts.display, o.fonts.body])
    .filter((f, i, arr) => arr.indexOf(f) === i)
    .map((f) => f.replace(/\s+/g, '+'))
    .join('&family=');

  const themeCssVars = options.map((opt, i) => {
    const bg = resolveColor(opt.colors.semantic['background-primary'], opt.colors.primitive);
    const text = resolveColor(opt.colors.semantic['text-primary'], opt.colors.primitive);
    const cta = resolveColor(opt.colors.semantic['cta-primary'], opt.colors.primitive);
    const error = resolveColor(opt.colors.semantic.error, opt.colors.primitive);
    const primitiveVals = Object.values(opt.colors.primitive);
    const surface = primitiveVals[3] ?? '#f5f5f5';
    const muted = primitiveVals[4] ?? '#e0e0e0';
    return `
    [data-theme="${i + 1}"] {
      --bg-primary: ${bg};
      --text-primary: ${text};
      --cta-primary: ${cta};
      --error: ${error};
      --surface: ${surface};
      --muted: ${muted};
      --font-display: '${opt.fonts.display}', sans-serif;
      --font-body: '${opt.fonts.body}', sans-serif;
    }`;
  }).join('\n');

  const tabs = options.map((opt, i) => {
    const active = i === 0 ? ' active' : '';
    return `<button class="tab${active}" onclick="switchTab(${i + 1})" data-tab="${i + 1}">${opt.label}</button>`;
  }).join('\n          ');

  const panels = options.map((opt, i) => {
    const display = i === 0 ? 'block' : 'none';
    const primitiveEntries = Object.entries(opt.colors.primitive);
    const bg = resolveColor(opt.colors.semantic['background-primary'], opt.colors.primitive);
    const text = resolveColor(opt.colors.semantic['text-primary'], opt.colors.primitive);
    const cta = resolveColor(opt.colors.semantic['cta-primary'], opt.colors.primitive);
    const errorHex = resolveColor(opt.colors.semantic.error, opt.colors.primitive);
    const surface = Object.values(opt.colors.primitive)[3] ?? '#f5f5f5';

    return `
      <div class="panel" id="panel-${i + 1}" style="display:${display}" data-theme="${i + 1}">
        <!-- Section 1: Theme Identity -->
        <div class="section">
          <h2 style="font-family:var(--font-display);color:var(--text-primary);font-size:28px;font-weight:700;margin:0 0 8px">${opt.label}</h2>
          <p style="font-family:var(--font-body);color:var(--text-primary);opacity:0.7;font-size:16px;margin:0 0 12px">${opt.vibe}</p>
          <span class="badge" style="background:var(--cta-primary);color:${isLight(cta) ? '#111' : '#fff'};padding:4px 12px;border-radius:9999px;font-size:12px;font-family:var(--font-body)">${opt.brand.tone}</span>
        </div>

        <!-- Section 2: Color Palette -->
        <div class="section">
          <h3 class="section-title">Color Palette</h3>
          <div class="swatch-strip">
            ${primitiveEntries.map(([, hex]) => `<div class="swatch-segment" style="background:${hex}"></div>`).join('')}
          </div>
          <div class="swatch-labels">
            ${primitiveEntries.map(([name, hex]) => `
              <div class="swatch-label-item">
                <div class="swatch-label">${name}</div>
                <div class="swatch-hex">${hex}</div>
              </div>
            `).join('')}
          </div>
          <div class="semantic-row" style="margin-top:16px">
            <div class="semantic-chip" style="background:${bg};color:${text};border:1px solid #ddd">Background</div>
            <div class="semantic-chip" style="background:${text};color:${bg}">Text</div>
            <div class="semantic-chip" style="background:${cta};color:${isLight(cta) ? '#111' : '#fff'}">CTA</div>
            <div class="semantic-chip" style="background:${errorHex};color:#fff">Error</div>
          </div>
        </div>

        <!-- Section 3: Typography Scale -->
        <div class="section">
          <h3 class="section-title">Typography Scale</h3>
          <div class="type-ladder">
            <div class="type-row"><span style="font-family:var(--font-display);font-size:32px;font-weight:700;color:var(--text-primary)">Heading 1</span><span class="type-meta">32px / 700 / ${opt.fonts.display}</span></div>
            <div class="type-row"><span style="font-family:var(--font-display);font-size:24px;font-weight:700;color:var(--text-primary)">Heading 2</span><span class="type-meta">24px / 700 / ${opt.fonts.display}</span></div>
            <div class="type-row"><span style="font-family:var(--font-display);font-size:18px;font-weight:600;color:var(--text-primary)">Heading 3</span><span class="type-meta">18px / 600 / ${opt.fonts.display}</span></div>
            <div class="type-row"><span style="font-family:var(--font-body);font-size:14px;font-weight:400;color:var(--text-primary)">Body text — The quick brown fox jumps over the lazy dog</span><span class="type-meta">14px / 400 / ${opt.fonts.body}</span></div>
            <div class="type-row"><span style="font-family:var(--font-body);font-size:12px;font-weight:500;color:var(--text-primary)">Label text</span><span class="type-meta">12px / 500 / ${opt.fonts.body}</span></div>
            <div class="type-row"><span style="font-family:var(--font-body);font-size:11px;font-weight:400;color:var(--text-primary);opacity:0.7">Small / caption text</span><span class="type-meta">11px / 400 / ${opt.fonts.body}</span></div>
          </div>
          <div class="font-pairing" style="margin-top:24px;padding:24px;background:var(--bg-primary);border-radius:12px;border:1px solid #e0e0e0">
            <h4 style="font-family:var(--font-display);font-size:24px;font-weight:700;color:var(--text-primary);margin:0 0 8px">Font Pairing Demo</h4>
            <p style="font-family:var(--font-body);font-size:14px;color:var(--text-primary);line-height:1.6;margin:0">This paragraph demonstrates how ${opt.fonts.display} (display) and ${opt.fonts.body} (body) work together. Good font pairing creates visual hierarchy while maintaining readability across all screen sizes.</p>
          </div>
        </div>

        <!-- Section 4: Component Kitchen Sink -->
        <div class="section">
          <h3 class="section-title">Components</h3>
          <div class="component-row">
            <button class="demo-btn" style="background:var(--cta-primary);color:${isLight(cta) ? '#111' : '#fff'};border:none;padding:10px 24px;border-radius:8px;font-family:var(--font-body);font-size:14px;font-weight:500;cursor:pointer">Primary</button>
            <button class="demo-btn" style="background:transparent;color:var(--cta-primary);border:2px solid var(--cta-primary);padding:8px 22px;border-radius:8px;font-family:var(--font-body);font-size:14px;font-weight:500;cursor:pointer">Secondary</button>
            <button class="demo-btn" style="background:#ccc;color:#888;border:none;padding:10px 24px;border-radius:8px;font-family:var(--font-body);font-size:14px;font-weight:500;cursor:not-allowed" disabled>Disabled</button>
          </div>
          <div class="form-group" style="margin-top:20px;max-width:360px">
            <label style="font-family:var(--font-body);font-size:12px;font-weight:500;color:var(--text-primary);display:block;margin-bottom:4px">Email Address</label>
            <input type="text" value="user@example.com" style="width:100%;padding:10px 12px;border:1px solid #d0d0d0;border-radius:8px;font-family:var(--font-body);font-size:14px;color:var(--text-primary);box-sizing:border-box" readonly>
            <span style="font-family:var(--font-body);font-size:11px;color:var(--text-primary);opacity:0.5;margin-top:4px;display:block">We'll never share your email</span>
          </div>
          <div class="alerts-row" style="margin-top:20px;display:flex;gap:8px;flex-wrap:wrap">
            <span class="alert-badge" style="background:#dcfce7;color:#166534;padding:4px 12px;border-radius:8px;font-size:12px;font-family:var(--font-body)">Success</span>
            <span class="alert-badge" style="background:#fef9c3;color:#854d0e;padding:4px 12px;border-radius:8px;font-size:12px;font-family:var(--font-body)">Warning</span>
            <span class="alert-badge" style="background:#fecaca;color:#991b1b;padding:4px 12px;border-radius:8px;font-size:12px;font-family:var(--font-body)">Error</span>
            <span class="alert-badge" style="background:#dbeafe;color:#1e40af;padding:4px 12px;border-radius:8px;font-size:12px;font-family:var(--font-body)">Info</span>
          </div>
        </div>

        <!-- Section 5: Mini Dashboard Demo -->
        <div class="section">
          <h3 class="section-title">Dashboard Preview</h3>
          <div class="dashboard-demo" style="border:1px solid #e0e0e0;border-radius:16px;overflow:hidden;display:grid;grid-template-columns:200px 1fr;min-height:400px">
            <!-- Sidebar -->
            <div class="dash-sidebar" style="background:${text};padding:24px 16px;display:flex;flex-direction:column;gap:4px">
              <div style="font-family:var(--font-display);font-size:16px;font-weight:700;color:${bg};margin-bottom:16px">${appName || 'App'}</div>
              <div class="nav-item active-nav" style="color:${bg};font-family:var(--font-body);font-size:13px;padding:8px 12px;border-radius:8px;background:rgba(255,255,255,0.1)">Dashboard</div>
              <div class="nav-item" style="color:${bg};opacity:0.6;font-family:var(--font-body);font-size:13px;padding:8px 12px;border-radius:8px">Analytics</div>
              <div class="nav-item" style="color:${bg};opacity:0.6;font-family:var(--font-body);font-size:13px;padding:8px 12px;border-radius:8px">Settings</div>
              <div class="nav-item" style="color:${bg};opacity:0.6;font-family:var(--font-body);font-size:13px;padding:8px 12px;border-radius:8px">Users</div>
            </div>
            <!-- Main content -->
            <div class="dash-main" style="background:${bg};padding:24px">
              <!-- Stat cards -->
              <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:24px">
                <div class="stat-card" style="background:${surface};padding:20px;border-radius:12px">
                  <div style="font-family:var(--font-body);font-size:12px;font-weight:500;color:${text};opacity:0.6;margin-bottom:4px">Total Users</div>
                  <div style="font-family:var(--font-display);font-size:28px;font-weight:700;color:${text}">12,847</div>
                  <div style="font-family:var(--font-body);font-size:11px;color:#16a34a;margin-top:4px">+12.5%</div>
                </div>
                <div class="stat-card" style="background:${surface};padding:20px;border-radius:12px">
                  <div style="font-family:var(--font-body);font-size:12px;font-weight:500;color:${text};opacity:0.6;margin-bottom:4px">Revenue</div>
                  <div style="font-family:var(--font-display);font-size:28px;font-weight:700;color:${text}">$48.2K</div>
                  <div style="font-family:var(--font-body);font-size:11px;color:#16a34a;margin-top:4px">+8.1%</div>
                </div>
                <div class="stat-card" style="background:${surface};padding:20px;border-radius:12px">
                  <div style="font-family:var(--font-body);font-size:12px;font-weight:500;color:${text};opacity:0.6;margin-bottom:4px">Active Now</div>
                  <div style="font-family:var(--font-display);font-size:28px;font-weight:700;color:${text}">342</div>
                  <div style="font-family:var(--font-body);font-size:11px;color:${errorHex};margin-top:4px">-2.3%</div>
                </div>
              </div>
              <!-- Data table -->
              <div style="background:${surface};border-radius:12px;overflow:hidden">
                <table style="width:100%;border-collapse:collapse;font-family:var(--font-body);font-size:13px">
                  <thead>
                    <tr style="border-bottom:1px solid #e0e0e0">
                      <th style="text-align:left;padding:12px 16px;color:${text};opacity:0.6;font-weight:500;font-size:11px">Name</th>
                      <th style="text-align:left;padding:12px 16px;color:${text};opacity:0.6;font-weight:500;font-size:11px">Status</th>
                      <th style="text-align:right;padding:12px 16px;color:${text};opacity:0.6;font-weight:500;font-size:11px">Amount</th>
                      <th style="text-align:right;padding:12px 16px;color:${text};opacity:0.6;font-weight:500;font-size:11px">Date</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr style="border-bottom:1px solid #f0f0f0">
                      <td style="padding:12px 16px;color:${text}">Sarah Johnson</td>
                      <td style="padding:12px 16px"><span style="background:#dcfce7;color:#166534;padding:2px 8px;border-radius:9999px;font-size:11px">Active</span></td>
                      <td style="padding:12px 16px;text-align:right;color:${text}">$2,450</td>
                      <td style="padding:12px 16px;text-align:right;color:${text};opacity:0.6">Mar 15</td>
                    </tr>
                    <tr style="background:${bg};border-bottom:1px solid #f0f0f0">
                      <td style="padding:12px 16px;color:${text}">Alex Chen</td>
                      <td style="padding:12px 16px"><span style="background:#fef9c3;color:#854d0e;padding:2px 8px;border-radius:9999px;font-size:11px">Pending</span></td>
                      <td style="padding:12px 16px;text-align:right;color:${text}">$1,870</td>
                      <td style="padding:12px 16px;text-align:right;color:${text};opacity:0.6">Mar 14</td>
                    </tr>
                    <tr style="border-bottom:1px solid #f0f0f0">
                      <td style="padding:12px 16px;color:${text}">Maria Garcia</td>
                      <td style="padding:12px 16px"><span style="background:#dcfce7;color:#166534;padding:2px 8px;border-radius:9999px;font-size:11px">Active</span></td>
                      <td style="padding:12px 16px;text-align:right;color:${text}">$3,200</td>
                      <td style="padding:12px 16px;text-align:right;color:${text};opacity:0.6">Mar 13</td>
                    </tr>
                    <tr>
                      <td style="padding:12px 16px;color:${text}">James Wilson</td>
                      <td style="padding:12px 16px"><span style="background:#fecaca;color:#991b1b;padding:2px 8px;border-radius:9999px;font-size:11px">Inactive</span></td>
                      <td style="padding:12px 16px;text-align:right;color:${text}">$950</td>
                      <td style="padding:12px 16px;text-align:right;color:${text};opacity:0.6">Mar 12</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>`;
  }).join('\n');

  const compareStrip = options.map((opt, i) => {
    const dots = Object.values(opt.colors.primitive)
      .map((hex) => `<span class="dot" style="background:${hex}"></span>`)
      .join('');
    return `
          <div class="compare-item" onclick="switchTab(${i + 1})" style="cursor:pointer">
            <div class="compare-label">${opt.label}</div>
            <div class="compare-dots">${dots}</div>
            <div class="compare-fonts">${opt.fonts.display} / ${opt.fonts.body}</div>
            <div class="compare-tone">${opt.brand.tone}</div>
          </div>`;
  }).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Design System Preview — ${appName || 'Your App'}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=${fontFamilies}&display=swap" rel="stylesheet">
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f8f9fa; color: #333; min-width: 1024px; }
    .header { text-align: center; padding: 40px 24px 24px; }
    .header h1 { font-size: 28px; font-weight: 700; margin-bottom: 8px; }
    .header p { font-size: 16px; color: #666; }
    .tabs { display: flex; gap: 8px; justify-content: center; padding: 0 24px 24px; }
    .tab { padding: 10px 28px; border-radius: 9999px; border: 2px solid #ddd; background: #fff; font-size: 14px; font-weight: 500; cursor: pointer; transition: all .2s; }
    .tab.active { background: #111; color: #fff; border-color: #111; }
    .tab:hover:not(.active) { border-color: #999; }
    .content { max-width: 1200px; margin: 0 auto; padding: 0 24px; }
    .section { margin-bottom: 32px; padding: 24px; background: #fff; border-radius: 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.06); }
    .section-title { font-size: 16px; font-weight: 600; margin-bottom: 16px; color: #555; }
    .swatch-strip { display: flex; border-radius: 10px; overflow: hidden; height: 56px; }
    .swatch-segment { flex: 1; }
    .swatch-labels { display: flex; margin-top: 8px; }
    .swatch-label-item { flex: 1; text-align: center; }
    .swatch-label { font-size: 11px; font-weight: 500; color: #555; }
    .swatch-hex { font-size: 10px; color: #999; font-family: monospace; }
    .semantic-row { display: flex; gap: 8px; flex-wrap: wrap; }
    .semantic-chip { padding: 8px 16px; border-radius: 8px; font-size: 12px; font-weight: 500; }
    .type-ladder { display: flex; flex-direction: column; gap: 12px; }
    .type-row { display: flex; align-items: baseline; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #f0f0f0; }
    .type-meta { font-size: 11px; color: #999; font-family: monospace; white-space: nowrap; margin-left: 16px; }
    .component-row { display: flex; gap: 12px; align-items: center; margin-bottom: 12px; }
    .compare-strip { max-width: 1200px; margin: 24px auto; padding: 20px 24px; background: #fff; border-radius: 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.06); display: grid; grid-template-columns: repeat(${options.length}, 1fr); gap: 24px; }
    .compare-item { text-align: center; padding: 16px; border-radius: 12px; transition: background .2s; }
    .compare-item:hover { background: #f5f5f5; }
    .compare-label { font-size: 14px; font-weight: 600; margin-bottom: 8px; }
    .compare-dots { display: flex; gap: 6px; justify-content: center; margin-bottom: 8px; }
    .dot { width: 20px; height: 20px; border-radius: 50%; border: 1px solid #ddd; display: inline-block; }
    .compare-fonts { font-size: 11px; color: #888; margin-bottom: 4px; }
    .compare-tone { font-size: 11px; color: #aaa; font-style: italic; }
    .footer { text-align: center; padding: 32px; color: #888; font-size: 14px; }
    .footer strong { color: #333; }
${themeCssVars}
  </style>
</head>
<body>
  <div class="header">
    <h1>Design System Preview — ${appName || 'Your App'}</h1>
    <p>Choose the design direction for your app</p>
  </div>

  <div class="tabs">
    ${tabs}
  </div>

  <div class="content">
    ${panels}
  </div>

  <div class="compare-strip">
    ${compareStrip}
  </div>

  <div class="footer">
    Return to your terminal and type ${options.map((_, i) => `<strong>${i + 1}</strong>`).join(', ')}
  </div>

  <script>
    function switchTab(n) {
      document.querySelectorAll('.tab').forEach(t => t.classList.toggle('active', t.dataset.tab == n));
      document.querySelectorAll('.panel').forEach(p => p.style.display = p.id === 'panel-' + n ? 'block' : 'none');
    }
  </script>
</body>
</html>`;
}

/** Check if a hex color is light (for choosing contrast text). */
function isLight(hex: string): boolean {
  const c = hex.replace('#', '');
  const r = parseInt(c.substring(0, 2), 16);
  const g = parseInt(c.substring(2, 4), 16);
  const b = parseInt(c.substring(4, 6), 16);
  return (r * 299 + g * 587 + b * 114) / 1000 > 128;
}

/** Open a URL in the default browser. */
export function openInBrowser(url: string): Promise<boolean> {
  return new Promise((resolve) => {
    const cmd = process.platform === 'darwin' ? 'open'
      : process.platform === 'win32' ? 'start'
      : 'xdg-open';
    exec(`${cmd} "${url}"`, (err) => {
      resolve(!err);
    });
  });
}

/** Print a CLI summary table when browser can't open. */
function printCliSummary(
  options: DesignOption[],
  output: NodeJS.WritableStream,
): void {
  options.forEach((opt, i) => {
    const colors = Object.values(opt.colors.primitive).join(', ');
    output.write(infoMsg(`\n  Option ${i + 1}: ${opt.label}\n`));
    output.write(infoMsg(`    ${opt.vibe}\n`));
    output.write(infoMsg(`    Colors: ${colors}\n`));
    output.write(infoMsg(`    Fonts: ${opt.fonts.display} + ${opt.fonts.body}\n`));
    output.write(infoMsg(`    Tone: ${opt.brand.tone}\n`));
  });
}

/** Prompt for a single line using a short-lived readline. */
export function promptOnce(
  input: NodeJS.ReadableStream,
  output: NodeJS.WritableStream,
  question: string,
): Promise<string> {
  const rl = readline.createInterface({ input, output, terminal: false });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

/** Options for customizing generateDesignOptions behavior (e.g. in tests). */
export interface GenerateDesignOptionsConfig {
  /** Override browser opener. Return true if browser opened. */
  readonly openBrowser?: (url: string) => Promise<boolean>;
}

/**
 * Generate 3 design system options (LLM or fallback), show preview, let user pick.
 */
export async function generateDesignOptions(
  context: { appName: string; description: string; targetAudience: string; prdContent?: string },
  input?: NodeJS.ReadableStream,
  output?: NodeJS.WritableStream,
  config?: GenerateDesignOptionsConfig,
): Promise<GenerateDesignResult> {
  const out = output ?? process.stdout;
  const inp = input ?? process.stdin;

  let options: DesignOption[];
  let source: 'llm' | 'fallback' = 'fallback';

  // Try LLM generation
  const apiKey = process.env['ANTHROPIC_API_KEY'];
  if (apiKey) {
    out.write(infoMsg('\nGenerating design options with AI...\n'));
    const llmOptions = await tryLLMGeneration(apiKey, context, out);
    if (llmOptions) {
      options = llmOptions;
      source = 'llm';
    } else {
      options = buildFallbackOptions();
    }
  } else {
    options = buildFallbackOptions();
  }

  // Generate HTML preview and open in browser
  const html = generatePreviewHtml(context.appName, options);
  const tmpFile = path.join(os.tmpdir(), `agentforge-design-preview-${Date.now()}.html`);
  fs.writeFileSync(tmpFile, html, 'utf-8');

  const browserFn = config?.openBrowser ?? openInBrowser;
  const browserOpened = await browserFn(`file://${tmpFile}`);
  if (browserOpened) {
    out.write(infoMsg('\nDesign preview opened in your browser.\n'));
  } else {
    out.write(warnMsg('\nCould not open browser. Here are the options:\n'));
    printCliSummary(options, out);
  }

  // Prompt user to choose — read directly from stream to avoid readline buffering
  // issues that consume data intended for subsequent readline consumers
  let choice: number | undefined;

  while (choice === undefined) {
    const answer = await promptOnce(inp, out, '\nChoose 1, 2, or 3 (or \'r\' to regenerate): ');

    if (answer === 'r' && apiKey) {
      out.write(infoMsg('Regenerating...\n'));
      const llmOptions = await tryLLMGeneration(apiKey, context, out);
      if (llmOptions) {
        options = llmOptions;
        source = 'llm';
        const newHtml = generatePreviewHtml(context.appName, options);
        fs.writeFileSync(tmpFile, newHtml, 'utf-8');
        const opened = await browserFn(`file://${tmpFile}`);
        if (!opened) {
          printCliSummary(options, out);
        } else {
          out.write(infoMsg('Preview refreshed in browser.\n'));
        }
      } else {
        out.write(warnMsg('Regeneration failed. Keeping current options.\n'));
      }
      continue;
    }

    const num = parseInt(answer, 10);
    if (num >= 1 && num <= options.length) {
      choice = num;
    } else {
      out.write(warnMsg('Please enter 1, 2, or 3.\n'));
    }
  }

  // Clean up temp file
  try {
    fs.unlinkSync(tmpFile);
  } catch {
    // ignore cleanup errors
  }

  const selected = options[choice - 1];
  const tokens = optionToTokens(selected);
  const brand = optionToBrand(selected, context.targetAudience);

  return { tokens, brand, source };
}

/** Attempt LLM generation, return null on failure. */
async function tryLLMGeneration(
  apiKey: string,
  context: { appName: string; description: string; targetAudience: string; prdContent?: string },
  output: NodeJS.WritableStream,
): Promise<DesignOption[] | null> {
  let provider: LLMProvider;
  try {
    provider = createClaudeProvider('claude-sonnet-4', { apiKey });
  } catch {
    output.write(warnMsg('Failed to create LLM provider, using defaults.\n'));
    return null;
  }

  const systemPrompt = buildSystemPrompt();
  const userPrompt = buildUserPrompt(context);

  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const result = await provider.complete(
        {
          system: systemPrompt,
          messages: [
            { role: 'user', content: userPrompt },
            ...(attempt > 0
              ? [{ role: 'user' as const, content: 'Your previous response was not valid JSON. Please respond with ONLY the JSON object, no markdown.' }]
              : []),
          ],
        },
        { model: 'claude-sonnet-4', maxTokens: 4096, temperature: 0.8 },
      );

      if (!result.ok) {
        output.write(warnMsg(`LLM request failed: ${JSON.stringify(result.error)}\n`));
        return null;
      }

      const options = parseLLMResponse(result.value.content);
      if (options.length < 2) {
        if (attempt === 0) continue; // retry
        output.write(warnMsg('LLM returned insufficient valid options, using defaults.\n'));
        return null;
      }

      // Validate each option by converting to tokens/brand
      const validOptions = options.filter((opt) => {
        const tokens = optionToTokens(opt);
        const brand = optionToBrand(opt, context.targetAudience);
        const tokensValid = validateDesignTokens(tokens);
        const brandValid = validateBrandSpec(brand);
        return tokensValid.ok && brandValid.ok;
      });

      if (validOptions.length < 2) {
        if (attempt === 0) continue;
        output.write(warnMsg('LLM options failed validation, using defaults.\n'));
        return null;
      }

      return validOptions.slice(0, 3);
    } catch (err) {
      if (attempt === 0) continue;
      output.write(warnMsg(`LLM error: ${err instanceof Error ? err.message : String(err)}\n`));
      return null;
    }
  }

  return null;
}
