/**
 * Render-and-compare test: renders generated DesignSpec V2 JSON files
 * using the browser renderer (real shadcn components), takes screenshots,
 * and compares against screenshots of the actual running app.
 *
 * This validates that the source→DesignSpec pipeline produces specs
 * that render to something visually recognizable.
 *
 * Requires: generated spec files from import-integration.test.ts
 * Requires: brownfield app running on localhost:3001 (or captures will be skipped)
 */

import { join } from 'node:path';
import { readFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import {
  screenshotDesignSpec,
} from '@agentforge/designspec-renderer';
import { V2_BUILTIN_CATALOG } from '../../../designspec-renderer/src/__fixtures__/catalog-entries.js';
import type { DesignSpecV2, RendererTokens } from '@agentforge/designspec-renderer';

const MONOREPO_ROOT = join(__dirname, '..', '..', '..', '..');
const BROWNFIELD_APP = join(MONOREPO_ROOT, 'agentforge-brownfield-app');
const IMPORT_DIR = join(BROWNFIELD_APP, '.agentforge', 'import');
const SCREENSHOT_DIR = join(IMPORT_DIR, 'screenshots');

/**
 * Build minimal RendererTokens from the brownfield app's CSS variables.
 * Maps the teal/coral oklch theme to hex approximations for the renderer.
 */
function buildRendererTokens(): RendererTokens {
  return {
    colors: {
      primitive: {
        'teal-600': '#0d9488',
        'teal-500': '#14b8a6',
        'teal-100': '#ccfbf1',
        'teal-50': '#f0fdfa',
        'coral-500': '#f97316',
        'coral-400': '#fb923c',
        'coral-50': '#fff7ed',
        'white': '#ffffff',
        'gray-950': '#0a0a0a',
        'gray-700': '#404040',
        'gray-500': '#737373',
        'gray-200': '#e5e5e5',
        'gray-100': '#f5f5f5',
        'gray-50': '#fafafa',
        'red-500': '#ef4444',
        'red-50': '#fef2f2',
      },
      semantic: {
        'background-primary': 'gray-50',
        'surface-primary': 'white',
        'surface-secondary': 'gray-100',
        'surface-elevated': 'gray-100',
        'surface-input': 'white',
        'text-primary': 'gray-950',
        'text-secondary': 'gray-500',
        'text-on-cta': 'white',
        'cta-primary': 'teal-600',
        'cta-hover': 'teal-500',
        'border-default': 'gray-200',
        'divider': 'gray-200',
        'error': 'red-500',
        'success': 'teal-500',
        'warning': 'coral-500',
        'info': 'teal-100',
      },
    },
    typography: {
      font_families: {
        display: 'Geist',
        body: 'Geist',
      },
      scale: [
        { role: 'heading-1', size: 30, weight: 700, family: 'display' },
        { role: 'heading-2', size: 24, weight: 700, family: 'display' },
        { role: 'heading-3', size: 18, weight: 600, family: 'display' },
        { role: 'body', size: 14, weight: 400, family: 'body' },
        { role: 'label', size: 14, weight: 500, family: 'body' },
        { role: 'small', size: 12, weight: 400, family: 'body' },
      ],
    },
    spacing: {
      unit: 4,
      scale: [4, 8, 12, 16, 24, 32, 48, 64],
    },
    borders: {
      radius: {
        small: 6,
        medium: 8,
        large: 10,
        pill: 9999,
      },
    },
    elevation: {
      levels: [
        { level: 0, shadow: 'none', description: 'Flat' },
        { level: 1, shadow: '0 1px 3px rgba(0,0,0,0.1)', description: 'Subtle' },
        { level: 2, shadow: '0 4px 6px rgba(0,0,0,0.1)', description: 'Card' },
        { level: 3, shadow: '0 10px 15px rgba(0,0,0,0.1)', description: 'Modal' },
      ],
    },
  };
}

function loadSpec(name: string): DesignSpecV2 | null {
  const specPath = join(IMPORT_DIR, `${name}-spec.json`);
  if (!existsSync(specPath)) return null;
  return JSON.parse(readFileSync(specPath, 'utf-8')) as DesignSpecV2;
}

// Check if specs exist (generated by import-integration.test.ts)
const HAS_SPECS = existsSync(join(IMPORT_DIR, 'dashboard-spec.json'));

const describeWithSpecs = HAS_SPECS ? describe : describe.skip;

describeWithSpecs('Render & Compare — DesignSpec V2 screenshots', () => {
  jest.setTimeout(60_000);

  const tokens = buildRendererTokens();

  beforeAll(() => {
    if (!existsSync(SCREENSHOT_DIR)) mkdirSync(SCREENSHOT_DIR, { recursive: true });
  });

  it('renders dashboard spec to a screenshot', async () => {
    const spec = loadSpec('dashboard');
    expect(spec).not.toBeNull();

    const { screenshot, html } = await screenshotDesignSpec(
      spec!,
      tokens,
      V2_BUILTIN_CATALOG,
      { width: 1440, outputPath: join(SCREENSHOT_DIR, 'dashboard-rendered.png') },
    );

    expect(screenshot.length).toBeGreaterThan(1000); // Non-trivial PNG
    expect(html.length).toBeGreaterThan(100);

    // Save HTML for debugging
    writeFileSync(join(SCREENSHOT_DIR, 'dashboard-rendered.html'), html);

    console.log(`Dashboard rendered: ${(screenshot.length / 1024).toFixed(0)}KB PNG, ${(html.length / 1024).toFixed(0)}KB HTML`);
  });

  it('renders settings spec to a screenshot', async () => {
    const spec = loadSpec('settings');
    expect(spec).not.toBeNull();

    const { screenshot, html } = await screenshotDesignSpec(
      spec!,
      tokens,
      V2_BUILTIN_CATALOG,
      { width: 1440, outputPath: join(SCREENSHOT_DIR, 'settings-rendered.png') },
    );

    expect(screenshot.length).toBeGreaterThan(1000);
    writeFileSync(join(SCREENSHOT_DIR, 'settings-rendered.html'), html);
    console.log(`Settings rendered: ${(screenshot.length / 1024).toFixed(0)}KB PNG, ${(html.length / 1024).toFixed(0)}KB HTML`);
  });

  it('renders users spec to a screenshot', async () => {
    const spec = loadSpec('users');
    expect(spec).not.toBeNull();

    const { screenshot, html } = await screenshotDesignSpec(
      spec!,
      tokens,
      V2_BUILTIN_CATALOG,
      { width: 1440, outputPath: join(SCREENSHOT_DIR, 'users-rendered.png') },
    );

    expect(screenshot.length).toBeGreaterThan(1000);
    writeFileSync(join(SCREENSHOT_DIR, 'users-rendered.html'), html);
    console.log(`Users rendered: ${(screenshot.length / 1024).toFixed(0)}KB PNG, ${(html.length / 1024).toFixed(0)}KB HTML`);
  });
});
