/**
 * Mock CompletionResult for the design-penpot-v2 stage.
 * Returns a submit_design tool call with a minimal DesignSpec V2.
 * Used by `--mock` flag to skip LLM calls during development.
 */
export const mockDesignPenpotV2Result = {
  ok: true as const,
  value: {
    content: '',
    toolCalls: [
      {
        id: 'mock-tool-call-001',
        name: 'submit_design',
        args: {
          viewport_width: 420,
          nodes: [
            {
              id: 'root',
              type: 'frame',
              name: 'PageLayout',
              parent_id: null,
              x: 0,
              y: 0,
              width: 420,
              height: 800,
              fill: '{colors.semantic.background-primary}',
              layout: 'column',
              gap: 24,
              padding_top: 24,
              padding_bottom: 24,
              padding_left: 16,
              padding_right: 16,
            },
            {
              id: 'header',
              type: 'frame',
              name: 'Header',
              parent_id: 'root',
              width: 'fill',
              height: 64,
              layout: 'column',
              gap: 4,
              padding_top: 0,
              padding_bottom: 0,
              padding_left: 0,
              padding_right: 0,
            },
            {
              id: 'title',
              type: 'text',
              name: 'Title',
              parent_id: 'header',
              text: 'Good morning',
              font_family: '{typography.font_families.display}',
              font_size: 24,
              font_weight: '700',
              fill: '{colors.semantic.text-primary}',
              width: 'fill',
            },
            {
              id: 'subtitle',
              type: 'text',
              name: 'Subtitle',
              parent_id: 'header',
              text: 'Choose your session type',
              font_family: '{typography.font_families.body}',
              font_size: 14,
              font_weight: '400',
              fill: '{colors.semantic.text-secondary}',
              width: 'fill',
            },
            {
              id: 'card-group',
              type: 'frame',
              name: 'CardGroup',
              parent_id: 'root',
              width: 'fill',
              layout: 'column',
              gap: 12,
              padding_top: 0,
              padding_bottom: 0,
              padding_left: 0,
              padding_right: 0,
            },
            {
              id: 'card-1',
              type: 'frame',
              name: 'Card-DeepWork',
              parent_id: 'card-group',
              width: 'fill',
              height: 72,
              fill: '{colors.semantic.surface-elevated}',
              corner_radius: '{borders.radius.large}',
              stroke: '{colors.semantic.border-default}',
              stroke_width: 1,
              layout: 'column',
              gap: 4,
              padding_top: 16,
              padding_bottom: 16,
              padding_left: 16,
              padding_right: 16,
            },
            {
              id: 'card-1-title',
              type: 'text',
              name: 'CardTitle-DeepWork',
              parent_id: 'card-1',
              text: 'Deep Work',
              font_family: '{typography.font_families.body}',
              font_size: 16,
              font_weight: '600',
              fill: '{colors.semantic.text-primary}',
              width: 'fill',
            },
            {
              id: 'card-1-desc',
              type: 'text',
              name: 'CardDesc-DeepWork',
              parent_id: 'card-1',
              text: 'Focused session for deep concentration',
              font_family: '{typography.font_families.body}',
              font_size: 13,
              font_weight: '400',
              fill: '{colors.semantic.text-secondary}',
              width: 'fill',
            },
            {
              id: 'action-btn',
              type: 'frame',
              name: 'StartButton',
              parent_id: 'root',
              width: 'fill',
              height: 56,
              fill: '{colors.semantic.cta-primary}',
              corner_radius: '{borders.radius.medium}',
              layout: 'row',
              gap: 0,
              align_items: 'center',
              justify_content: 'center',
              padding_top: 0,
              padding_bottom: 0,
              padding_left: 0,
              padding_right: 0,
            },
            {
              id: 'action-btn-text',
              type: 'text',
              name: 'StartButtonText',
              parent_id: 'action-btn',
              text: 'Start Session',
              font_family: '{typography.font_families.body}',
              font_size: 16,
              font_weight: '600',
              fill: '{colors.semantic.text-on-cta}',
            },
          ],
        },
      },
    ],
    usage: { inputTokens: 12000, outputTokens: 3000 },
    cost: {
      inputCostUsd: 0,
      outputCostUsd: 0,
      totalCostUsd: 0,
      model: 'mock',
      timestamp: new Date().toISOString(),
    },
    model: 'mock',
    latencyMs: 0,
    finishReason: 'tool_use' as const,
  },
};
