const mockDesignOutput = {
    ok: true,
    value: {
        content: "",
        toolCalls: [
            {
                id: "toolu_01RfZffsbfredS7FU3m6687A",
                name: "submit_design",
                args: {
                    screen: "session-picker",
                    width: 1440,
                    nodes: {
                        root: {
                            parent: null,
                            order: 0,
                            type: "page",
                            width: 1440,
                            layout: {
                                dir: "column",
                                align: "center",
                                gap: 0,
                            },
                            background: "background-primary",
                        },
                        topbar: {
                            parent: "root",
                            order: 0,
                            type: "header",
                            width: 1440,
                            height: 56,
                            layout: {
                                dir: "row",
                                align: "center",
                                justify: "space-between",
                                px: 32,
                                py: 0,
                            },
                            background: "surface-primary",
                            shadow: "sm",
                        },
                        "topbar-logo": {
                            parent: "topbar",
                            order: 0,
                            type: "text",
                            content: "Focusly",
                            typography: "heading-3",
                            color: "text-primary",
                            weight: 700,
                        },
                        "topbar-settings-btn": {
                            parent: "topbar",
                            order: 1,
                            catalog: "button-primary",
                            label: "Settings",
                            overrides: {
                                background: "transparent",
                                color: "text-secondary",
                                border: "none",
                                shadow: "none",
                                font_size: 13,
                            },
                        },
                        "page-content": {
                            parent: "root",
                            order: 1,
                            type: "container",
                            width: 600,
                            layout: {
                                dir: "column",
                                gap: 32,
                                py: 48,
                                px: 0,
                            },
                        },
                        "greeting-section": {
                            parent: "page-content",
                            order: 0,
                            type: "container",
                            width: "fill",
                            layout: {
                                dir: "column",
                                gap: 6,
                                align: "center",
                            },
                        },
                        "greeting-text": {
                            parent: "greeting-section",
                            order: 0,
                            type: "text",
                            content: "Good morning, Alex ☀️",
                            typography: "heading-1",
                            color: "text-primary",
                            textAlign: "center",
                        },
                        "greeting-subtitle": {
                            parent: "greeting-section",
                            order: 1,
                            type: "text",
                            content: "Ready to make the most of your morning? Let's build on that 7-day streak.",
                            typography: "body",
                            color: "text-secondary",
                            textAlign: "center",
                        },
                        "stat-strip": {
                            parent: "page-content",
                            order: 1,
                            type: "container",
                            width: "fill",
                            layout: {
                                dir: "row",
                                align: "center",
                                justify: "center",
                                gap: 0,
                            },
                            background: "surface-primary",
                            shadow: "sm",
                            radius: 12,
                        },
                        "stat-streak": {
                            parent: "stat-strip",
                            order: 0,
                            type: "container",
                            layout: {
                                dir: "column",
                                align: "center",
                                gap: 4,
                                px: 32,
                                py: 16,
                            },
                        },
                        "stat-streak-value": {
                            parent: "stat-streak",
                            order: 0,
                            type: "text",
                            content: "🔥 7",
                            typography: "heading-2",
                            color: "warning",
                            textAlign: "center",
                        },
                        "stat-streak-label": {
                            parent: "stat-streak",
                            order: 1,
                            type: "text",
                            content: "Day Streak",
                            typography: "label",
                            color: "text-secondary",
                            textAlign: "center",
                        },
                        "stat-divider-1": {
                            parent: "stat-strip",
                            order: 1,
                            type: "divider",
                        },
                        "stat-weekly": {
                            parent: "stat-strip",
                            order: 2,
                            type: "container",
                            layout: {
                                dir: "column",
                                align: "center",
                                gap: 4,
                                px: 32,
                                py: 16,
                            },
                        },
                        "stat-weekly-value": {
                            parent: "stat-weekly",
                            order: 0,
                            type: "text",
                            content: "12.5 hrs",
                            typography: "heading-2",
                            color: "text-primary",
                            textAlign: "center",
                        },
                        "stat-weekly-label": {
                            parent: "stat-weekly",
                            order: 1,
                            type: "text",
                            content: "This Week",
                            typography: "label",
                            color: "text-secondary",
                            textAlign: "center",
                        },
                        "stat-divider-2": {
                            parent: "stat-strip",
                            order: 3,
                            type: "divider",
                        },
                        "stat-total": {
                            parent: "stat-strip",
                            order: 4,
                            type: "container",
                            layout: {
                                dir: "column",
                                align: "center",
                                gap: 4,
                                px: 32,
                                py: 16,
                            },
                        },
                        "stat-total-value": {
                            parent: "stat-total",
                            order: 0,
                            type: "text",
                            content: "148",
                            typography: "heading-2",
                            color: "text-primary",
                            textAlign: "center",
                        },
                        "stat-total-label": {
                            parent: "stat-total",
                            order: 1,
                            type: "text",
                            content: "Total Sessions",
                            typography: "label",
                            color: "text-secondary",
                            textAlign: "center",
                        },
                        "config-card": {
                            parent: "page-content",
                            order: 2,
                            type: "section",
                            width: "fill",
                            layout: {
                                dir: "column",
                                gap: 24,
                                px: 24,
                                py: 24,
                            },
                            background: "surface-primary",
                            shadow: "md",
                            radius: 16,
                        },
                        "session-type-section": {
                            parent: "config-card",
                            order: 0,
                            type: "container",
                            width: "fill",
                            layout: {
                                dir: "column",
                                gap: 12,
                            },
                        },
                        "session-type-label": {
                            parent: "session-type-section",
                            order: 0,
                            type: "text",
                            content: "Session Type",
                            typography: "heading-3",
                            color: "text-primary",
                        },
                        "session-type-cards": {
                            parent: "session-type-section",
                            order: 1,
                            type: "container",
                            width: "fill",
                            layout: {
                                dir: "row",
                                gap: 12,
                                align: "stretch",
                            },
                        },
                        "card-deep-work": {
                            parent: "session-type-cards",
                            order: 0,
                            type: "container",
                            width: "fill",
                            layout: {
                                dir: "column",
                                gap: 10,
                                px: 16,
                                py: 16,
                            },
                            background: "surface-primary",
                            shadow: "sm",
                            radius: 12,
                            overrides: {
                                border_color: "cta-primary",
                                border_width: 2,
                            },
                        },
                        "card-deep-work-icon-wrap": {
                            parent: "card-deep-work",
                            order: 0,
                            type: "container",
                            width: 40,
                            height: 40,
                            layout: {
                                dir: "row",
                                align: "center",
                                justify: "center",
                            },
                            background: "cta-primary",
                            radius: 10,
                        },
                        "card-deep-work-icon": {
                            parent: "card-deep-work-icon-wrap",
                            order: 0,
                            type: "text",
                            content: "⚡",
                            typography: "body",
                            textAlign: "center",
                        },
                        "card-deep-work-name": {
                            parent: "card-deep-work",
                            order: 1,
                            type: "text",
                            content: "Deep Work",
                            typography: "heading-3",
                            color: "text-primary",
                            weight: 600,
                        },
                        "card-deep-work-desc": {
                            parent: "card-deep-work",
                            order: 2,
                            type: "text",
                            content: "Focused, distraction-free work blocks",
                            typography: "label",
                            color: "text-secondary",
                        },
                        "card-deep-work-badge": {
                            parent: "card-deep-work",
                            order: 3,
                            catalog: "badge-info",
                            label: "Selected",
                            overrides: {
                                font_size: 11,
                            },
                        },
                        "card-meditation": {
                            parent: "session-type-cards",
                            order: 1,
                            type: "container",
                            width: "fill",
                            layout: {
                                dir: "column",
                                gap: 10,
                                px: 16,
                                py: 16,
                            },
                            background: "surface-primary",
                            shadow: "sm",
                            radius: 12,
                        },
                        "card-meditation-icon-wrap": {
                            parent: "card-meditation",
                            order: 0,
                            type: "container",
                            width: 40,
                            height: 40,
                            layout: {
                                dir: "row",
                                align: "center",
                                justify: "center",
                            },
                            background: "surface-secondary",
                            radius: 10,
                        },
                        "card-meditation-icon": {
                            parent: "card-meditation-icon-wrap",
                            order: 0,
                            type: "text",
                            content: "🧘",
                            typography: "body",
                            textAlign: "center",
                        },
                        "card-meditation-name": {
                            parent: "card-meditation",
                            order: 1,
                            type: "text",
                            content: "Meditation",
                            typography: "heading-3",
                            color: "text-primary",
                            weight: 600,
                        },
                        "card-meditation-desc": {
                            parent: "card-meditation",
                            order: 2,
                            type: "text",
                            content: "Guided mindfulness and breathing",
                            typography: "label",
                            color: "text-secondary",
                        },
                        "card-power-nap": {
                            parent: "session-type-cards",
                            order: 2,
                            type: "container",
                            width: "fill",
                            layout: {
                                dir: "column",
                                gap: 10,
                                px: 16,
                                py: 16,
                            },
                            background: "surface-primary",
                            shadow: "sm",
                            radius: 12,
                        },
                        "card-power-nap-icon-wrap": {
                            parent: "card-power-nap",
                            order: 0,
                            type: "container",
                            width: 40,
                            height: 40,
                            layout: {
                                dir: "row",
                                align: "center",
                                justify: "center",
                            },
                            background: "surface-secondary",
                            radius: 10,
                        },
                        "card-power-nap-icon": {
                            parent: "card-power-nap-icon-wrap",
                            order: 0,
                            type: "text",
                            content: "💤",
                            typography: "body",
                            textAlign: "center",
                        },
                        "card-power-nap-name": {
                            parent: "card-power-nap",
                            order: 1,
                            type: "text",
                            content: "Power Nap",
                            typography: "heading-3",
                            color: "text-primary",
                            weight: 600,
                        },
                        "card-power-nap-desc": {
                            parent: "card-power-nap",
                            order: 2,
                            type: "text",
                            content: "Short restorative rest to recharge",
                            typography: "label",
                            color: "text-secondary",
                        },
                        "config-divider-1": {
                            parent: "config-card",
                            order: 1,
                            type: "divider",
                        },
                        "duration-section": {
                            parent: "config-card",
                            order: 2,
                            type: "container",
                            width: "fill",
                            layout: {
                                dir: "column",
                                gap: 12,
                            },
                        },
                        "duration-label": {
                            parent: "duration-section",
                            order: 0,
                            type: "text",
                            content: "Duration",
                            typography: "heading-3",
                            color: "text-primary",
                        },
                        "duration-chip-row": {
                            parent: "duration-section",
                            order: 1,
                            type: "container",
                            width: "fill",
                            layout: {
                                dir: "row",
                                gap: 8,
                                align: "center",
                            },
                        },
                        "chip-15": {
                            parent: "duration-chip-row",
                            order: 0,
                            catalog: "chip",
                            label: "15 min",
                            overrides: {
                                selected: false,
                            },
                        },
                        "chip-25": {
                            parent: "duration-chip-row",
                            order: 1,
                            catalog: "chip",
                            label: "25 min",
                            overrides: {
                                selected: true,
                                background: "cta-primary",
                                color: "text-on-cta",
                                border_color: "cta-primary",
                            },
                        },
                        "chip-45": {
                            parent: "duration-chip-row",
                            order: 2,
                            catalog: "chip",
                            label: "45 min",
                            overrides: {
                                selected: false,
                            },
                        },
                        "chip-60": {
                            parent: "duration-chip-row",
                            order: 3,
                            catalog: "chip",
                            label: "60 min",
                            overrides: {
                                selected: false,
                            },
                        },
                        "chip-90": {
                            parent: "duration-chip-row",
                            order: 4,
                            catalog: "chip",
                            label: "90 min",
                            overrides: {
                                selected: false,
                            },
                        },
                        "chip-custom": {
                            parent: "duration-chip-row",
                            order: 5,
                            catalog: "chip",
                            label: "Custom",
                            overrides: {
                                selected: false,
                            },
                        },
                        "custom-duration-row": {
                            parent: "duration-section",
                            order: 2,
                            type: "container",
                            width: "fill",
                            layout: {
                                dir: "row",
                                gap: 12,
                                align: "center",
                            },
                        },
                        "custom-duration-input": {
                            parent: "custom-duration-row",
                            order: 0,
                            catalog: "input-text",
                            label: "Custom duration (minutes)",
                            placeholder: "e.g. 35",
                            value: "",
                            width: "fill",
                        },
                        "custom-duration-apply-btn": {
                            parent: "custom-duration-row",
                            order: 1,
                            catalog: "button-primary",
                            label: "Apply",
                            overrides: {
                                variant: "secondary",
                            },
                        },
                        "config-divider-2": {
                            parent: "config-card",
                            order: 3,
                            type: "divider",
                        },
                        "toggle-section": {
                            parent: "config-card",
                            order: 4,
                            type: "container",
                            width: "fill",
                            layout: {
                                dir: "column",
                                gap: 4,
                            },
                        },
                        "toggle-section-label": {
                            parent: "toggle-section",
                            order: 0,
                            type: "text",
                            content: "Session Options",
                            typography: "heading-3",
                            color: "text-primary",
                        },
                        "toggle-spacer": {
                            parent: "toggle-section",
                            order: 1,
                            type: "spacer",
                            height: 8,
                        },
                        "break-reminder-row": {
                            parent: "toggle-section",
                            order: 2,
                            type: "container",
                            width: "fill",
                            layout: {
                                dir: "row",
                                align: "center",
                                justify: "space-between",
                                px: 0,
                                py: 8,
                            },
                        },
                        "break-reminder-text": {
                            parent: "break-reminder-row",
                            order: 0,
                            type: "container",
                            layout: {
                                dir: "column",
                                gap: 2,
                            },
                        },
                        "break-reminder-label": {
                            parent: "break-reminder-text",
                            order: 0,
                            type: "text",
                            content: "Break Reminders",
                            typography: "body",
                            color: "text-primary",
                        },
                        "break-reminder-sublabel": {
                            parent: "break-reminder-text",
                            order: 1,
                            type: "text",
                            content: "Remind me every 25 min to stretch",
                            typography: "label",
                            color: "text-secondary",
                        },
                        "break-reminder-toggle": {
                            parent: "break-reminder-row",
                            order: 1,
                            catalog: "switch",
                            label: "",
                            value: "on",
                            overrides: {
                                checked: true,
                            },
                        },
                        "toggle-divider": {
                            parent: "toggle-section",
                            order: 3,
                            type: "divider",
                        },
                        "ambient-sound-row": {
                            parent: "toggle-section",
                            order: 4,
                            type: "container",
                            width: "fill",
                            layout: {
                                dir: "row",
                                align: "center",
                                justify: "space-between",
                                px: 0,
                                py: 8,
                            },
                        },
                        "ambient-sound-text": {
                            parent: "ambient-sound-row",
                            order: 0,
                            type: "container",
                            layout: {
                                dir: "column",
                                gap: 2,
                            },
                        },
                        "ambient-sound-label": {
                            parent: "ambient-sound-text",
                            order: 0,
                            type: "text",
                            content: "Ambient Sound",
                            typography: "body",
                            color: "text-primary",
                        },
                        "ambient-sound-sublabel": {
                            parent: "ambient-sound-text",
                            order: 1,
                            type: "text",
                            content: "Forest Rain — playing during session",
                            typography: "label",
                            color: "text-secondary",
                        },
                        "ambient-sound-toggle": {
                            parent: "ambient-sound-row",
                            order: 1,
                            catalog: "switch",
                            label: "",
                            value: "on",
                            overrides: {
                                checked: true,
                            },
                        },
                        "start-btn": {
                            parent: "page-content",
                            order: 3,
                            catalog: "button-primary",
                            label: "Start Deep Work Session",
                            width: "fill",
                            height: 56,
                            overrides: {
                                border_radius: 14,
                                font_size: 16,
                                font_weight: 600,
                            },
                        },
                        "recent-label": {
                            parent: "page-content",
                            order: 4,
                            type: "text",
                            content: "Recent Sessions",
                            typography: "heading-3",
                            color: "text-primary",
                        },
                        "recent-sessions-list": {
                            parent: "page-content",
                            order: 5,
                            type: "container",
                            width: "fill",
                            layout: {
                                dir: "column",
                                gap: 8,
                            },
                        },
                        "recent-session-1": {
                            parent: "recent-sessions-list",
                            order: 0,
                            type: "container",
                            width: "fill",
                            layout: {
                                dir: "row",
                                align: "center",
                                justify: "space-between",
                                px: 16,
                                py: 12,
                            },
                            background: "surface-primary",
                            shadow: "sm",
                            radius: 10,
                        },
                        "recent-session-1-left": {
                            parent: "recent-session-1",
                            order: 0,
                            type: "container",
                            layout: {
                                dir: "row",
                                align: "center",
                                gap: 12,
                            },
                        },
                        "recent-session-1-icon": {
                            parent: "recent-session-1-left",
                            order: 0,
                            type: "text",
                            content: "⚡",
                            typography: "body",
                        },
                        "recent-session-1-info": {
                            parent: "recent-session-1-left",
                            order: 1,
                            type: "container",
                            layout: {
                                dir: "column",
                                gap: 2,
                            },
                        },
                        "recent-session-1-name": {
                            parent: "recent-session-1-info",
                            order: 0,
                            type: "text",
                            content: "Deep Work",
                            typography: "body",
                            color: "text-primary",
                            weight: 500,
                        },
                        "recent-session-1-meta": {
                            parent: "recent-session-1-info",
                            order: 1,
                            type: "text",
                            content: "Today · 45 min",
                            typography: "label",
                            color: "text-secondary",
                        },
                        "recent-session-1-badge": {
                            parent: "recent-session-1",
                            order: 1,
                            catalog: "badge-success",
                            label: "Completed",
                        },
                        "recent-session-2": {
                            parent: "recent-sessions-list",
                            order: 1,
                            type: "container",
                            width: "fill",
                            layout: {
                                dir: "row",
                                align: "center",
                                justify: "space-between",
                                px: 16,
                                py: 12,
                            },
                            background: "surface-primary",
                            shadow: "sm",
                            radius: 10,
                        },
                        "recent-session-2-left": {
                            parent: "recent-session-2",
                            order: 0,
                            type: "container",
                            layout: {
                                dir: "row",
                                align: "center",
                                gap: 12,
                            },
                        },
                        "recent-session-2-icon": {
                            parent: "recent-session-2-left",
                            order: 0,
                            type: "text",
                            content: "🧘",
                            typography: "body",
                        },
                        "recent-session-2-info": {
                            parent: "recent-session-2-left",
                            order: 1,
                            type: "container",
                            layout: {
                                dir: "column",
                                gap: 2,
                            },
                        },
                        "recent-session-2-name": {
                            parent: "recent-session-2-info",
                            order: 0,
                            type: "text",
                            content: "Meditation",
                            typography: "body",
                            color: "text-primary",
                            weight: 500,
                        },
                        "recent-session-2-meta": {
                            parent: "recent-session-2-info",
                            order: 1,
                            type: "text",
                            content: "Yesterday · 15 min",
                            typography: "label",
                            color: "text-secondary",
                        },
                        "recent-session-2-badge": {
                            parent: "recent-session-2",
                            order: 1,
                            catalog: "badge-success",
                            label: "Completed",
                        },
                        "recent-session-3": {
                            parent: "recent-sessions-list",
                            order: 2,
                            type: "container",
                            width: "fill",
                            layout: {
                                dir: "row",
                                align: "center",
                                justify: "space-between",
                                px: 16,
                                py: 12,
                            },
                            background: "surface-primary",
                            shadow: "sm",
                            radius: 10,
                        },
                        "recent-session-3-left": {
                            parent: "recent-session-3",
                            order: 0,
                            type: "container",
                            layout: {
                                dir: "row",
                                align: "center",
                                gap: 12,
                            },
                        },
                        "recent-session-3-icon": {
                            parent: "recent-session-3-left",
                            order: 0,
                            type: "text",
                            content: "⚡",
                            typography: "body",
                        },
                        "recent-session-3-info": {
                            parent: "recent-session-3-left",
                            order: 1,
                            type: "container",
                            layout: {
                                dir: "column",
                                gap: 2,
                            },
                        },
                        "recent-session-3-name": {
                            parent: "recent-session-3-info",
                            order: 0,
                            type: "text",
                            content: "Deep Work",
                            typography: "body",
                            color: "text-primary",
                            weight: 500,
                        },
                        "recent-session-3-meta": {
                            parent: "recent-session-3-info",
                            order: 1,
                            type: "text",
                            content: "Mon · 90 min",
                            typography: "label",
                            color: "text-secondary",
                        },
                        "recent-session-3-badge": {
                            parent: "recent-session-3",
                            order: 1,
                            catalog: "badge-warning",
                            label: "Ended early",
                        },
                        "bottom-spacer": {
                            parent: "page-content",
                            order: 6,
                            type: "spacer",
                            height: 32,
                        },
                    },
                },
            },
        ],
        usage: {
            inputTokens: 15361,
            outputTokens: 6971,
            cacheReadTokens: 0,
            cacheWriteTokens: 0,
        },
        cost: {
            inputCostUsd: 0.046083,
            outputCostUsd: 0.10456499999999999,
            totalCostUsd: 0.150648,
            model: "claude-sonnet-4-6",
            timestamp: "2026-03-29T08:21:38.098Z",
        },
        model: "claude-sonnet-4-6",
        latencyMs: 61685,
        finishReason: "tool_use",
    },
}

export default mockDesignOutput;