/**
 * @module @agentforge/agents-cicd/pr-manager
 *
 * PR Manager: creates pull requests via MCP client after CI passes.
 * PR description includes task ID, spec reference, generated files,
 * test results, and cost. Emits PRCreated event to trigger both
 * the PR reviewer agent and security scanner agent.
 */

import type {
  AgentContract,
  AgentContext,
  AgentWorkFn,
  Result,
  EventBus,
  TaskEntry,
} from '@agentforge/core';
import { Ok, Err, runAgent } from '@agentforge/core';

// ============================================================================
// Types
// ============================================================================

/** Input for the PR manager. */
export interface PRManagerInput {
  readonly task: TaskEntry;
  readonly projectRoot: string;
  readonly branch: string;
  readonly filesGenerated: readonly string[];
  readonly testResults: string;
  readonly costUsd: number;
  readonly designRef?: string;
}

/** Output produced by the PR manager. */
export interface PRManagerOutput {
  readonly prNumber: number;
  readonly prUrl: string;
  readonly branch: string;
}

// ============================================================================
// Contract
// ============================================================================

/** The agent contract for the PR manager. */
export const PR_MANAGER_CONTRACT: AgentContract = {
  role: 'pr_manager',
  description: 'Creates pull requests via MCP client after CI passes',
  category: 'cicd',
  provider: 'claude-haiku-4-5',
  execution: { mode: 'complete', progress_events: false, max_context_tokens: 10000 },
  tools: ['github.create_pr'],
  permissions: ['read_code', 'create_pr', 'create_branch'],
  denied: ['write_design', 'deploy_staging', 'deploy_production', 'merge_pr'],
  hitl_policy: 'notify_only',
  budget: { max_tokens_per_task: 5000, max_cost_per_task_usd: 0.1 },
  on_complete: 'PRCreated',
  on_error: 'notify_human + pause',
  context: {},
};

// ============================================================================
// Helpers
// ============================================================================

/** Build the PR description with task context. */
export const buildPRDescription = (input: PRManagerInput): string => {
  const sections = [
    `## Task`,
    `- **ID:** ${input.task.id}`,
    `- **Title:** ${input.task.title}`,
    `- **Spec:** ${input.task.spec_ref}`,
    `- **Agent:** ${input.task.agent}`,
  ];

  if (input.designRef) {
    sections.push(`- **Design:** ${input.designRef}`);
  }

  sections.push(
    '',
    '## Generated Files',
    ...input.filesGenerated.map((f) => `- \`${f}\``),
    '',
    '## Test Results',
    '```',
    input.testResults,
    '```',
    '',
    `## Cost`,
    `$${input.costUsd.toFixed(2)}`,
    '',
    '---',
    '_Generated by AgentForge_',
  );

  return sections.join('\n');
};

// ============================================================================
// Work function
// ============================================================================

/**
 * PR manager work function.
 * Creates a PR via MCP with full task context and emits PRCreated.
 */
export const prManagerWork: AgentWorkFn<PRManagerInput, PRManagerOutput> = async (
  input,
  _provider,
  _learnings,
  context,
) => {
  const { task, branch } = input;

  // 1. Build PR description
  const body = buildPRDescription(input);
  const title = `[${task.id}] ${task.title}`;

  // 2. Create PR via MCP
  const prResult = await context.mcpClient!.callTool('github', 'create_pr', {
    title,
    body,
    head: branch,
    base: 'main',
  });

  if (!prResult.ok) {
    return Err({
      code: 'INVALID_STATE' as const,
      message: `Failed to create PR for ${branch}: ${prResult.error.message}`,
      recoverable: true,
    });
  }

  const prData = prResult.value as { number?: number; html_url?: string };
  const prNumber = prData.number ?? 0;
  const prUrl = prData.html_url ?? '';

  // 3. Emit PRCreated event (triggers PR reviewer + security scanner)
  context.eventBus.publish({
    type: 'PRCreated',
    taskId: task.id,
    prNumber,
    branch,
    source: 'agent:pr_manager',
    timestamp: Date.now(),
  });

  return Ok({ prNumber, prUrl, branch });
};

// ============================================================================
// Execution + Registration
// ============================================================================

/** Execute the PR manager through the full governance pipeline. */
export const executePRManager = async (
  contract: AgentContract,
  context: AgentContext,
  input: PRManagerInput,
): Promise<Result<unknown>> => {
  return runAgent(
    contract,
    context,
    input,
    'create_pr',
    input.branch,
    `Create PR for task ${input.task.id}`,
    prManagerWork,
  );
};

/** Register the PR manager to respond to CodeGenComplete events. */
export const registerPRManager = (
  eventBus: EventBus,
  context: AgentContext,
  contract: AgentContract = PR_MANAGER_CONTRACT,
): void => {
  eventBus.subscribe('CodeGenComplete', (event) => {
    void context.eventBus.publish({
      type: 'AgentStarted',
      agentId: contract.role,
      taskId: event.taskId,
      source: `agent:${contract.role}`,
      timestamp: Date.now(),
    });
  });
};
