/**
 * @module @agentforge/agents-clarifier/types
 *
 * Internal types for the Clarifier pipeline.
 * Cross-boundary schemas (EnrichedRequirement, AssumptionLedger) are
 * imported from @agentforge/core — NOT duplicated here.
 */

import type { EnrichedRequirement, AssumptionLedger, PRD, FeaturePlan } from '@agentforge/core';

/** Clarifier operates in two modes per vision Layer 5. */
export type ClarifierMode = 'bootstrap' | 'evolution';

/** How an option was generated — drives telemetry attribution (Phase 5). */
export type OptionSource = 'llm' | 'codebase' | 'template' | 'catalog';

/** A structured option for a clarification question. */
export interface StructuredOption {
  readonly label: string;
  readonly description: string;
  readonly rationale?: string;
  readonly tradeoffs?: readonly string[];
  readonly recommended: boolean;
  readonly source: OptionSource;
  readonly citation?: string;
}

/** A gap detected by the Gap/Conflict Detector (Task 1.3). */
export interface Gap {
  readonly id: string;
  readonly topic?: string;
  readonly description: string;
  readonly category: 'missing' | 'ambiguous' | 'conflicting' | 'incomplete';
  readonly confidence: number;
  readonly deterministic: boolean;
  readonly divergentInterpretations?: readonly StructuredOption[];
  readonly divergenceScore?: number;
}

/** A question generated by the Question Prioritizer (Task 1.4). */
export interface Question {
  readonly id: string;
  readonly gapId: string;
  readonly topic?: string;
  readonly text: string;
  readonly type: 'open' | 'multiple-choice';
  readonly options?: readonly StructuredOption[];
  readonly priority: number;
  readonly evpiScore: number;
}

/** Context gathered by the Context Retriever (Task 1.1). */
export interface ClarifierContext {
  readonly catalog?: string;
  readonly patternLibrary?: string;
  readonly platformConstraints?: string;
  readonly codeChunks?: readonly string[];
  readonly docChunks?: readonly string[];
  readonly designChunks?: readonly string[];
  readonly repoMap?: string;
}

/** User choice after max rounds exhausted. */
export type EscalationDecision = 'accept' | 'restart' | 'abandon' | null;

/** Human response to a batch of clarifier questions. */
export interface HumanResponse {
  readonly questionId: string;
  readonly answer: string;
  readonly selectedOption?: string;
}

/**
 * LangGraph state for the Clarifier pipeline.
 * Each field is a typed channel (vision Layer 2).
 */
export interface ClarifierState {
  readonly rawInput: string;
  readonly mode: ClarifierMode;
  readonly context: ClarifierContext;
  readonly gaps: readonly Gap[];
  readonly questions: readonly Question[];
  readonly humanResponses: readonly HumanResponse[];
  readonly requirement: EnrichedRequirement | null;
  readonly assumptions: AssumptionLedger | null;
  readonly round: number;
  readonly maxRounds: number;
  readonly error: string | null;
  readonly prdDraft: PRD | null;
  readonly featurePlan: FeaturePlan | null;
  readonly criticRetries: number;
  readonly criticPassed: boolean;
  readonly escalationDecision: EscalationDecision;
  readonly threadId: string;
}

/** Execution log entry — lightweight, with file pointers. */
export interface PipelineStageRecord {
  readonly stageName: string;
  readonly turnNumber: number;
  readonly sequenceNumber: number;
  readonly timestamp: string;
  readonly threadId: string;
  readonly inputFile: string;
  readonly outputFile: string;
}

/** Q&A log entry — focused view for analysis. */
export interface QALogEntry {
  readonly timestamp: string;
  readonly threadId: string;
  readonly round: number;
  readonly questionId: string;
  readonly gapId: string;
  readonly topic?: string;
  readonly questionText: string;
  readonly questionType: 'open' | 'multiple-choice';
  readonly answer: string;
  readonly selectedOption?: string;
  readonly optionCount?: number;
  readonly evpiScore: number;
}
