/**
 * Domain events for the AgentForge event bus.
 *
 * All agent-to-agent and system communication flows through these
 * strongly-typed events. Each variant carries only the data it needs,
 * and the discriminated union lets consumers narrow on `type`.
 *
 * Every event includes `event_id` (unique per emission), `source`
 * (the emitter identity), and `timestamp`.
 *
 * ADR-002: Payloads are flat discriminated unions (not nested under a
 * generic `payload` field) for compile-time type safety.
 */

/**
 * Fields shared by every domain event.
 *
 * `event_id` is auto-generated by the event bus if not provided by the caller.
 */
export interface BaseDomainEventFields {
  /** Unique identifier for this event instance. */
  readonly event_id: string;
  /** Identity of the emitter (e.g. "orchestrator", "agent:frontend_coder", "cli"). */
  readonly source: string;
  /** Unix-epoch millisecond timestamp of emission. */
  readonly timestamp: number;
}

/** Fired when an agent begins executing a task. */
export interface AgentStarted extends BaseDomainEventFields {
  readonly type: 'AgentStarted';
  readonly agentId: string;
  readonly taskId: string;
}

/** Fired when an agent finishes a task successfully. */
export interface AgentCompleted extends BaseDomainEventFields {
  readonly type: 'AgentCompleted';
  readonly agentId: string;
  readonly taskId: string;
}

/** Fired when an agent fails while executing a task. */
export interface AgentFailed extends BaseDomainEventFields {
  readonly type: 'AgentFailed';
  readonly agentId: string;
  readonly taskId: string;
  readonly error: string;
}

/** Fired when a task transitions between statuses. */
export interface TaskStatusChanged extends BaseDomainEventFields {
  readonly type: 'TaskStatusChanged';
  readonly taskId: string;
  readonly from: string;
  readonly to: string;
}

/** Fired when spending approaches or exceeds a budget threshold. */
export interface BudgetAlert extends BaseDomainEventFields {
  readonly type: 'BudgetAlert';
  readonly level: string;
  readonly entityId: string;
  readonly currentSpendUsd: number;
  readonly limitUsd: number;
  readonly severity: 'warning' | 'hard_stop';
}

/** Fired when an agent reaches a gate that requires human approval. */
export interface HITLApprovalRequested extends BaseDomainEventFields {
  readonly type: 'HITLApprovalRequested';
  readonly gateId: string;
  readonly agentId: string;
  readonly taskId: string;
}

/** Fired when a human responds to an approval request. */
export interface HITLApprovalReceived extends BaseDomainEventFields {
  readonly type: 'HITLApprovalReceived';
  readonly gateId: string;
  readonly decision: string;
  readonly decidedBy?: string;
}

/** Fired when an agent acquires a lock on a spec file. */
export interface SpecLockAcquired extends BaseDomainEventFields {
  readonly type: 'SpecLockAcquired';
  readonly filePath: string;
  readonly agentId: string;
}

/** Fired when an agent releases a lock on a spec file. */
export interface SpecLockReleased extends BaseDomainEventFields {
  readonly type: 'SpecLockReleased';
  readonly filePath: string;
  readonly agentId: string;
}

/** Fired when a PR is merged into the default branch. */
export interface PRMerged extends BaseDomainEventFields {
  readonly type: 'PRMerged';
  readonly prNumber: number;
  readonly branch: string;
  readonly mergedBy: string;
}

/** Fired when spec drift is detected after a merge. */
export interface SpecDriftDetected extends BaseDomainEventFields {
  readonly type: 'SpecDriftDetected';
  readonly specFile: string;
  readonly deviations: readonly string[];
  readonly severity: 'minor' | 'significant';
}

/** Fired when a user requests a new page design. */
export interface PageRequested extends BaseDomainEventFields {
  readonly type: 'PageRequested';
  readonly pageId: string;
  readonly taskId: string;
  readonly description: string;
}

/** Fired when UX research completes for a page. */
export interface UXResearchComplete extends BaseDomainEventFields {
  readonly type: 'UXResearchComplete';
  readonly pageId: string;
  readonly taskId: string;
  readonly layoutSuggestions: readonly string[];
}

/** Fired when wireframe generation completes. */
export interface WireframeComplete extends BaseDomainEventFields {
  readonly type: 'WireframeComplete';
  readonly pageId: string;
  readonly taskId: string;
  readonly designRef: string;
}

/** Fired when a wireframe is approved by a human. */
export interface WireframeApproved extends BaseDomainEventFields {
  readonly type: 'WireframeApproved';
  readonly pageId: string;
  readonly taskId: string;
  readonly designRef: string;
}

/** Fired when visual design completes. */
export interface VisualDesignComplete extends BaseDomainEventFields {
  readonly type: 'VisualDesignComplete';
  readonly pageId: string;
  readonly taskId: string;
  readonly designRef: string;
}

/** Fired when design review completes. */
export interface DesignReviewComplete extends BaseDomainEventFields {
  readonly type: 'DesignReviewComplete';
  readonly pageId: string;
  readonly taskId: string;
  readonly passed: boolean;
  readonly issues: readonly string[];
}

/** Fired when the design phase completes and specs are ready for generation. */
export interface DesignPhaseComplete extends BaseDomainEventFields {
  readonly type: 'DesignPhaseComplete';
  readonly specRef: string;
  readonly designRef: string;
}

/** Fired when spec generation completes for a task. */
export interface SpecComplete extends BaseDomainEventFields {
  readonly type: 'SpecComplete';
  readonly specRef: string;
  readonly taskId: string;
}

/** Fired when task decomposition creates new tasks. */
export interface TasksCreated extends BaseDomainEventFields {
  readonly type: 'TasksCreated';
  readonly taskCount: number;
  readonly taskIds: readonly string[];
}

/** Fired when a code generation agent completes a task. */
export interface CodeGenComplete extends BaseDomainEventFields {
  readonly type: 'CodeGenComplete';
  readonly taskId: string;
  readonly agentId: string;
  readonly branch: string;
  readonly filesGenerated: readonly string[];
}

/** Fired when the test writer agent completes generating tests. */
export interface TestsComplete extends BaseDomainEventFields {
  readonly type: 'TestsComplete';
  readonly taskId: string;
  readonly agentId: string;
  readonly branch: string;
  readonly testFilesGenerated: readonly string[];
}

/** Fired when a PR is created and ready for review. */
export interface PRCreated extends BaseDomainEventFields {
  readonly type: 'PRCreated';
  readonly taskId: string;
  readonly prNumber: number;
  readonly branch: string;
}

/** Fired when the PR reviewer completes a code review. */
export interface ReviewComplete extends BaseDomainEventFields {
  readonly type: 'ReviewComplete';
  readonly taskId: string;
  readonly agentId: string;
  readonly prNumber: number;
  readonly decision: string;
}

// ─── CI/CD Phase Events ──────────────────────────────────────────────

/** Fired when a CI pipeline fails on generated code. */
export interface CIFailed extends BaseDomainEventFields {
  readonly type: 'CIFailed';
  readonly taskId: string;
  readonly branch: string;
  readonly runId: string;
  readonly logs: string;
}

/**
 * Fired when a CI pipeline run completes (pass or fail).
 * Covers the success path that CIFailed does not.
 * (architecture.md Section 11.3.3)
 */
export interface CIResult extends BaseDomainEventFields {
  readonly type: 'CIResult';
  readonly taskId: string;
  readonly passed: boolean;
  readonly logs?: string;
  readonly duration: number;
}

/** Fired when the security scanner completes analysis on a PR. */
export interface SecurityScanComplete extends BaseDomainEventFields {
  readonly type: 'SecurityScanComplete';
  readonly taskId: string;
  readonly prNumber: number;
  readonly findingsCount: number;
  readonly criticalCount: number;
  readonly passed: boolean;
}

/** Fired when the build agent completes a CI fix. */
export interface BuildFixComplete extends BaseDomainEventFields {
  readonly type: 'BuildFixComplete';
  readonly taskId: string;
  readonly branch: string;
  readonly fixApplied: boolean;
}

/** Fired when a deployment completes (staging or production). */
export interface DeployComplete extends BaseDomainEventFields {
  readonly type: 'DeployComplete';
  readonly taskId: string;
  readonly environment: 'staging' | 'production';
  readonly healthy: boolean;
}

/** Fired when an agent is aborted (cooperative or forced). */
export interface AgentAborted extends BaseDomainEventFields {
  readonly type: 'AgentAborted';
  readonly agentId: string;
  readonly taskId: string;
  readonly reason: string;
}

/** Fired when a human approves or requests changes at a HITL gate. */
export interface HITLApproved extends BaseDomainEventFields {
  readonly type: 'HITLApproved';
  readonly gateId: string;
  readonly decision: string;
  readonly feedback?: string;
  readonly source: string;
}

/**
 * Fired when a HITL approval gate times out and escalates.
 * (architecture.md Section 13.3)
 */
export interface HITLTimeout extends BaseDomainEventFields {
  readonly type: 'HITLTimeout';
  readonly gateId: string;
  readonly escalatedTo: string;
}

/**
 * Fired when an agent's trust level changes due to consecutive approvals.
 * (architecture.md Section 13.2)
 */
export interface TrustEscalated extends BaseDomainEventFields {
  readonly type: 'TrustEscalated';
  readonly agentRole: string;
  readonly previousLevel: string;
  readonly newLevel: string;
  readonly consecutiveApprovals: number;
}

/** Fired when a deployment fails health checks. */
export interface DeployFailed extends BaseDomainEventFields {
  readonly type: 'DeployFailed';
  readonly taskId: string;
  readonly environment: 'staging' | 'production';
  readonly reason: string;
}

// ─── UX Dashboard Squad Events ──────────────────────────────────────

/** Fired when a dashboard module is requested, triggering the UX agent pipeline. */
export interface UXModuleRequested extends BaseDomainEventFields {
  readonly type: 'UXModuleRequested';
  readonly moduleId: string;
  readonly taskId: string;
  readonly description: string;
  readonly prdRequirements: readonly string[];
}

/** Fired when the Research Agent completes a design brief for a module. */
export interface DesignBriefCompleted extends BaseDomainEventFields {
  readonly type: 'DesignBriefCompleted';
  readonly briefId: string;
  readonly moduleId: string;
  readonly taskId: string;
  readonly requirementIds: readonly string[];
}

/** Fired when the Planning Agent produces a component specification. */
export interface ComponentSpecReady extends BaseDomainEventFields {
  readonly type: 'ComponentSpecReady';
  readonly specRef: string;
  readonly moduleId: string;
  readonly taskId: string;
  readonly componentTree: readonly string[];
  readonly tokenBindings: Readonly<Record<string, string>>;
}

/** Fired when the Implementation Agent produces a draft for review. */
export interface ImplementationDraftReady extends BaseDomainEventFields {
  readonly type: 'ImplementationDraftReady';
  readonly taskId: string;
  readonly moduleId: string;
  readonly branch: string;
  readonly componentPaths: readonly string[];
}

/** Fired when the Review Agent completes a multi-dimensional UX review. */
export interface UXReviewCompleted extends BaseDomainEventFields {
  readonly type: 'UXReviewCompleted';
  readonly reviewId: string;
  readonly taskId: string;
  readonly moduleId: string;
  readonly issueCount: number;
  readonly severitySummary: Readonly<Record<string, number>>;
}

/** Fired when the Testing Agent completes a UI test suite run. */
export interface UXTestSuiteCompleted extends BaseDomainEventFields {
  readonly type: 'UXTestSuiteCompleted';
  readonly testRunId: string;
  readonly taskId: string;
  readonly passCount: number;
  readonly failCount: number;
  readonly healedCount: number;
}

/** Fired when a UX dashboard module is deployed to an environment. */
export interface UXModuleDeployed extends BaseDomainEventFields {
  readonly type: 'UXModuleDeployed';
  readonly moduleId: string;
  readonly deploymentId: string;
  readonly figmaContextRef: string;
}

/** Fired when the Clarifier completes requirement clarification (telemetry plane). */
export interface RequirementsClarified extends BaseDomainEventFields {
  readonly type: 'RequirementsClarified';
  readonly mode: 'bootstrap' | 'evolution';
  readonly questionCount: number;
  readonly roundCount: number;
  readonly assumptionCount: number;
  readonly confidence: number;
}

/** Fired when a pipeline run progresses through stages. */
export interface PipelineRunProgress extends BaseDomainEventFields {
  readonly type: 'PipelineRunProgress';
  readonly runId: string;
  readonly pipeline: 'init' | 'design-generate' | 'design-penpot' | 'design-browser' | 'design-chat-iterate';
  readonly stage: string;
  readonly stageIndex: number;
  readonly totalStages: number;
  readonly status: 'started' | 'completed' | 'failed' | 'log';
  readonly taskId?: string;
  readonly agentRole?: string;
  readonly detail?: string;
  readonly cost?: { totalCostUsd: number; tokensUsed: number };
}

/**
 * Discriminated union of every domain event in the system.
 *
 * Consumers can narrow on the `type` field to get full type safety
 * for the payload of each variant.
 */
export type DomainEvent =
  | AgentStarted
  | AgentCompleted
  | AgentFailed
  | TaskStatusChanged
  | BudgetAlert
  | HITLApprovalRequested
  | HITLApprovalReceived
  | SpecLockAcquired
  | SpecLockReleased
  | PRMerged
  | SpecDriftDetected
  | PageRequested
  | UXResearchComplete
  | WireframeComplete
  | WireframeApproved
  | VisualDesignComplete
  | DesignReviewComplete
  | DesignPhaseComplete
  | SpecComplete
  | TasksCreated
  | CodeGenComplete
  | TestsComplete
  | PRCreated
  | ReviewComplete
  | CIFailed
  | CIResult
  | SecurityScanComplete
  | BuildFixComplete
  | DeployComplete
  | DeployFailed
  | AgentAborted
  | HITLApproved
  | HITLTimeout
  | TrustEscalated
  | UXModuleRequested
  | DesignBriefCompleted
  | ComponentSpecReady
  | ImplementationDraftReady
  | UXReviewCompleted
  | UXTestSuiteCompleted
  | UXModuleDeployed
  | PipelineRunProgress
  | RequirementsClarified;

/** Union of all possible `type` values on a `DomainEvent`. */
export type DomainEventType = DomainEvent['type'];

/**
 * Distributive Omit — applies Omit to each member of a union individually,
 * preserving discriminated-union narrowing.
 */
type DistributiveOmit<T, K extends string> = T extends T ? Omit<T, K> : never;

/**
 * Input type for publishing events.
 * `event_id` is optional — the event bus auto-generates it if omitted.
 */
export type DomainEventInput = DistributiveOmit<DomainEvent, 'event_id'> & { event_id?: string };
