export type {
  BaseDomainEventFields,
  DomainEvent,
  DomainEventInput,
  DomainEventType,
  AgentStarted,
  AgentCompleted,
  AgentFailed,
  TaskStatusChanged,
  BudgetAlert,
  HITLApprovalRequested,
  HITLApprovalReceived,
  SpecLockAcquired,
  SpecLockReleased,
  PRMerged,
  SpecDriftDetected,
  PageRequested,
  UXResearchComplete,
  WireframeComplete,
  WireframeApproved,
  VisualDesignComplete,
  DesignReviewComplete,
  DesignPhaseComplete,
  SpecComplete,
  TasksCreated,
  CodeGenComplete,
  TestsComplete,
  PRCreated,
  ReviewComplete,
  CIFailed,
  CIResult,
  SecurityScanComplete,
  BuildFixComplete,
  DeployComplete,
  DeployFailed,
  AgentAborted,
  HITLApproved,
  HITLTimeout,
  TrustEscalated,
  UXModuleRequested,
  DesignBriefCompleted,
  ComponentSpecReady,
  ImplementationDraftReady,
  UXReviewCompleted,
  UXTestSuiteCompleted,
  UXModuleDeployed,
  PipelineRunProgress,
  RequirementsClarified,
} from './domain-events.js';

export type { EventBus, EventFilter, EventBusOptions } from './event-bus.js';
export { createEventBus } from './event-bus.js';

// File-based event bridge for Python engine interop
export {
  writeEvent as writeBridgeEvent,
  readNewEvents as readBridgeEvents,
  startBridgeWatcher,
} from './file-event-bridge.js';
